WW-99 | Tracking for Create New Wiki
Wikia/app pull request #11300
Opened 2016-09-09 12:21 UTC by rybmat

https://wikia-inc.atlassian.net/browse/WW-99

Tracking for whole Create New Wiki Flow.

@Wikia/west-wing

2016-09-09 12:22 UTC, WikiaTech commented
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/625fd2dc9af748cebe30ee04061f559cd1c7ed36/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/625fd2dc9af748cebe30ee04061f559cd1c7ed36/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L448](https://github.com/Wikia/app/blob/625fd2dc9af748cebe30ee04061f559cd1c7ed36/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L448): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L599](https://github.com/Wikia/app/blob/625fd2dc9af748cebe30ee04061f559cd1c7ed36/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L599): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L601](https://github.com/Wikia/app/blob/625fd2dc9af748cebe30ee04061f559cd1c7ed36/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L601): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [WikiBuilder.js#L609](https://github.com/Wikia/app/blob/625fd2dc9af748cebe30ee04061f559cd1c7ed36/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L609): Move this trailing comment on the previous empty line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3ATrailingComment)

2016-09-09 12:28 UTC, WikiaTech commented
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/c279d530f2c95bb347dbf17283e05630087aa541/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/c279d530f2c95bb347dbf17283e05630087aa541/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L448](https://github.com/Wikia/app/blob/c279d530f2c95bb347dbf17283e05630087aa541/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L448): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L599](https://github.com/Wikia/app/blob/c279d530f2c95bb347dbf17283e05630087aa541/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L599): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L601](https://github.com/Wikia/app/blob/c279d530f2c95bb347dbf17283e05630087aa541/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L601): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [WikiBuilder.js#L609](https://github.com/Wikia/app/blob/c279d530f2c95bb347dbf17283e05630087aa541/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L609): Move this trailing comment on the previous empty line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3ATrailingComment)

2016-09-09 12:42 UTC, idradm commented
LGTM, as long as you have buy-in on tracking labels

2016-09-09 12:59 UTC, sebastianmarzjan commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +			label: 'category-select'
Do we want to track the selected category?

2016-09-09 12:59 UTC, sebastianmarzjan commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +			label: 'intended-for-kids'
Do we want to track the selected value?

2016-09-09 12:59 UTC, sebastianmarzjan commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +				label: 'vertical-select'
Do we want to track the selected vertical?

2016-09-09 12:59 UTC, sebastianmarzjan commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +			label: 'change-language-link'
Do we want to track the selected language?

2016-09-09 12:59 UTC, sebastianmarzjan commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +			label: 'language-changed'
Do we want to track the selected language?

2016-09-09 13:29 UTC, WikiaTech commented
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/849be105a9e0529c0b28869a50afc95b2a906d53/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/849be105a9e0529c0b28869a50afc95b2a906d53/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L448](https://github.com/Wikia/app/blob/849be105a9e0529c0b28869a50afc95b2a906d53/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L448): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L599](https://github.com/Wikia/app/blob/849be105a9e0529c0b28869a50afc95b2a906d53/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L599): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L601](https://github.com/Wikia/app/blob/849be105a9e0529c0b28869a50afc95b2a906d53/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L601): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [WikiBuilder.js#L609](https://github.com/Wikia/app/blob/849be105a9e0529c0b28869a50afc95b2a906d53/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L609): Move this trailing comment on the previous empty line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3ATrailingComment)

2016-09-09 13:56 UTC, sebastianmarzjan commented on extensions/wikia/CreateNewWiki/js/WikiWelcome.js
> +		e.preventDefault();
Please add a comment why this is needed here (if it is)

2016-09-12 16:06 UTC, rybmat commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +			label: 'category-select'
Trevor: "It is enough to track only event of interacting with given options, no matter which one is chosen.
We'll get browser lang and user lang via Google Analytics, and can export wiki lang data (assuming it is created.) I highly doubt we'd change the CNW funnel for a specific language."

2016-09-12 16:06 UTC, rybmat commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +			label: 'intended-for-kids'
Trevor: "It is enough to track only event of interacting with given options, no matter which one is chosen.
We'll get browser lang and user lang via Google Analytics, and can export wiki lang data (assuming it is created.) I highly doubt we'd change the CNW funnel for a specific language."

2016-09-12 16:06 UTC, rybmat commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +				label: 'vertical-select'
Trevor: "It is enough to track only event of interacting with given options, no matter which one is chosen.
We'll get browser lang and user lang via Google Analytics, and can export wiki lang data (assuming it is created.) I highly doubt we'd change the CNW funnel for a specific language."

2016-09-12 16:06 UTC, rybmat commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +			label: 'change-language-link'
Trevor: "It is enough to track only event of interacting with given options, no matter which one is chosen.
We'll get browser lang and user lang via Google Analytics, and can export wiki lang data (assuming it is created.) I highly doubt we'd change the CNW funnel for a specific language."

2016-09-12 16:06 UTC, rybmat commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +			label: 'language-changed'
Trevor: "It is enough to track only event of interacting with given options, no matter which one is chosen.
We'll get browser lang and user lang via Google Analytics, and can export wiki lang data (assuming it is created.) I highly doubt we'd change the CNW funnel for a specific language."

2016-09-12 23:26 UTC, WikiaTech commented on extensions/wikia/CreateNewWiki/js/WikiWelcome.js
>  	'use strict';
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) Use of JavaScript strict mode may result in unexpected behaviour in some browsers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AStrictMode)

2016-09-12 23:26 UTC, WikiaTech commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
>  	'use strict';
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) Use of JavaScript strict mode may result in unexpected behaviour in some browsers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AStrictMode)

2016-09-12 23:26 UTC, WikiaTech commented
SonarQube analysis reported 9 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 5 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 4 info

Watch the comments in this conversation to review them.

#### 7 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/8ce3aa8c7e27accdfa96769d5b57e3a9555d9bcc/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/8ce3aa8c7e27accdfa96769d5b57e3a9555d9bcc/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L448](https://github.com/Wikia/app/blob/8ce3aa8c7e27accdfa96769d5b57e3a9555d9bcc/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L448): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L599](https://github.com/Wikia/app/blob/8ce3aa8c7e27accdfa96769d5b57e3a9555d9bcc/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L599): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L601](https://github.com/Wikia/app/blob/8ce3aa8c7e27accdfa96769d5b57e3a9555d9bcc/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L601): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [CreateNewWikiThemeDesignerOverrides.js#L4](https://github.com/Wikia/app/blob/8ce3aa8c7e27accdfa96769d5b57e3a9555d9bcc/extensions/wikia/CreateNewWiki/js/CreateNewWikiThemeDesignerOverrides.js#L4): Use of JavaScript strict mode may result in unexpected behaviour in some browsers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AStrictMode)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [WikiWelcome.js#L133](https://github.com/Wikia/app/blob/8ce3aa8c7e27accdfa96769d5b57e3a9555d9bcc/extensions/wikia/CreateNewWiki/js/WikiWelcome.js#L133): Use of JavaScript strict mode may result in unexpected behaviour in some browsers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AStrictMode)

2016-09-16 00:28 UTC, WikiaTech commented
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/7e2418fad75d5412560001ca4d9a4b4a1a4049b7/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/7e2418fad75d5412560001ca4d9a4b4a1a4049b7/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L448](https://github.com/Wikia/app/blob/7e2418fad75d5412560001ca4d9a4b4a1a4049b7/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L448): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L599](https://github.com/Wikia/app/blob/7e2418fad75d5412560001ca4d9a4b4a1a4049b7/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L599): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L601](https://github.com/Wikia/app/blob/7e2418fad75d5412560001ca4d9a4b4a1a4049b7/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L601): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

2016-09-16 19:59 UTC, sebastianmarzjan commented
LGTM

2016-09-16 20:45 UTC, dianafa commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +						}
what about
`label = descriptionVal === WikiBuilderCfg.descriptionplaceholder ? 'wiki-description-empty' : 'wiki-description-not-empty';

track({
    action: tracker.ACTIONS.SUBMIT,
    label: label
});
`

2016-09-20 20:35 UTC, WikiaTech commented
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/b85d9db53e4f668bb0659d2adda231a61acb034f/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/b85d9db53e4f668bb0659d2adda231a61acb034f/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L443](https://github.com/Wikia/app/blob/b85d9db53e4f668bb0659d2adda231a61acb034f/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L443): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L594](https://github.com/Wikia/app/blob/b85d9db53e4f668bb0659d2adda231a61acb034f/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L594): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L596](https://github.com/Wikia/app/blob/b85d9db53e4f668bb0659d2adda231a61acb034f/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L596): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

2016-09-20 23:42 UTC, dianafa commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +						var label = descriptionVal === WikiBuilderCfg.descriptionplaceholder ? 'wiki-description-empty' : 'wiki-description-not-empty';
let's move it till beginning of the block

2016-09-21 00:25 UTC, rybmat commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +						}
done

2016-09-21 00:25 UTC, rybmat commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +						var label = descriptionVal === WikiBuilderCfg.descriptionplaceholder ? 'wiki-description-empty' : 'wiki-description-not-empty';
done

2016-09-21 00:25 UTC, WikiaTech commented
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/406718fd1a11d8f64942f3c4464314c9793b0249/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/406718fd1a11d8f64942f3c4464314c9793b0249/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L446](https://github.com/Wikia/app/blob/406718fd1a11d8f64942f3c4464314c9793b0249/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L446): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L597](https://github.com/Wikia/app/blob/406718fd1a11d8f64942f3c4464314c9793b0249/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L597): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L599](https://github.com/Wikia/app/blob/406718fd1a11d8f64942f3c4464314c9793b0249/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L599): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

2016-09-21 16:20 UTC, idradm commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +							label: 'wiki-description-phalanx-validation'
Could you rename it to describe what it means?

2016-09-21 16:20 UTC, idradm commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +							label: 'wiki-description-phalanx-validation'
Could you rename it to describe what it means?

2016-09-21 16:21 UTC, idradm commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +						track({
Do we need two tracking events one after another? Can it be a single one?

2016-09-21 16:26 UTC, idradm requested changes
Could we make a naming convention more consistent? Some of the `label` values are action description, others element names and others technical step description. I'd propose to make them more create wiki context based, like a report of actions made by a user.

2016-09-22 23:16 UTC, WikiaTech commented
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/e97a9349c0ea4aeca3dc2049fb398503b1492355/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/e97a9349c0ea4aeca3dc2049fb398503b1492355/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L446](https://github.com/Wikia/app/blob/e97a9349c0ea4aeca3dc2049fb398503b1492355/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L446): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L597](https://github.com/Wikia/app/blob/e97a9349c0ea4aeca3dc2049fb398503b1492355/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L597): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L599](https://github.com/Wikia/app/blob/e97a9349c0ea4aeca3dc2049fb398503b1492355/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L599): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

2016-09-23 22:20 UTC, WikiaTech commented
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/fc383057cb57096bd571a8a01e2def6cafd16ce9/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/fc383057cb57096bd571a8a01e2def6cafd16ce9/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L433](https://github.com/Wikia/app/blob/fc383057cb57096bd571a8a01e2def6cafd16ce9/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L433): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L584](https://github.com/Wikia/app/blob/fc383057cb57096bd571a8a01e2def6cafd16ce9/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L584): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L586](https://github.com/Wikia/app/blob/fc383057cb57096bd571a8a01e2def6cafd16ce9/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L586): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

2016-09-23 22:24 UTC, idradm approved these changes

2016-09-23 22:26 UTC, sebastianmarzjan commented on extensions/wikia/CreateNewWiki/js/WikiBuilder.js
> +						var descriptionLabel = descriptionVal === WikiBuilderCfg.descriptionplaceholder ?
Adding parenthesis really helps in reading such parts of code

2016-09-23 22:28 UTC, WikiaTech commented
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/f239fd99ee16bc4965f914ac61b600cb88838bea/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/f239fd99ee16bc4965f914ac61b600cb88838bea/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L433](https://github.com/Wikia/app/blob/f239fd99ee16bc4965f914ac61b600cb88838bea/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L433): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L584](https://github.com/Wikia/app/blob/f239fd99ee16bc4965f914ac61b600cb88838bea/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L584): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L586](https://github.com/Wikia/app/blob/f239fd99ee16bc4965f914ac61b600cb88838bea/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L586): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

2016-09-23 22:29 UTC, sebastianmarzjan approved these changes

2016-09-23 23:07 UTC, WikiaTech commented
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L9](https://github.com/Wikia/app/blob/b3b7fc2e234a8841d4bb6293501d68452881924b/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L9): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L10](https://github.com/Wikia/app/blob/b3b7fc2e234a8841d4bb6293501d68452881924b/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L10): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L433](https://github.com/Wikia/app/blob/b3b7fc2e234a8841d4bb6293501d68452881924b/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L433): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L584](https://github.com/Wikia/app/blob/b3b7fc2e234a8841d4bb6293501d68452881924b/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L584): Remove this useless assignment to local variable "cityId" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiBuilder.js#L586](https://github.com/Wikia/app/blob/b3b7fc2e234a8841d4bb6293501d68452881924b/extensions/wikia/CreateNewWiki/js/WikiBuilder.js#L586): Remove this useless assignment to local variable "createStatusMessage" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

2016-09-29 13:44 UTC, merged