ADEN-3772 recover uap
Wikia/app pull request #11331
Opened 2016-09-14 14:29 UTC by v3rth

https://wikia-inc.atlassian.net/browse/ADEN-3918

2016-09-14 14:30 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +			styleName = "";
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove this useless assignment to local variable "styleName" [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

2016-09-14 14:30 UTC, WikiaTech commented
SonarQube analysis reported 5 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 4 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L207](https://github.com/Wikia/app/blob/b98dcc5316e625eb450a42e4c78c90aed0fd5c2e/extensions/wikia/AdEngine/js/SlotTweaker.js#L207): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L13](https://github.com/Wikia/app/blob/b98dcc5316e625eb450a42e4c78c90aed0fd5c2e/extensions/wikia/AdEngine/js/template/bfaa.js#L13): Function has 10 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/b98dcc5316e625eb450a42e4c78c90aed0fd5c2e/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L88](https://github.com/Wikia/app/blob/b98dcc5316e625eb450a42e4c78c90aed0fd5c2e/extensions/wikia/AdEngine/js/SlotTweaker.js#L88): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-14 14:33 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L207](https://github.com/Wikia/app/blob/f5b3d0df5d0a2071816aaca6d1fbbe782fc57bcb/extensions/wikia/AdEngine/js/SlotTweaker.js#L207): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L13](https://github.com/Wikia/app/blob/f5b3d0df5d0a2071816aaca6d1fbbe782fc57bcb/extensions/wikia/AdEngine/js/template/bfaa.js#L13): Function has 10 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/f5b3d0df5d0a2071816aaca6d1fbbe782fc57bcb/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L88](https://github.com/Wikia/app/blob/f5b3d0df5d0a2071816aaca6d1fbbe782fc57bcb/extensions/wikia/AdEngine/js/SlotTweaker.js#L88): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-14 15:17 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +	function noop(arg) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove the unused function parameter "arg". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2016-09-14 15:17 UTC, WikiaTech commented
SonarQube analysis reported 4 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L13](https://github.com/Wikia/app/blob/35c9e56ad181b6427876c21e8c9d66837ec43990/extensions/wikia/AdEngine/js/template/bfaa.js#L13): Function has 10 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/35c9e56ad181b6427876c21e8c9d66837ec43990/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L88](https://github.com/Wikia/app/blob/35c9e56ad181b6427876c21e8c9d66837ec43990/extensions/wikia/AdEngine/js/SlotTweaker.js#L88): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-14 15:20 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L207](https://github.com/Wikia/app/blob/f5b3d0df5d0a2071816aaca6d1fbbe782fc57bcb/extensions/wikia/AdEngine/js/SlotTweaker.js#L207): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L13](https://github.com/Wikia/app/blob/f5b3d0df5d0a2071816aaca6d1fbbe782fc57bcb/extensions/wikia/AdEngine/js/template/bfaa.js#L13): Function has 10 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/f5b3d0df5d0a2071816aaca6d1fbbe782fc57bcb/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L88](https://github.com/Wikia/app/blob/f5b3d0df5d0a2071816aaca6d1fbbe782fc57bcb/extensions/wikia/AdEngine/js/SlotTweaker.js#L88): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-15 09:16 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +		if (!iframe && !win._sp_) {
Please don't rely on `_sp_`. It's also defined when AdBlock is off (and recovery is enabled on wiki). Please check `ext.wikia.aRecoveryEngine.recovery.helper::isBlocking`

2016-09-15 09:17 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +	var logGroup = 'ext.wikia.adEngine.slotTweaker',
Change group name please

2016-09-15 09:19 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +		if (!!win._sp_.getElementId) {
&& `ext.wikia.aRecoveryEngine.recovery.helper::isBlocking`

2016-09-15 09:21 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +			slotTweaker.tweakRecoveredSlot(iframe.parentNode.parentNode.parentNode.parentNode);
Wrap it with `ext.wikia.aRecoveryEngine.recovery.helper::isBlocking` please.

2016-09-15 09:37 UTC, fraszczakszymon requested changes

2016-09-15 10:01 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L208](https://github.com/Wikia/app/blob/e2a0ad911992783dc14bbafc0f3e794380aa0470/extensions/wikia/AdEngine/js/SlotTweaker.js#L208): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/e2a0ad911992783dc14bbafc0f3e794380aa0470/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L81](https://github.com/Wikia/app/blob/e2a0ad911992783dc14bbafc0f3e794380aa0470/extensions/wikia/AdEngine/js/SlotTweaker.js#L81): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L89](https://github.com/Wikia/app/blob/e2a0ad911992783dc14bbafc0f3e794380aa0470/extensions/wikia/AdEngine/js/SlotTweaker.js#L89): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-15 17:05 UTC, drets commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +			return;
I'd investigate _why_ for IE and Edge we don't need these tweaks and maybe we can help somehow SP to recover the ad on Chrome and Firefox in the same way.

2016-09-15 17:08 UTC, drets commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +define('ext.wikia.adEngine.domElementTweaker', [
We have https://github.com/Wikia/app/blob/dev/extensions/wikia/AdEngine/js/utils/domCalculator.js.
Does it make sense to keep those files in the same dir?

2016-09-16 09:10 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +		}
when none of above is supported then what? Do believe it's worth logging at least?

2016-09-16 09:11 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +		moveStylesToInline: moveStylesToInline
alphabetical order please 🙈

2016-09-16 09:13 UTC, bognix commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +		if (!iframe && !recoveryHelper.isBlocking()) {
`!recoveryHelper.isBlocking` doesn't mean iframe doesn't exist, I guess. Create another if with
` if (!recoveryHelper.isBlocking()) {`
and log the message that describe the issue

2016-09-16 09:16 UTC, bognix commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +		adContainer.className += ' ' + className;
consider using: https://developer.mozilla.org/en/docs/Web/API/Element/classList

2016-09-16 09:16 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +			newClasses = ' ' + element.className.replace(rclass, ' ') + ' ';
consider using https://developer.mozilla.org/en/docs/Web/API/Element/classList although I don't totally understand what is going on there.

2016-09-16 09:17 UTC, bognix commented on extensions/wikia/AdEngine/js/SlotTweaker.js
>  	'wikia.log',
alphabetical order please 🙈

2016-09-16 09:18 UTC, bognix commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +				slotTweaker.tweakRecoveredSlot(iframe.parentNode.parentNode.parentNode.parentNode);
this one doesn't look very robust. Is there a way to make it more dynamic? like get first parent matching particular selector?

2016-09-16 09:18 UTC, bognix commented on skins/oasis/css/core/ads.scss
> +	#HOME_TOP_LEADERBOARD, #TOP_LEADERBOARD, #CORP_TOP_LEADERBOARD, #HUB_TOP_LEADERBOARD, .tmpHeader {
don't call it `tmpHeader` please, is it possible to find a little bit more meaningful name?

2016-09-16 10:22 UTC, v3rth commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +			newClasses = ' ' + element.className.replace(rclass, ' ') + ' ';
I extracted few functions from slotTweaker to this module to separate functionality, soo.... I don't understand it too and I don't even want :D

2016-09-16 11:22 UTC, v3rth commented on skins/oasis/css/core/ads.scss
> +	#HOME_TOP_LEADERBOARD, #TOP_LEADERBOARD, #CORP_TOP_LEADERBOARD, #HUB_TOP_LEADERBOARD, .tmpHeader {
but it's temporaryHeader class :P It's used only for copying styles and it's not used like "typical" class

2016-09-16 11:25 UTC, v3rth commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +				slotTweaker.tweakRecoveredSlot(iframe.parentNode.parentNode.parentNode.parentNode);
https://github.com/Wikia/app/pull/11331/files

2016-09-16 11:29 UTC, v3rth commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +				slotTweaker.tweakRecoveredSlot(iframe.parentNode.parentNode.parentNode.parentNode);
I couldn't find a good way to "find" this specific element in a right way. After recovery elements get random ids and recovery library don't allow to easily find any recovered equivalent (that's why we are using hack's like this https://github.com/Wikia/app/pull/11331/files#diff-eec4847c6159c65ee41d96d4212bd940R134)

2016-09-19 11:29 UTC, bognix commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +				slotTweaker.tweakRecoveredSlot(iframe.parentNode.parentNode.parentNode.parentNode);
understood.

2016-09-19 11:31 UTC, bognix commented on skins/oasis/css/core/ads.scss
> +	#HOME_TOP_LEADERBOARD, #TOP_LEADERBOARD, #CORP_TOP_LEADERBOARD, #HUB_TOP_LEADERBOARD, .tmpHeader {
how about `virtual-slot`? from what I understand you use this class to copy the generated styles for the slot and then you remove this class, am I right?

2016-09-19 11:33 UTC, v3rth commented on skins/oasis/css/core/ads.scss
> +	#HOME_TOP_LEADERBOARD, #TOP_LEADERBOARD, #CORP_TOP_LEADERBOARD, #HUB_TOP_LEADERBOARD, .tmpHeader {
Yes you are. Good idea, thanks!

2016-09-20 10:54 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +		if (typeof win.CSS2Properties !== 'undefined' && computedStyles instanceof win.CSS2Properties) {
I wond if `typeof win.CSS2Properties` needed? If it's not defined then `computedStyles instanceof win.CSS2Properties` would return false either way.

2016-09-20 10:54 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +			for (var i = 0; i < computedStyles.length; i++) {
move var declaration outside for loop scope.

2016-09-20 10:54 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +		for (var i = 0; i < element.childNodes.length; i++) {
move var outside for loop scope

2016-09-20 10:54 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +		} else if (typeof win.CSSStyleDeclaration !== 'undefined' && computedStyles instanceof win.CSSStyleDeclaration) {
same as two comments above

2016-09-20 10:58 UTC, bognix commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +		var fallbackId = win._sp_.getElementId(document.querySelectorAll('div[id="' + slotName + '"] div')[1].id);
I wonder if it's worth checking if `win._sp_.getElementId(document.querySelectorAll('div[id="' + slotName + '"] div')[1]` exists before accessing it's property

2016-09-20 10:58 UTC, bognix commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +		return doc.getElementById(fallbackId).querySelector('div:not(.hidden) > div[id*="_container_"] iframe');
same here, maybe it's worth checking if element exists before calling `querySelector` on it.

2016-09-20 10:59 UTC, bognix commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +		var element = document.getElementById(win._sp_.getElementId(providerContainer.childNodes[0].id));
check if element exists before accessing it's property

2016-09-20 11:00 UTC, bognix commented on extensions/wikia/AdEngine/js/SlotTweaker.js
> +			var recoveredProviderContainer = getRecoveredProviderContainer(providerContainer);
one var per function scope

2016-09-20 12:02 UTC, v3rth commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +		} else if (typeof win.CSSStyleDeclaration !== 'undefined' && computedStyles instanceof win.CSSStyleDeclaration) {
For `computedStyles instanceof win.CSS2Properties` in Chrome:
`Uncaught TypeError: Right-hand side of 'instanceof' is not an objectmoveStylesToInline`

2016-09-20 12:03 UTC, v3rth commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +		if (typeof win.CSS2Properties !== 'undefined' && computedStyles instanceof win.CSS2Properties) {
For `computedStyles instanceof win.CSS2Properties` in Chrome:
`Uncaught TypeError: Right-hand side of 'instanceof' is not an objectmoveStylesToInline`

2016-09-20 14:27 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L217](https://github.com/Wikia/app/blob/bbad63534f96d269e81304921024b25ecede8f1d/extensions/wikia/AdEngine/js/SlotTweaker.js#L217): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/bbad63534f96d269e81304921024b25ecede8f1d/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L81](https://github.com/Wikia/app/blob/bbad63534f96d269e81304921024b25ecede8f1d/extensions/wikia/AdEngine/js/SlotTweaker.js#L81): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L89](https://github.com/Wikia/app/blob/bbad63534f96d269e81304921024b25ecede8f1d/extensions/wikia/AdEngine/js/SlotTweaker.js#L89): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-20 14:42 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L217](https://github.com/Wikia/app/blob/5f77948f441ba79f244916a8940f20738016930c/extensions/wikia/AdEngine/js/SlotTweaker.js#L217): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/5f77948f441ba79f244916a8940f20738016930c/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L81](https://github.com/Wikia/app/blob/5f77948f441ba79f244916a8940f20738016930c/extensions/wikia/AdEngine/js/SlotTweaker.js#L81): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L89](https://github.com/Wikia/app/blob/5f77948f441ba79f244916a8940f20738016930c/extensions/wikia/AdEngine/js/SlotTweaker.js#L89): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-20 14:45 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L217](https://github.com/Wikia/app/blob/306f423019c8bf5ddccbaf999b6ef54bf5fc8cc0/extensions/wikia/AdEngine/js/SlotTweaker.js#L217): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/306f423019c8bf5ddccbaf999b6ef54bf5fc8cc0/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L81](https://github.com/Wikia/app/blob/306f423019c8bf5ddccbaf999b6ef54bf5fc8cc0/extensions/wikia/AdEngine/js/SlotTweaker.js#L81): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L89](https://github.com/Wikia/app/blob/306f423019c8bf5ddccbaf999b6ef54bf5fc8cc0/extensions/wikia/AdEngine/js/SlotTweaker.js#L89): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-21 11:16 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +	function removeClass(element, cls) {
I wonder if it's worth to add unit tests to this method, it doesn't have to be right now, however the `while` loop scares me a little.

2016-09-21 11:18 UTC, bognix commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +			return;
consider adding log here as well.

2016-09-21 11:20 UTC, bognix approved these changes
Minor comments, LGTM

2016-09-23 14:48 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L217](https://github.com/Wikia/app/blob/93f2ae285cc3ae1d100701a9be68481b22c6bc12/extensions/wikia/AdEngine/js/SlotTweaker.js#L217): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/93f2ae285cc3ae1d100701a9be68481b22c6bc12/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L81](https://github.com/Wikia/app/blob/93f2ae285cc3ae1d100701a9be68481b22c6bc12/extensions/wikia/AdEngine/js/SlotTweaker.js#L81): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L89](https://github.com/Wikia/app/blob/93f2ae285cc3ae1d100701a9be68481b22c6bc12/extensions/wikia/AdEngine/js/SlotTweaker.js#L89): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-23 14:50 UTC, v3rth commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +	function removeClass(element, cls) {
Happy path tested

2016-09-27 10:01 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L217](https://github.com/Wikia/app/blob/fd7fc0b01cd208019bffc158da843667bcae59fa/extensions/wikia/AdEngine/js/SlotTweaker.js#L217): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/fd7fc0b01cd208019bffc158da843667bcae59fa/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L81](https://github.com/Wikia/app/blob/fd7fc0b01cd208019bffc158da843667bcae59fa/extensions/wikia/AdEngine/js/SlotTweaker.js#L81): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L89](https://github.com/Wikia/app/blob/fd7fc0b01cd208019bffc158da843667bcae59fa/extensions/wikia/AdEngine/js/SlotTweaker.js#L89): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-27 12:59 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L217](https://github.com/Wikia/app/blob/1712b9f1713fa3fe319506a6b851d5c7fcbc5169/extensions/wikia/AdEngine/js/SlotTweaker.js#L217): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L13](https://github.com/Wikia/app/blob/1712b9f1713fa3fe319506a6b851d5c7fcbc5169/extensions/wikia/AdEngine/js/template/bfaa.js#L13): Function has 10 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L81](https://github.com/Wikia/app/blob/1712b9f1713fa3fe319506a6b851d5c7fcbc5169/extensions/wikia/AdEngine/js/SlotTweaker.js#L81): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L89](https://github.com/Wikia/app/blob/1712b9f1713fa3fe319506a6b851d5c7fcbc5169/extensions/wikia/AdEngine/js/SlotTweaker.js#L89): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-09-27 13:11 UTC, drets commented
Checked the code changes related to resolving conflicts with dev branch − LGTM :+1:

2016-10-03 09:41 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L217](https://github.com/Wikia/app/blob/f3875bc01714113a268b7d590ceda00d49f36789/extensions/wikia/AdEngine/js/SlotTweaker.js#L217): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L13](https://github.com/Wikia/app/blob/f3875bc01714113a268b7d590ceda00d49f36789/extensions/wikia/AdEngine/js/template/bfaa.js#L13): Function has 10 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L81](https://github.com/Wikia/app/blob/f3875bc01714113a268b7d590ceda00d49f36789/extensions/wikia/AdEngine/js/SlotTweaker.js#L81): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L89](https://github.com/Wikia/app/blob/f3875bc01714113a268b7d590ceda00d49f36789/extensions/wikia/AdEngine/js/SlotTweaker.js#L89): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-04 15:03 UTC, drets approved these changes
Minor comments → LGTM :+1:

2016-10-04 15:03 UTC, drets commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +			element.style.cssText = null;
I'd write: `element.style.cssText = '';`
and do we really need to remove attribute and not just clearing `cssText`?

2016-10-04 15:03 UTC, drets commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +				win.addEventListener('resize', function () {
I'd add `throttling` but since it's called only for bfaa → not required.

2016-10-05 16:18 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L218](https://github.com/Wikia/app/blob/812065d18ec06f2d7ac9be7f6583f9579ac27353/extensions/wikia/AdEngine/js/SlotTweaker.js#L218): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/812065d18ec06f2d7ac9be7f6583f9579ac27353/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/812065d18ec06f2d7ac9be7f6583f9579ac27353/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L88](https://github.com/Wikia/app/blob/812065d18ec06f2d7ac9be7f6583f9579ac27353/extensions/wikia/AdEngine/js/SlotTweaker.js#L88): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-05 16:22 UTC, WikiaTech commented
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L218](https://github.com/Wikia/app/blob/3f8ae5038d23f4200739befad4c754cf116e090a/extensions/wikia/AdEngine/js/SlotTweaker.js#L218): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/3f8ae5038d23f4200739befad4c754cf116e090a/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/3f8ae5038d23f4200739befad4c754cf116e090a/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L88](https://github.com/Wikia/app/blob/3f8ae5038d23f4200739befad4c754cf116e090a/extensions/wikia/AdEngine/js/SlotTweaker.js#L88): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-05 16:46 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +		return browser.isIE() || browser.isEdge();
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3ACommentedCode)

2016-10-05 16:46 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/template/bfaa.js
>  ], function (
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Function has 12 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2016-10-05 16:46 UTC, WikiaTech commented
SonarQube analysis reported 5 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L210](https://github.com/Wikia/app/blob/7358352e1b49be39d9ca026f107f260c3804db0e/extensions/wikia/AdEngine/js/SlotTweaker.js#L210): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L72](https://github.com/Wikia/app/blob/7358352e1b49be39d9ca026f107f260c3804db0e/extensions/wikia/AdEngine/js/SlotTweaker.js#L72): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/7358352e1b49be39d9ca026f107f260c3804db0e/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-05 16:46 UTC, WikiaTech commented
SonarQube analysis reported 4 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L210](https://github.com/Wikia/app/blob/7358352e1b49be39d9ca026f107f260c3804db0e/extensions/wikia/AdEngine/js/SlotTweaker.js#L210): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L72](https://github.com/Wikia/app/blob/7358352e1b49be39d9ca026f107f260c3804db0e/extensions/wikia/AdEngine/js/SlotTweaker.js#L72): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/7358352e1b49be39d9ca026f107f260c3804db0e/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-06 07:39 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +			element.className += hiddenElementClass;
The space between new `hidden` class and previous classes is added somewhere in the `removeClass` which is confusing (previously there was hardcoded `_hidden`). I wonder if it's worth to implement `removeClass` method. Duplicates can be handled by using `classList`

2016-10-06 07:41 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/DOMElementTweaker.js
> +	function recursiveRun(action, element) {
It seems not needed

2016-10-06 08:21 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +		win.addEventListener('resize', function () {
adHelper is already here. Please use throtling

2016-10-06 08:25 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/template/bfaa.js
> +			if (recoveryHelper.isBlocking()) {
Can we apply it for oasis handler only?

2016-10-06 08:53 UTC, fraszczakszymon approved these changes

2016-10-06 08:53 UTC, fraszczakszymon commented
LGTM 👍

2016-10-06 09:28 UTC, WikiaTech commented
SonarQube analysis reported 4 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L210](https://github.com/Wikia/app/blob/f19c57fd03b1625bb5bf986e2e39f22af349ec33/extensions/wikia/AdEngine/js/SlotTweaker.js#L210): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L72](https://github.com/Wikia/app/blob/f19c57fd03b1625bb5bf986e2e39f22af349ec33/extensions/wikia/AdEngine/js/SlotTweaker.js#L72): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/f19c57fd03b1625bb5bf986e2e39f22af349ec33/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-10 12:44 UTC, WikiaTech commented
SonarQube analysis reported 4 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L213](https://github.com/Wikia/app/blob/0a611fe8cd8dfe107d9d6f941ebdbd3120cf1064/extensions/wikia/AdEngine/js/SlotTweaker.js#L213): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L72](https://github.com/Wikia/app/blob/0a611fe8cd8dfe107d9d6f941ebdbd3120cf1064/extensions/wikia/AdEngine/js/SlotTweaker.js#L72): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/0a611fe8cd8dfe107d9d6f941ebdbd3120cf1064/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-10 12:52 UTC, WikiaTech commented
SonarQube analysis reported 4 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L213](https://github.com/Wikia/app/blob/efb6c30310ce7bd2cd9b7318ec3b922015a8e386/extensions/wikia/AdEngine/js/SlotTweaker.js#L213): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L72](https://github.com/Wikia/app/blob/efb6c30310ce7bd2cd9b7318ec3b922015a8e386/extensions/wikia/AdEngine/js/SlotTweaker.js#L72): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/efb6c30310ce7bd2cd9b7318ec3b922015a8e386/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-10 14:13 UTC, WikiaTech commented
SonarQube analysis reported 4 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L213](https://github.com/Wikia/app/blob/1ebe29f6f871680d22360781639752e983019bf6/extensions/wikia/AdEngine/js/SlotTweaker.js#L213): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L72](https://github.com/Wikia/app/blob/1ebe29f6f871680d22360781639752e983019bf6/extensions/wikia/AdEngine/js/SlotTweaker.js#L72): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/1ebe29f6f871680d22360781639752e983019bf6/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-10 14:25 UTC, fraszczakszymon commented
LGTM 👍

2016-10-12 09:28 UTC, WikiaTech commented
SonarQube analysis reported 4 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [SlotTweaker.js#L207](https://github.com/Wikia/app/blob/06e8ca342d54e6e452735411ca79a66f92b35b8b/extensions/wikia/AdEngine/js/SlotTweaker.js#L207): "noop" expects "0" arguments, but "1" were provided. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS930)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L72](https://github.com/Wikia/app/blob/06e8ca342d54e6e452735411ca79a66f92b35b8b/extensions/wikia/AdEngine/js/SlotTweaker.js#L72): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [SlotTweaker.js#L80](https://github.com/Wikia/app/blob/06e8ca342d54e6e452735411ca79a66f92b35b8b/extensions/wikia/AdEngine/js/SlotTweaker.js#L80): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1135)

2016-10-12 09:31 UTC, jacekjursza commented
LGTM 💎

2016-10-12 11:19 UTC, merged