WW-316 updated copy of to-do list
Wikia/app pull request #11388
Opened 2016-09-19 23:20 UTC by cormorando

2016-09-19 23:21 UTC, WikiaTech commented
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [CommunityPageSpecialController.class.php#L3](https://github.com/Wikia/app/blob/5fe78f16e98d6e1d724b7eb017a9fd145e8c7774/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L3): Class "CommunityPageSpecialController" has 22 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L42](https://github.com/Wikia/app/blob/5fe78f16e98d6e1d724b7eb017a9fd145e8c7774/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L42): Define a constant instead of duplicating this literal "CommunityPageSpecialController" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L293](https://github.com/Wikia/app/blob/5fe78f16e98d6e1d724b7eb017a9fd145e8c7774/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L293): Define a constant instead of duplicating this literal "timeAgo" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

2016-09-19 23:26 UTC, dianafa commented on extensions/wikia/CommunityPage/styles/components/_todo-list-module.scss
>  		padding: 5px 10px;
the styles of this two classes are almost the same, could we avoid this duplication?

2016-09-19 23:32 UTC, WikiaTech commented
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [CommunityPageSpecialController.class.php#L3](https://github.com/Wikia/app/blob/cef8d82868c6b1624ef4b9d15258247a07927495/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L3): Class "CommunityPageSpecialController" has 22 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L42](https://github.com/Wikia/app/blob/cef8d82868c6b1624ef4b9d15258247a07927495/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L42): Define a constant instead of duplicating this literal "CommunityPageSpecialController" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L293](https://github.com/Wikia/app/blob/cef8d82868c6b1624ef4b9d15258247a07927495/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L293): Define a constant instead of duplicating this literal "timeAgo" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

2016-09-19 23:38 UTC, dianafa commented on extensions/wikia/CommunityPage/CommunityPage.i18n.php
> +	'communitypage-tasks-header-welcome' => 'Herzlich Willkommen $1 Fan!',
This change will break existing functionality and will show `Herzlich Willkommen Fan!`

2016-09-19 23:39 UTC, dianafa commented on extensions/wikia/CommunityPage/CommunityPage.i18n.php
> +	'communitypage-wantedpages-description' => "There are redlinks pointing to these pages, but the pages don't exist! Create the article or make it a redirect to the correct article to help readers nav
hmmm I'm not sure we want this change.

2016-09-19 23:39 UTC, dianafa commented on extensions/wikia/CommunityPage/CommunityPage.i18n.php
> +	'communitypage-recent-activity-header' => 'Recent wiki activity',
I'm not sure we want this change.

2016-09-19 23:39 UTC, dianafa commented on extensions/wikia/CommunityPage/CommunityPage.i18n.php
> +	'communitypage-admin-welcome-message' => 'Share your knowledge by editing pages, uploading images and adding new content.',
hmmm I'm not sure we want this change.

2016-09-19 23:40 UTC, dianafa commented on extensions/wikia/CommunityPage/CommunityPage.i18n.php
> +	'communitypage-admin-welcome-message' => 'Share your knowledge by editing pages, uploading images and adding new content.',
hmmm I'm not sure we want this change.

2016-09-19 23:43 UTC, dianafa reviewed
- changes for non-en languages from `{{SITENAME}}` to `$1` will break existing text
- many of strings is not ready yet

2016-09-20 15:43 UTC, idradm requested changes
To make it safe to merge, I'd request to revert all changes that are not connected with the sprint 10 translations.

2016-09-20 16:03 UTC, WikiaTech commented
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [CommunityPageSpecialController.class.php#L3](https://github.com/Wikia/app/blob/f8baa2dbcbfa525d080821f8c331cb79905cb0a4/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L3): Class "CommunityPageSpecialController" has 22 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L42](https://github.com/Wikia/app/blob/f8baa2dbcbfa525d080821f8c331cb79905cb0a4/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L42): Define a constant instead of duplicating this literal "CommunityPageSpecialController" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L293](https://github.com/Wikia/app/blob/f8baa2dbcbfa525d080821f8c331cb79905cb0a4/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L293): Define a constant instead of duplicating this literal "timeAgo" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

2016-09-20 16:11 UTC, WikiaTech commented
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [CommunityPageSpecialController.class.php#L3](https://github.com/Wikia/app/blob/129a978ea3fca9639141076c3ebf7610a687acab/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L3): Class "CommunityPageSpecialController" has 22 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L42](https://github.com/Wikia/app/blob/129a978ea3fca9639141076c3ebf7610a687acab/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L42): Define a constant instead of duplicating this literal "CommunityPageSpecialController" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L293](https://github.com/Wikia/app/blob/129a978ea3fca9639141076c3ebf7610a687acab/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L293): Define a constant instead of duplicating this literal "timeAgo" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

2016-09-20 16:43 UTC, WikiaTech commented
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [CommunityPageSpecialController.class.php#L3](https://github.com/Wikia/app/blob/b4cd085ff29f49f2aa3751f7ed0cdf56b0e0c2e9/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L3): Class "CommunityPageSpecialController" has 22 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L42](https://github.com/Wikia/app/blob/b4cd085ff29f49f2aa3751f7ed0cdf56b0e0c2e9/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L42): Define a constant instead of duplicating this literal "CommunityPageSpecialController" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommunityPageSpecialController.class.php#L293](https://github.com/Wikia/app/blob/b4cd085ff29f49f2aa3751f7ed0cdf56b0e0c2e9/extensions/wikia/CommunityPage/CommunityPageSpecialController.class.php#L293): Define a constant instead of duplicating this literal "timeAgo" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

2016-09-20 16:51 UTC, dianafa commented on extensions/wikia/CommunityPage/styles/components/_todo-list-module.scss
> +		border-style: solid;
do we need this line? `solid` is below

2016-09-20 16:52 UTC, dianafa commented on extensions/wikia/CommunityPage/styles/components/_todo-list-module.scss
>  		padding: 5px 10px;
some spacing values have 5 or 10px - could we move it to const. ie. `$padding-base: 5px;` or `$padding-small: 5px; $padding-big: 10px;` ?

2016-09-20 16:53 UTC, dianafa commented on extensions/wikia/CommunityPage/CommunityPage.i18n.php
> +	'communitypage-todo-module-description' => 'In diesem Bereich können Admins Seiten vorschlagen, an denen gearbeitet werden sollte und somit neue Autoren bei ihrem Start unterstützen. (Admins: denkt
we don't need this key anymore - it has just been removed in this PR

2016-09-20 16:53 UTC, dianafa commented on extensions/wikia/CommunityPage/CommunityPage.i18n.php
> +	'communitypage-todo-module-description' => 'Esta es un área para que los administradores sugieran páginas que necesitan trabajo para ayudar a los nuevos editores a comenzar. (Administradores - recue
we don't need this key anymore - it has just been removed in this PR

2016-09-20 16:54 UTC, dianafa commented on extensions/wikia/CommunityPage/CommunityPage.i18n.php
> +	'communitypage-todo-module-description' => "Les administrateurs peuvent ici suggérer des pages à améliorer, sur lesquelles les nouveaux contributeurs peuvent commencer. (Administrateurs, n'oubliez p
we don't need this key anymore - it has just been removed in this PR ... (więcej już nie piszę ;P )

2016-09-20 19:39 UTC, closed without merging