WW-294: Use fandom logo in Community Page entry point
Wikia/app pull request #11406
Opened 2016-09-20 22:43 UTC by lukaszkonieczny

@Wikia/west-wing

2016-09-20 22:47 UTC, dianafa commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
>  		height: 30px;
would it make sense to move border-radius, height & width to a `$entry-point-logo-size: 30px;` ?

2016-09-20 23:01 UTC, idradm commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
> +$logo-url: '/extensions/wikia/DesignSystem/bower_components/design-system/dist/svg/wds-company-logo-fandom-heart.svg';
Please make sure this is desired way of using design system svgs.

2016-09-20 23:01 UTC, idradm reviewed
It's fine as long we want to load svgs that way.

2016-09-20 23:14 UTC, idradm commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
> +$content-spacing-large: 40px;
Please, do not override existing variables, it might cause errors on auto refactoring and is misleading in general. Use new ones where needed.

2016-09-20 23:15 UTC, idradm requested changes

2016-09-21 00:08 UTC, idradm commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
> +	margin-top: $content-spacing-regular;
content-spacing-regular is 18px. Do we want to change those sizes?

2016-09-21 00:10 UTC, idradm commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
> +		padding-top: $content-spacing-regular;
`content-spacing-regular` is `18px`. Do we want to change those sizes?

2016-09-21 18:01 UTC, lukaszkonieczny commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
>  		height: 30px;
:+1:

2016-09-21 18:01 UTC, lukaszkonieczny commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
> +$logo-url: '/extensions/wikia/DesignSystem/bower_components/design-system/dist/svg/wds-company-logo-fandom-heart.svg';
I didn't find different way

2016-09-21 18:03 UTC, lukaszkonieczny commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
> +	margin-top: $content-spacing-regular;
I compared how it look after this difference is minor, so I decided to use existing spacing value

2016-09-21 18:04 UTC, lukaszkonieczny commented on extensions/wikia/CommunityPage/styles/entrypoint/EntryPoint.scss
> +		padding-top: $content-spacing-regular;
I compared how it look after this difference is minor, so I decided to use existing spacing value

2016-09-21 18:11 UTC, idradm approved these changes

2016-09-21 21:49 UTC, sebastianmarzjan approved these changes

2016-09-21 21:57 UTC, dianafa commented
LGTM

2016-09-22 16:01 UTC, merged