ADEN-4037 Remove used prebid.js bids
Wikia/app pull request #11581
Opened 2016-10-07 10:02 UTC by fraszczakszymon

and implement our custom adapter which can be enabled by `?wikia_adapter=<price>`

2016-10-07 10:02 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/lookup/prebid/prebid.js
> +], function (adContext, adaptersTracker, appnexus, index, wikiaAdapter, helper, factory, doc, win) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Function has 9 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2016-10-07 10:02 UTC, WikiaTech commented
SonarQube analysis reported 1 issue
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major

Watch the comments in this conversation to review them.

2016-10-07 15:43 UTC, v3rth requested changes

2016-10-07 15:43 UTC, v3rth commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +], function (doc, win, QueryString) {
alphabetical order, please

2016-10-07 15:43 UTC, v3rth commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +		return parseInt(price, 10) / 100;
Price in QueryString can be only decimal? Because it is always rounded to decimal, so 5.3 will not pass

2016-10-07 15:43 UTC, v3rth commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +	function getCreative(price, size) {
maybe extract it to some "creative builder" this is probably should not be a responsibility of this module

2016-10-07 15:43 UTC, v3rth commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +			var bidResponse = win.pbjs.createBid(1),
IMO using globals isn't clean, maybe it's a good idea to 'close' it behind some module?

2016-10-10 07:52 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +		return parseInt(price, 10) / 100;
I'd say it's fine, `?wikia_adapter=532` will force $5.32 price

2016-10-10 07:58 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +	function getCreative(price, size) {
In general I agree. But it seems this module will be used for tests purposes for now and I wouldn't like to spread it to more modules. Is it ok?

2016-10-10 08:41 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +			var bidResponse = win.pbjs.createBid(1),
Addressed

2016-10-10 08:41 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +], function (doc, win, QueryString) {
Addressed

2016-10-10 09:29 UTC, v3rth commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +	function getCreative(price, size) {
:+1:

2016-10-10 09:29 UTC, v3rth commented on extensions/wikia/AdEngine/js/lookup/prebid/adapters/wikia.js
> +		return parseInt(price, 10) / 100;
:+1:

2016-10-10 09:29 UTC, v3rth approved these changes

2016-10-10 09:29 UTC, v3rth commented
LGTM

2016-10-12 11:07 UTC, bognix commented
tested, merging.

2016-10-12 11:07 UTC, merged