SOC-3211 Mark deleted and reported posts in discussions tag
Wikia/app pull request #11642
Opened 2016-10-17 03:28 UTC by perjg

@Grunny @garthwebb

2016-10-17 03:29 UTC, WikiaTech commented on extensions/wikia/EmbeddableDiscussions/scripts/templates.mustache.js
>  /* jshint ignore:start */ define( 'embeddablediscussions.templates.mustache', [], function() { 'use strict'; return {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Reformat the code to have only one statement per line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AOneStatementPerLine)

2016-10-17 03:29 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/6f342ba6d9f8a9a90dfbbd1b66be34dba609c743/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L69](https://github.com/Wikia/app/blob/6f342ba6d9f8a9a90dfbbd1b66be34dba609c743/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L69): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AForIn)

2016-10-19 09:35 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/c05d878019431b81441c7e43c815d2269162353a/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L69](https://github.com/Wikia/app/blob/c05d878019431b81441c7e43c815d2269162353a/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L69): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AForIn)

2016-10-19 13:55 UTC, Grunny requested changes

2016-10-19 13:55 UTC, Grunny commented on extensions/wikia/EmbeddableDiscussions/styles/EmbeddableDiscussions.scss
> +$discussion-deleted-actions-opacity: 0.5;
Remove the leading 0 per conventions.

2016-10-19 13:55 UTC, Grunny commented on extensions/wikia/EmbeddableDiscussions/styles/EmbeddableDiscussions.scss
> +		&.is-deleted {
This nested rule should be below the `font-size` property per conventions.

2016-10-19 13:55 UTC, Grunny commented on extensions/wikia/EmbeddableDiscussions/styles/EmbeddableDiscussions.scss
> +		&.is-deleted {
This nested rule should be below the properties below per conventions.

2016-10-19 13:55 UTC, Grunny commented on extensions/wikia/EmbeddableDiscussions/styles/EmbeddableDiscussions.scss
> +				content: "";
Should use single quotes per conventions.

2016-10-19 13:55 UTC, Grunny commented on extensions/wikia/EmbeddableDiscussions/styles/EmbeddableDiscussions.scss
> +		position: relative;
These properties should be above the nested rules above.

2016-10-19 13:55 UTC, Grunny commented on extensions/wikia/EmbeddableDiscussions/styles/EmbeddableDiscussions.scss
> +		&.is-deleted {
This nested rule should be below the properties below.

2016-10-20 02:47 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/597b7d3f856315e67ec00acfdcfc8682fd74a43d/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L69](https://github.com/Wikia/app/blob/597b7d3f856315e67ec00acfdcfc8682fd74a43d/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L69): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AForIn)

2016-10-20 02:47 UTC, perjg commented
@Grunny I've fixed the style guide issues in the .scss file.

2016-10-25 08:27 UTC, Grunny approved these changes
LGTM.

2016-11-02 03:00 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/a46bd74c6be249f39c6bf685f1835ed0b33e5b7a/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/a46bd74c6be249f39c6bf685f1835ed0b33e5b7a/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-02 03:03 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/2dca5dd61c505e03334b163d4b991ae7040f0b51/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/2dca5dd61c505e03334b163d4b991ae7040f0b51/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-02 03:12 UTC, merged