ADEN-4124 Video in BFAA
Wikia/app pull request #11660
Opened 2016-10-18 15:13 UTC by drets

• expand video on click
• hide video after playing

2016-10-18 15:13 UTC, WikiaTech commented
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L16](https://github.com/Wikia/app/blob/68af69e274baa86035b02921216ce091195defb7/extensions/wikia/AdEngine/js/template/bfaa.js#L16): Function has 13 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2016-10-19 10:27 UTC, WikiaTech commented
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [bfaa.js#L14](https://github.com/Wikia/app/blob/235a72fe82ae381990654d1e32e918aed89fb777/extensions/wikia/AdEngine/js/template/bfaa.js#L14): Function has 11 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2016-10-19 12:34 UTC, bognix commented
I am wondering if you considered adding another template instead of re-using the BFAA template. I understand why you choose re-usage and I'm asking just out of the curiosity.

My second question is, have you considered breaking BFAA template into two: bfaa_desktop and bfaa_mobile. Logic for loading BFAA on those two platforms is totally different and we kind of do this by having mobileHandler and desktopHandler. How about going one step further and having two files `bfaaOasis' and `bfaaMercury`, then depending on the platform user is on we require one or the other inside `bfaa.js` file

2016-10-19 12:39 UTC, bognix requested changes
Please address my third question/comment in the comment to PR

2016-10-20 10:44 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/template/bfaaDesktop.js
> +], function (
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Function has 9 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2016-10-20 10:44 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/template/bfaaMobile.js
> +], function (
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2016-10-20 10:44 UTC, WikiaTech commented
SonarQube analysis reported 2 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major

Watch the comments in this conversation to review them.

2016-10-20 13:49 UTC, bognix commented on skins/oasis/css/core/ads.scss
> +	video {
do you think it's safe to style all videos inside top leaderboard?

2016-10-20 14:40 UTC, bognix approved these changes

2016-10-24 11:42 UTC, merged