SUS-1121: update Oasis i18n strings with translations from Crowdin
Wikia/app pull request #11743
Opened 2016-10-28 14:26 UTC by macbre

https://wikia-inc.atlassian.net/browse/SUS-1121

`crowdin download` + a script that ignores translations with "Wikia" phrase

@mixth-sense / @TK-999

2016-10-29 21:05 UTC, mszabo-wikia requested changes
Let's fix the outdated message :)

2016-10-29 21:05 UTC, TK-999 commented on extensions/wikia/Oasis/Oasis.i18n.php
> +	'oasis-comments-anonymous-prompt' => '匿名ユーザー<br /> <a href="#" class="ajaxLogin">ログインしますか？</a>',
This will break because this message is passed to parser - version in app repo is correct here. AjaxLogin extension is long gone anyways :)

2016-10-29 21:05 UTC, TK-999 commented on extensions/wikia/Oasis/Oasis.i18n.php
> +	'oasis-comments-anonymous-prompt' => 'Użytkownik anonimowy<br /> <a href="#" class="ajaxLogin">Chcesz się zalogować?</a>',
same for all language variants

2016-10-29 21:05 UTC, TK-999 commented on extensions/wikia/Oasis/Oasis.i18n.php
> +	'oasis-comments-anonymous-prompt' => '匿名使用者<br /> <a href="#" class="ajaxLogin">進行登錄？</a>',
It seems in this case version in app repo was never updated - it should use wikitext to link to login page

2016-10-30 14:37 UTC, macbre commented on extensions/wikia/Oasis/Oasis.i18n.php
> +	'oasis-comments-anonymous-prompt' => '匿名使用者<br /> <a href="#" class="ajaxLogin">進行登錄？</a>',
Thanks, @TK-999 - I'll skip `oasis-comments-anonymous-prompt` messages in this PR.

2016-11-02 08:46 UTC, macbre commented
@TK-999, `oasis-comments-anonymous-prompt` string skipped

2016-11-02 09:43 UTC, mszabo-wikia approved these changes
![LGTM](https://media.giphy.com/media/xT9DPPniA6EjHhmLqU/giphy.gif)

2016-11-02 10:03 UTC, merged