SUS-794 added validation for phalanx filters form
Wikia/app pull request #11759
Opened 2016-11-02 14:07 UTC by cormorando

2016-11-02 14:07 UTC, WikiaTech commented on extensions/wikia/PhalanxII/js/SpecialPhalanx.js
>  		on('click', '#enterbulk', function(ev) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove the unused function parameter "ev". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2016-11-02 14:07 UTC, WikiaTech commented on extensions/wikia/PhalanxII/js/SpecialPhalanx.js
>  		on('click', '#entersingle', function(ev) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove the unused function parameter "ev". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2016-11-02 14:07 UTC, WikiaTech commented on extensions/wikia/PhalanxII/js/SpecialPhalanx.js
> +		on('change', '#wpPhalanxExpire', function(ev) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove the unused function parameter "ev". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2016-11-02 14:07 UTC, WikiaTech commented on extensions/wikia/PhalanxII/js/SpecialPhalanx.js
>  		on('click', '#validate', function(ev) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove the unused function parameter "ev". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2016-11-02 14:07 UTC, WikiaTech commented
SonarQube analysis reported 12 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 6 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 5 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [PhalanxSpecialController.class.php#L295](https://github.com/Wikia/app/blob/bf0bfa79105e0f237a67264ed3da80151e53a7bc/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L295): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [SpecialPhalanx.js#L12](https://github.com/Wikia/app/blob/bf0bfa79105e0f237a67264ed3da80151e53a7bc/extensions/wikia/PhalanxII/js/SpecialPhalanx.js#L12): Remove the unused function parameter "ev". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L13](https://github.com/Wikia/app/blob/bf0bfa79105e0f237a67264ed3da80151e53a7bc/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L13): Define a constant instead of duplicating this literal "Phalanx" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L34](https://github.com/Wikia/app/blob/bf0bfa79105e0f237a67264ed3da80151e53a7bc/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L34): Replace this "switch" statement with "if" statements to increase readability. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1301)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L145](https://github.com/Wikia/app/blob/bf0bfa79105e0f237a67264ed3da80151e53a7bc/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L145): Define a constant instead of duplicating this literal "checkBlocker" 5 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L308](https://github.com/Wikia/app/blob/bf0bfa79105e0f237a67264ed3da80151e53a7bc/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L308): Define a constant instead of duplicating this literal "error" 4 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L315](https://github.com/Wikia/app/blob/bf0bfa79105e0f237a67264ed3da80151e53a7bc/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L315): Define a constant instead of duplicating this literal "token" 4 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [PhalanxSpecialController.class.php#L203](https://github.com/Wikia/app/blob/bf0bfa79105e0f237a67264ed3da80151e53a7bc/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L203): Move this trailing comment on the previous empty line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

2016-11-02 21:05 UTC, mszabo-wikia requested changes

2016-11-02 21:05 UTC, TK-999 commented on extensions/wikia/PhalanxII/js/SpecialPhalanx.js
> +		$("span[id*='formValidateMessage-filter']").hide();
What do you think about using BannerNotification for validation notices?

2016-11-02 21:10 UTC, cormorando commented on extensions/wikia/PhalanxII/js/SpecialPhalanx.js
> +		$("span[id*='formValidateMessage-filter']").hide();
This is front end validation, regex is done the same way in this form

2016-11-03 12:00 UTC, mszabo-wikia approved these changes

2016-11-07 13:09 UTC, WikiaTech commented
SonarQube analysis reported 12 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 6 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 5 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [PhalanxSpecialController.class.php#L295](https://github.com/Wikia/app/blob/4c634b6ff2b7dd83516cbe7ded47aea97c5d7811/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L295): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [SpecialPhalanx.js#L12](https://github.com/Wikia/app/blob/4c634b6ff2b7dd83516cbe7ded47aea97c5d7811/extensions/wikia/PhalanxII/js/SpecialPhalanx.js#L12): Remove the unused function parameter "ev". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L13](https://github.com/Wikia/app/blob/4c634b6ff2b7dd83516cbe7ded47aea97c5d7811/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L13): Define a constant instead of duplicating this literal "Phalanx" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L34](https://github.com/Wikia/app/blob/4c634b6ff2b7dd83516cbe7ded47aea97c5d7811/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L34): Replace this "switch" statement with "if" statements to increase readability. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1301)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L145](https://github.com/Wikia/app/blob/4c634b6ff2b7dd83516cbe7ded47aea97c5d7811/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L145): Define a constant instead of duplicating this literal "checkBlocker" 5 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L308](https://github.com/Wikia/app/blob/4c634b6ff2b7dd83516cbe7ded47aea97c5d7811/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L308): Define a constant instead of duplicating this literal "error" 4 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [PhalanxSpecialController.class.php#L315](https://github.com/Wikia/app/blob/4c634b6ff2b7dd83516cbe7ded47aea97c5d7811/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L315): Define a constant instead of duplicating this literal "token" 4 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [PhalanxSpecialController.class.php#L203](https://github.com/Wikia/app/blob/4c634b6ff2b7dd83516cbe7ded47aea97c5d7811/extensions/wikia/PhalanxII/PhalanxSpecialController.class.php#L203): Move this trailing comment on the previous empty line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

2016-11-09 16:56 UTC, merged