PLATFORM-2567 repulling translations
Wikia/app pull request #11767
Opened 2016-11-03 12:22 UTC by pgrabowski-wikia

https://wikia-inc.atlassian.net/browse/PLATFORM-2567

2016-11-04 14:30 UTC, Grunny requested changes

2016-11-04 14:30 UTC, Grunny commented on extensions/wikia/Email/i18n/Welcome.i18n.php
> +	'emailext-welcome-subject' => 'Welcome to Wikia, $1!',
Seems to be restoring pre-rebrand messages? Were the source strings up to date?

2016-11-07 09:01 UTC, pgrabowski-wikia commented on extensions/wikia/Email/i18n/Welcome.i18n.php
> +	'emailext-welcome-subject' => 'Welcome to Wikia, $1!',
It seems this is not used anywhere:
<img width="888" alt="screenshot 2016-11-07 10 01 02" src="https://cloud.githubusercontent.com/assets/20514390/20051790/1b532342-a4d1-11e6-8562-e2535b7bbca5.png">

2016-11-07 09:20 UTC, Grunny commented on extensions/wikia/Email/i18n/Welcome.i18n.php
> +	'emailext-welcome-subject' => 'Welcome to Wikia, $1!',
It's used here: https://github.com/Wikia/app/blob/dev/extensions/wikia/Email/Controller/WelcomeController.class.php#L19 and other messages such as the summary are affected as well.

2017-09-20 14:12 UTC, closed without merging