XW-2293 | Productize `Add New Page` button
Wikia/app pull request #11818
Opened 2016-11-08 15:52 UTC by rogatty

https://wikia-inc.atlassian.net/browse/XW-2293

Clean up after XW-2226.

@Wikia/x-wing

2016-11-08 15:52 UTC, WikiaTech commented
SonarQube analysis reported 8 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L73](https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L73): Function has a complexity of 15 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L96](https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L96): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L232](https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L232): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L586): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L606](https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L606): Function has a complexity of 12 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L648](https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L648): Function has a complexity of 18 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L663](https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L663): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L586): Replace this "switch" statement with "if" statements to increase readability. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1301)

2016-11-08 16:22 UTC, WikiaTech commented
SonarQube analysis reported 8 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L73](https://github.com/Wikia/app/blob/1c2b850ffcf3508243ec07f2c06f48cfd43bf693/skins/oasis/js/Tracking.js#L73): Function has a complexity of 15 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L96](https://github.com/Wikia/app/blob/1c2b850ffcf3508243ec07f2c06f48cfd43bf693/skins/oasis/js/Tracking.js#L96): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L232](https://github.com/Wikia/app/blob/1c2b850ffcf3508243ec07f2c06f48cfd43bf693/skins/oasis/js/Tracking.js#L232): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/1c2b850ffcf3508243ec07f2c06f48cfd43bf693/skins/oasis/js/Tracking.js#L586): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L606](https://github.com/Wikia/app/blob/1c2b850ffcf3508243ec07f2c06f48cfd43bf693/skins/oasis/js/Tracking.js#L606): Function has a complexity of 12 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L648](https://github.com/Wikia/app/blob/1c2b850ffcf3508243ec07f2c06f48cfd43bf693/skins/oasis/js/Tracking.js#L648): Function has a complexity of 18 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L663](https://github.com/Wikia/app/blob/1c2b850ffcf3508243ec07f2c06f48cfd43bf693/skins/oasis/js/Tracking.js#L663): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/1c2b850ffcf3508243ec07f2c06f48cfd43bf693/skins/oasis/js/Tracking.js#L586): Replace this "switch" statement with "if" statements to increase readability. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1301)

2016-11-09 09:21 UTC, kvas-damian commented on skins/oasis/css/core/PageHeader.scss
> +		clear: both;
:abc:

2016-11-09 09:26 UTC, kvas-damian commented on skins/oasis/modules/templates/PageHeader_Index.php
> +					<a href="/wiki/Special:CreatePage?flow=create-page-contribute-button" class="wikia-button createpage" data-id="createpage">
Hardcoded url was meant to be a temporary solution for ABTest. For production ready solution please use `SpecialPage::getTitleFor( $specialPageName )->getLocalURL()`.

Bonus points for reusing existing logic in: https://github.com/Wikia/app/blob/55a5452c79a44f0b49e6886f0352fba87745ecaf/skins/oasis/modules/ContributeMenuController.class.php#L19-L19 which already includes flow tracking parameters.

2016-11-09 09:27 UTC, kvas-damian requested changes
Please address feedback

2016-11-09 11:14 UTC, WikiaTech commented
SonarQube analysis reported 34 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 21 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 7 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 6 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L32](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L32): Remove the unused function parameters "$out, $skin". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): Remove the unused function parameters "$page, $user, $text, $summary, $minoredit, $watchThis, $sectionAnchor, $flags". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): This function has 9 parameters, which is greater than the 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L112](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L112): Remove the unused function parameter "$header". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L73](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/skins/oasis/js/Tracking.js#L73): Function has a complexity of 15 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L96](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/skins/oasis/js/Tracking.js#L96): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L232](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/skins/oasis/js/Tracking.js#L232): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/skins/oasis/js/Tracking.js#L586): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L606](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/skins/oasis/js/Tracking.js#L606): Function has a complexity of 12 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L648](https://github.com/Wikia/app/blob/fcd8720cc89ad90c9e19f52487d3fd775f6c05fa/skins/oasis/js/Tracking.js#L648): Function has a complexity of 18 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2016-11-09 11:20 UTC, kvas-damian commented on skins/oasis/modules/PageHeaderController.class.php
> +	private function getPageExists() {
what do you think about renaming to `pageExists()`?

2016-11-09 11:20 UTC, rogatty commented on skins/oasis/modules/PageHeaderController.class.php
> +	private function getPageExists() {
`doesPageExist()`?

2016-11-09 11:22 UTC, kvas-damian commented on skins/oasis/modules/PageHeaderController.class.php
> +			wfRunHooks( 'PageHeaderAfterAddNewPageButton', [ &$href ]);
spaces ;)

2016-11-09 11:24 UTC, kvas-damian approved these changes

2016-11-09 11:24 UTC, kvas-damian commented on skins/oasis/modules/PageHeaderController.class.php
> +	private function getPageExists() {
http://stackoverflow.com/questions/1566745/boolean-method-naming-readability

2016-11-09 11:28 UTC, weronika commented on skins/oasis/modules/PageHeaderController.class.php
> +	private function getPageExists() {
`pageExists()` is nicer to read in an `if` :)

2016-11-09 11:32 UTC, weronika commented on skins/oasis/js/Tracking.js
> +	$wikiHeader.find('.buttons .contribute').add('#WikiaPageHeader').on('mousedown', 'a', function (event) {
are you sure it won't catch too many links now?

2016-11-09 11:32 UTC, WikiaTech commented on skins/oasis/modules/PageHeaderController.class.php
>  	static function onArticleSaveComplete( &$article, &$user, $text, $summary,
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) This function has 11 parameters, which is greater than the 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)

2016-11-09 11:32 UTC, WikiaTech commented
SonarQube analysis reported 34 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 21 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 7 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 6 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L32](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L32): Remove the unused function parameters "$out, $skin". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): Remove the unused function parameters "$page, $user, $text, $summary, $minoredit, $watchThis, $sectionAnchor, $flags". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): This function has 9 parameters, which is greater than the 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L112](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L112): Remove the unused function parameter "$header". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L73](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/skins/oasis/js/Tracking.js#L73): Function has a complexity of 15 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L96](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/skins/oasis/js/Tracking.js#L96): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L232](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/skins/oasis/js/Tracking.js#L232): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/skins/oasis/js/Tracking.js#L586): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L606](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/skins/oasis/js/Tracking.js#L606): Function has a complexity of 12 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L648](https://github.com/Wikia/app/blob/b5242adf9c3be0645ae9ae5a9384ac0350db7cf9/skins/oasis/js/Tracking.js#L648): Function has a complexity of 18 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2016-11-09 11:33 UTC, rogatty commented on skins/oasis/js/Tracking.js
> +	$wikiHeader.find('.buttons .contribute').add('#WikiaPageHeader').on('mousedown', 'a', function (event) {
In the callback we filter the links using `data-id` attribute. Also, this is the same selector as in https://github.com/Wikia/app/blob/3ccf876cbf2cce90734ab37d23742a5ede58ccff/skins/oasis/js/Tracking.js#L73

2016-11-10 11:55 UTC, WikiaTech commented on skins/oasis/modules/PageHeaderController.class.php
>  	static function onArticleSaveComplete( &$article, &$user, $text, $summary,
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) This function has 11 parameters, which is greater than the 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)

2016-11-10 11:55 UTC, WikiaTech commented
SonarQube analysis reported 34 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 21 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 7 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 6 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L32](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L32): Remove the unused function parameters "$out, $skin". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): Remove the unused function parameters "$page, $user, $text, $summary, $minoredit, $watchThis, $sectionAnchor, $flags". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): This function has 9 parameters, which is greater than the 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L112](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L112): Remove the unused function parameter "$header". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L73](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/skins/oasis/js/Tracking.js#L73): Function has a complexity of 15 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L96](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/skins/oasis/js/Tracking.js#L96): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L232](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/skins/oasis/js/Tracking.js#L232): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/skins/oasis/js/Tracking.js#L586): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L606](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/skins/oasis/js/Tracking.js#L606): Function has a complexity of 12 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L648](https://github.com/Wikia/app/blob/90a0c96de15ce25386df64d4a7e4e0e46dc0e79e/skins/oasis/js/Tracking.js#L648): Function has a complexity of 18 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2016-11-10 21:19 UTC, WikiaTech commented
SonarQube analysis reported 34 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 21 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 7 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 6 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L32](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L32): Remove the unused function parameters "$out, $skin". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): Remove the unused function parameters "$page, $user, $text, $summary, $minoredit, $watchThis, $sectionAnchor, $flags". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): This function has 9 parameters, which is greater than the 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L112](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L112): Remove the unused function parameter "$header". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L73](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/skins/oasis/js/Tracking.js#L73): Function has a complexity of 15 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L96](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/skins/oasis/js/Tracking.js#L96): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L232](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/skins/oasis/js/Tracking.js#L232): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/skins/oasis/js/Tracking.js#L586): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L606](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/skins/oasis/js/Tracking.js#L606): Function has a complexity of 12 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L648](https://github.com/Wikia/app/blob/4fb2e0eb8436827809aacb05d1194cbbc9149c76/skins/oasis/js/Tracking.js#L648): Function has a complexity of 18 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2016-11-10 22:05 UTC, WikiaTech commented
SonarQube analysis reported 34 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 21 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 7 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 6 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L32](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L32): Remove the unused function parameters "$out, $skin". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): Remove the unused function parameters "$page, $user, $text, $summary, $minoredit, $watchThis, $sectionAnchor, $flags". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L50](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L50): This function has 9 parameters, which is greater than the 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [FlowTracking.hooks.php#L112](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/extensions/wikia/FlowTracking/FlowTracking.hooks.php#L112): Remove the unused function parameter "$header". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L73](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/skins/oasis/js/Tracking.js#L73): Function has a complexity of 15 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L96](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/skins/oasis/js/Tracking.js#L96): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L232](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/skins/oasis/js/Tracking.js#L232): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L586](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/skins/oasis/js/Tracking.js#L586): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L606](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/skins/oasis/js/Tracking.js#L606): Function has a complexity of 12 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Tracking.js#L648](https://github.com/Wikia/app/blob/87769e74244ba812ea7f9c685ad271272d6f122f/skins/oasis/js/Tracking.js#L648): Function has a complexity of 18 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2016-11-14 17:17 UTC, merged