SOC-3224, SOC-3225 | discussion widget color, and actions bar changes
Wikia/app pull request #11870
Opened 2016-11-15 11:36 UTC by latata

https://wikia-inc.atlassian.net/browse/SOC-3224
https://wikia-inc.atlassian.net/browse/SOC-3225

Tickets were strongly connected so I made single PR for both.

2016-11-15 11:37 UTC, WikiaTech commented on extensions/wikia/EmbeddableDiscussions/scripts/templates.mustache.js
>  /* jshint ignore:start */ define( 'embeddablediscussions.templates.mustache', [], function() { 'use strict'; return {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Reformat the code to have only one statement per line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AOneStatementPerLine)

2016-11-15 11:37 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/e53f4e32ba238b1e846bbec22a1db5a18863d6b0/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/e53f4e32ba238b1e846bbec22a1db5a18863d6b0/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-15 11:43 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/16ad48a7fb8b7fc874893020513411d5542887f2/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/16ad48a7fb8b7fc874893020513411d5542887f2/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-15 15:56 UTC, bkoval requested changes

2016-11-15 15:56 UTC, bkoval commented on extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js
> +			var imagesDir = '/extensions/wikia/EmbeddableDiscussions/images/';
In JS we try to hold on to the "one var per method" rule.

2016-11-15 15:56 UTC, bkoval commented on extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js
> +		$elem.find('img.svg').each(function(){
function () { (different spacing)

2016-11-15 15:56 UTC, bkoval commented on extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js
> +	 * Replace img elements with svg element, it give us possibility to set fill color of svg.
*gives

2016-11-15 15:56 UTC, bkoval commented on extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js
> +			jQuery.get(imgURL, function(data) {
Why not $ instead of jQuery? :)

2016-11-15 15:56 UTC, bkoval commented on extensions/wikia/EmbeddableDiscussions/styles/EmbeddableDiscussions.scss
> +@if luminance($color-text) > 0.3 {
👍

2016-11-15 15:56 UTC, bkoval commented on extensions/wikia/EmbeddableDiscussions/styles/EmbeddableDiscussions.scss
> +		background-color: mix($overlay-color, $color-page, $overlay-small-value);
🚓

2016-11-15 15:56 UTC, bkoval commented on extensions/wikia/EmbeddableDiscussions/templates/DiscussionThreads.mustache
> +                <li class="embeddable-action-gap"></li>
Is something wrong with indentation here? Or is it just github going wild? Also - why do we need it? Seems like this one has no content in it :)

2016-11-15 15:56 UTC, bkoval commented on skins/shared/functions.scss
> +}
Needs new line below (at the end of file)

2016-11-15 18:03 UTC, mleczey commented on extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js
> +			jQuery.get(imgURL, function(data) {
Maybe you could extract method here to make this more readable?

2016-11-15 18:03 UTC, mleczey commented on extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js
> +				$svg = $svg.removeAttr('xmlns:a');
Maybe you could extract method here instead of adding comment?

2016-11-15 21:29 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/c9928c31f0028763d5e6a6310887c8e9c6cd51d5/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/c9928c31f0028763d5e6a6310887c8e9c6cd51d5/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-16 14:34 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/b5324008197fa7c7309895743e28cc464c58ed9e/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/b5324008197fa7c7309895743e28cc464c58ed9e/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-16 15:38 UTC, bkoval approved these changes

2016-11-16 15:53 UTC, mleczey approved these changes

2016-11-21 11:47 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/b4d1ad31709769a95c269abf0572e72ba8f21b38/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/b4d1ad31709769a95c269abf0572e72ba8f21b38/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-21 17:40 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/d28b1fb1921c488cf0cdb6a0393dd15919f77585/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/d28b1fb1921c488cf0cdb6a0393dd15919f77585/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-21 17:58 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 2 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L10](https://github.com/Wikia/app/blob/11a3e37a5cb48c4a33ac26a17c1d21a594847bd8/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L10): Function has 8 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ext.embeddableDiscussions.js#L70](https://github.com/Wikia/app/blob/11a3e37a5cb48c4a33ac26a17c1d21a594847bd8/extensions/wikia/EmbeddableDiscussions/scripts/ext.embeddableDiscussions.js#L70): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-11-23 15:29 UTC, merged