WW-520 fixed margins
Wikia/app pull request #11897
Opened 2016-11-16 14:53 UTC by cormorando

2016-11-16 17:20 UTC, cormorando commented on extensions/wikia/CreateNewWiki/css/CreateNewWiki.scss
> +				margin-top: 0;
This line is important cause there's no `!important` any more

2016-11-17 08:04 UTC, lukaszkonieczny requested changes

2016-11-17 08:04 UTC, lukaszkonieczny commented on extensions/wikia/CreateNewWiki/templates/CreateNewWiki_Index.php
> -						<label>
Removing this label made text near checkbbox not clickable

2016-11-17 08:30 UTC, idradm commented on extensions/wikia/CreateNewWiki/css/CreateNewWiki.scss
> +		.wds-dropdown {
Could you rewrite this whole block to make it less nested?

2016-11-17 08:41 UTC, idradm requested changes
I've run linter on the file, could we fix whatever is possible at the current stage?

```
CreateNewWiki.scss:10:9 [W] ImportPath: Imported partial `extensions/wikia/DesignSystem/bower_components/design-system/dist/scss/wds-variables/index.scss` should be written as `extensions/wikia/DesignSystem/bower_components/design-system/dist/scss/wds-variables/index`
CreateNewWiki.scss:11:9 [W] ImportPath: Imported partial `extensions/wikia/DesignSystem/bower_components/design-system/dist/scss/wds-components/_buttons.scss` should be written as `extensions/wikia/DesignSystem/bower_components/design-system/dist/scss/wds-components/buttons`
CreateNewWiki.scss:40:25 [W] ColorVariable: Color literals like `rgba(26, 26, 26, 0.2)` should only be used in variable declarations; they should be referred to via variable everywhere else.
CreateNewWiki.scss:50:1 [W] IdSelector: Avoid using id selectors
CreateNewWiki.scss:52:2 [W] PropertySortOrder: Properties should be ordered background, border, box-sizing, color, font-family, font-size, line-height, margin, padding, position, width
CreateNewWiki.scss:72:3 [W] BorderZero: `border: 0` is preferred over `border: none`
CreateNewWiki.scss:75:11 [W] Shorthand: Shorthand form for property `margin` should be written more concisely as `0 0 $content-spacing-regular` instead of `0 0 $content-spacing-regular 0`
CreateNewWiki.scss:95:1 [W] QualifyingElement: Avoid qualifying attribute selectors with an element.
CreateNewWiki.scss:96:4 [W] PlaceholderInExtend: Prefer using placeholder selectors (e.g. %some-placeholder) with @extend
CreateNewWiki.scss:97:4 [W] PlaceholderInExtend: Prefer using placeholder selectors (e.g. %some-placeholder) with @extend
CreateNewWiki.scss:114:1 [W] QualifyingElement: Avoid qualifying attribute selectors with an element.
CreateNewWiki.scss:116:3 [W] BorderZero: `border: 0` is preferred over `border: none`
CreateNewWiki.scss:124:1 [W] QualifyingElement: Avoid qualifying attribute selectors with an element.
CreateNewWiki.scss:169:1 [W] QualifyingElement: Avoid qualifying attribute selectors with an element.
CreateNewWiki.scss:310:38 [W] LeadingZero: `0.1` should be written without a leading zero as `.1`
CreateNewWiki.scss:329:1 [W] IdSelector: Avoid using id selectors
CreateNewWiki.scss:329:1 [W] IdSelector: Avoid using id selectors
CreateNewWiki.scss:334:1 [W] IdSelector: Avoid using id selectors
CreateNewWiki.scss:354:1 [W] IdSelector: Avoid using id selectors
CreateNewWiki.scss:437:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 4, but was 5
CreateNewWiki.scss:444:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 4, but was 5
CreateNewWiki.scss:449:1 [W] QualifyingElement: Avoid qualifying class selectors with an element.
CreateNewWiki.scss:449:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 4, but was 5
CreateNewWiki.scss:449:1 [W] MergeableSelector: Merge rule `li.spacer` with rule on line 444
CreateNewWiki.scss:454:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 4, but was 5
CreateNewWiki.scss:455:6 [W] PropertySortOrder: Properties should be ordered background, color
```

2016-11-17 13:15 UTC, idradm commented on extensions/wikia/CreateNewWiki/css/CreateNewWiki.scss
> +@import 'extensions/wikia/DesignSystem/bower_components/design-system/dist/scss/wds-components/_buttons';
You can remove "_" (underscore) as well.

2016-11-17 13:52 UTC, idradm approved these changes

2016-11-17 13:58 UTC, lukaszkonieczny approved these changes

2016-11-17 13:59 UTC, merged