SUS-1325: introduce exception class for stale results
Wikia/app pull request #11958
Opened 2016-11-24 12:36 UTC by TK-999

Remain consistent in handling invalid cases - introduce an unique exception for the edge case where a stale page id is passed to search service

ticket: https://wikia-inc.atlassian.net/browse/SUS-1325

2016-11-24 12:37 UTC, WikiaTech commented on extensions/wikia/Search/classes/MediaWikiService.php
> +				$page = $this->getPageFromPageId( $articleId );
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove this unused "$page" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)

2016-11-24 12:37 UTC, WikiaTech commented
SonarQube analysis reported 109 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 17 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 91 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/MediaWikiService.php): File "MediaWikiService.php" has 1023 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php#L16](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/MediaWikiService.php#L16): Class "MediaWikiService" has 77 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php#L722](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/MediaWikiService.php#L722): Remove this unused "$file" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php): File "MediaWikiServiceTest.php" has 3116 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L16](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L16): Class "MediaWikiServiceTest" has 90 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L476](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L476): Remove this unused "$mockApiService" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1441](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1441): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1447](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1447): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1453](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1453): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1458](https://github.com/Wikia/app/blob/a2583791014f7d53701b5a9ed5dae9dc2d0cacf1/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1458): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)

2016-11-24 14:22 UTC, macbre commented on extensions/wikia/Search/classes/Result/StaleResultException.php
> +class StaleResultException extends \WikiaBaseException {}
Let's extend `WikiaException` class instead - it has ELK logging built in.

2016-11-24 14:22 UTC, macbre commented on extensions/wikia/Search/classes/MediaWikiService.php
> +			throw new StaleResultException();
Log page ID as an exception message?

2016-11-24 14:22 UTC, macbre requested changes
See above

2016-11-24 15:12 UTC, WikiaTech commented
SonarQube analysis reported 109 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 17 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 91 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/MediaWikiService.php): File "MediaWikiService.php" has 1020 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php#L16](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/MediaWikiService.php#L16): Class "MediaWikiService" has 77 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php#L719](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/MediaWikiService.php#L719): Remove this unused "$file" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php): File "MediaWikiServiceTest.php" has 3116 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L16](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L16): Class "MediaWikiServiceTest" has 90 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L476](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L476): Remove this unused "$mockApiService" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1441](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1441): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1447](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1447): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1453](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1453): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1458](https://github.com/Wikia/app/blob/ff12e245a20dc3fa80540c98db353f5cb75e56ab/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1458): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)

2016-11-24 15:19 UTC, macbre commented on extensions/wikia/Search/classes/MediaWikiService.php
> +			throw new StaleResultException( $pageId );
Let's cast `$pageId` to string or we may loose this message in ELK, due to elasticsearch type checks.

2016-11-24 16:01 UTC, WikiaTech commented
SonarQube analysis reported 109 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 17 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 91 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/MediaWikiService.php): File "MediaWikiService.php" has 1020 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php#L16](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/MediaWikiService.php#L16): Class "MediaWikiService" has 77 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiService.php#L719](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/MediaWikiService.php#L719): Remove this unused "$file" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php): File "MediaWikiServiceTest.php" has 3116 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L16](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L16): Class "MediaWikiServiceTest" has 90 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L476](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L476): Remove this unused "$mockApiService" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1441](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1441): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1447](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1447): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1453](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1453): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [MediaWikiServiceTest.php#L1458](https://github.com/Wikia/app/blob/5e0b4786b427a824d8bc265f0ffa2c480913ae9a/extensions/wikia/Search/classes/Test/MediaWikiServiceTest.php#L1458): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)

2016-11-24 16:15 UTC, macbre approved these changes

2016-11-25 12:51 UTC, mixth-sense commented
Tested and accepted. :medal_sports:

2016-11-25 12:51 UTC, merged