SUS-1387: fix namespace error in WallExternalController
Wikia/app pull request #11970
Opened 2016-11-25 20:59 UTC by TK-999

ticket: https://wikia-inc.atlassian.net/browse/SUS-1387

2016-11-25 21:00 UTC, WikiaTech commented
SonarQube analysis reported 28 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 7 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 14 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L10](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L10): Class "WallExternalController" has 26 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L275](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L275): The Cyclomatic Complexity of this function "deleteMessage" is 21 which is greater than 20 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1541)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L275](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L275): Reduce the number of returns of this function 5, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L306](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L306): Add a "case default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS131)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L337](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L337): Reduce this "switch/case" number of lines from 16 to at most 10, for example by extracting code into function. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1151)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L450](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L450): Reduce the number of conditional operators (4) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L710](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L710): Remove this unused private "getDisplayName" method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1144)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [WallExternalController.class.php#L56](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L56): Define a constant instead of duplicating this literal "value" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [WallExternalController.class.php#L88](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L88): Define a constant instead of duplicating this literal "error" 6 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [WallExternalController.class.php#L126](https://github.com/Wikia/app/blob/438e6f8f6cf82654adea45be25f8900744b3c5d6/extensions/wikia/Wall/WallExternalController.class.php#L126): Define a constant instead of duplicating this literal "count" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

2016-11-28 08:59 UTC, macbre commented on extensions/wikia/Wall/tests/WallExternalControllerTest.php
> +	const TEST_EDIT_TOKEN = 'Egy aprócska kalapocska, benne csacska macska mocska.';
:hungary:  :)

2016-11-28 09:00 UTC, macbre requested changes
See above

2016-11-28 09:00 UTC, macbre commented on extensions/wikia/Wall/WallExternalController.class.php
> +		if ( empty( $body ) || !in_array( $ns, $this->wg->WallNS ) ) {
There's a `WallHelper::isWallNamespace( $ns )` helper method.

2016-11-28 10:05 UTC, WikiaTech commented
SonarQube analysis reported 28 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 7 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 14 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L10](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L10): Class "WallExternalController" has 26 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L275](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L275): The Cyclomatic Complexity of this function "deleteMessage" is 21 which is greater than 20 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1541)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L275](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L275): Reduce the number of returns of this function 5, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L306](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L306): Add a "case default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS131)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L337](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L337): Reduce this "switch/case" number of lines from 16 to at most 10, for example by extracting code into function. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1151)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L450](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L450): Reduce the number of conditional operators (4) used in the expression (maximum allowed 3). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1067)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallExternalController.class.php#L710](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L710): Remove this unused private "getDisplayName" method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1144)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [WallExternalController.class.php#L56](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L56): Define a constant instead of duplicating this literal "value" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [WallExternalController.class.php#L88](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L88): Define a constant instead of duplicating this literal "error" 6 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [WallExternalController.class.php#L126](https://github.com/Wikia/app/blob/8d32cf1882f3595d0dde949646bc083504f09e72/extensions/wikia/Wall/WallExternalController.class.php#L126): Define a constant instead of duplicating this literal "count" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

2016-11-28 10:29 UTC, macbre approved these changes

2016-11-28 20:21 UTC, mixth-sense commented
Tested and accepted. :medal_sports:

2016-11-28 20:21 UTC, merged