SUS-1312 (Chat) Add groups to user model; display badges for VSTF and…
Wikia/app pull request #12098
Opened 2016-12-08 11:02 UTC by gitkuba

__DO NOT MERGE__

[SUS-1312](https://wikia-inc.atlassian.net/browse/SUS-1312)

Related change in Chat server: https://github.com/Wikia/chat/pull/39

2016-12-08 11:03 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
>  		//$().log("ABOUT TO RENDER THIS USER: " + JSON.stringify(this.model));
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)

2016-12-08 11:03 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
> +		// 	$(this.el).addClass('chatmoderator');
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)

2016-12-08 11:03 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
> +			for (var i in actions.admin) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Rename "i" as this name is already used in declaration at line 555. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2814)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-12-08 11:03 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
>  				var action = actions.admin[i],
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Rename "action" as this name is already used in declaration at line 556. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2814)

2016-12-08 11:03 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
> +		// if(groups.indexOf("staff") != -1){
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)

2016-12-08 11:03 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
>  					template = _.template( $('#user-action-'+action+'-template').html() );
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Rename "template" as this name is already used in declaration at line 557. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2814)

2016-12-08 11:03 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
> +		// 	$(this.el).addClass('staff');
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)

2016-12-08 11:03 UTC, WikiaTech commented
SonarQube analysis reported 157 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 121 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 21 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 14 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [controllers.js#L101](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L101): End this switch case with an unconditional break, continue, return or throw statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ChatAjax.class.php#L28](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/ChatAjax.class.php#L28): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L31](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L31): Remove this logging statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2228)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L68](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L68): Remove the unused function parameter "transport". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L141](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L141): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L141](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L141): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L145](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L145): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L177](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L177): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L217](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L217): Remove the unused function parameter "index". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L219](https://github.com/Wikia/app/blob/497ab07c772720ee86174784ea59b7de06b8ef5f/extensions/wikia/Chat2/js/controllers/controllers.js#L219): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2016-12-12 12:18 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
> +		if(groups.indexOf("staff") != -1){
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2016-12-12 12:18 UTC, WikiaTech commented on extensions/wikia/Chat2/js/views/views.js
>  		if(this.model.get('statusState') == STATUS_STATE_AWAY){
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2016-12-12 12:18 UTC, WikiaTech commented on extensions/wikia/Chat2/js/controllers/controllers.js
>  			case 'initial':
![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) End this switch case with an unconditional break, continue, return or throw statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)

2016-12-12 12:18 UTC, WikiaTech commented
SonarQube analysis reported 151 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 115 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 21 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 14 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ChatAjax.class.php#L28](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/ChatAjax.class.php#L28): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L31](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L31): Remove this logging statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2228)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L68](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L68): Remove the unused function parameter "transport". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L142](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L142): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L142](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L142): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L146](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L146): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L178](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L178): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L218](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L218): Remove the unused function parameter "index". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L220](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L220): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L233](https://github.com/Wikia/app/blob/caeb4b37a73843c03cafb1ae457cbfc084bbc29c/extensions/wikia/Chat2/js/controllers/controllers.js#L233): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-12-12 12:21 UTC, WikiaTech commented
SonarQube analysis reported 151 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 115 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 21 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 14 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ChatAjax.class.php#L28](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/ChatAjax.class.php#L28): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L31](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L31): Remove this logging statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2228)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L68](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L68): Remove the unused function parameter "transport". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L142](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L142): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L142](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L142): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L146](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L146): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L178](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L178): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L218](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L218): Remove the unused function parameter "index". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L220](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L220): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L233](https://github.com/Wikia/app/blob/8761000a1d066ba20efd64e56d185998c996326b/extensions/wikia/Chat2/js/controllers/controllers.js#L233): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2016-12-12 12:26 UTC, WikiaTech commented
SonarQube analysis reported 151 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 116 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 21 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 14 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ChatAjax.class.php#L28](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/ChatAjax.class.php#L28): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L31](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L31): Remove this logging statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2228)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L68](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L68): Remove the unused function parameter "transport". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L94](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L94): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L140](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L140](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L144](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L144): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L176](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L176): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L216](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L216): Remove the unused function parameter "index". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L218](https://github.com/Wikia/app/blob/cbd8f54a433b75310f09889ce763fd64a7943e7c/extensions/wikia/Chat2/js/controllers/controllers.js#L218): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2016-12-12 13:25 UTC, macbre commented on extensions/wikia/Chat2/ChatAjax.class.php
> +wfDebug('CHAT: ' . json_encode($res['groups']) . "\n");
Intending, please

2016-12-12 13:33 UTC, macbre requested changes
See above (including `!==` comments from Mr @WikiaTech)

2016-12-12 14:21 UTC, WikiaTech commented
SonarQube analysis reported 149 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 114 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 21 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 14 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ChatAjax.class.php#L28](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/ChatAjax.class.php#L28): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L31](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L31): Remove this logging statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2228)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L68](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L68): Remove the unused function parameter "transport". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L94](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L94): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L140](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L140](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L144](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L144): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L176](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L176): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L216](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L216): Remove the unused function parameter "index". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L218](https://github.com/Wikia/app/blob/4764d95db364c4cd16623625b99b168658e8991d/extensions/wikia/Chat2/js/controllers/controllers.js#L218): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2016-12-12 14:57 UTC, macbre approved these changes

2017-02-14 12:32 UTC, WikiaTech commented
SonarQube analysis reported 149 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 114 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 21 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 14 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ChatAjax.class.php#L28](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/ChatAjax.class.php#L28): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L31](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L31): Remove this logging statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2228)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L68](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L68): Remove the unused function parameter "transport". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L94](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L94): Add a "default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L140](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L140](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L144](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L144): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L176](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L176): Replace "!=" with "!==". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L216](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L216): Remove the unused function parameter "index". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [controllers.js#L218](https://github.com/Wikia/app/blob/78a69e1b0e92e7921e573030d9fbd538fc3bade8/extensions/wikia/Chat2/js/controllers/controllers.js#L218): Replace "==" with "===". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-02-15 14:31 UTC, macbre approved these changes

2017-02-16 11:44 UTC, merged