SUS-1275 | Custom404PageBestMatchingPageFinder: we're fine with querying the main namespace only
Wikia/app pull request #12105
Opened 2016-12-12 09:04 UTC by macbre

As discussed in https://wikia-inc.atlassian.net/browse/SUS-1275 we're fine with querying just the main namespace on 404 pages.

@mixth-sense / @bkoval / @gabrys

2016-12-12 09:05 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 1 info

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Custom404PageBestMatchingPageFinder.class.php#L51](https://github.com/Wikia/app/blob/d9591502b1bc5f2890b5a5d809ac03b8635775df/extensions/wikia/Custom404Page/Custom404PageBestMatchingPageFinder.class.php#L51): Reduce the number of returns of this function 5, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [Custom404PageBestMatchingPageFinder.class.php#L34](https://github.com/Wikia/app/blob/d9591502b1bc5f2890b5a5d809ac03b8635775df/extensions/wikia/Custom404Page/Custom404PageBestMatchingPageFinder.class.php#L34): Define a constant instead of duplicating this literal "numFound" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

2016-12-12 09:20 UTC, bkoval commented
LGTM!

2016-12-12 09:20 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Custom404PageBestMatchingPageFinder.class.php#L51](https://github.com/Wikia/app/blob/24b11907967d22d3c6b3157061ff4781a85d9bdc/extensions/wikia/Custom404Page/Custom404PageBestMatchingPageFinder.class.php#L51): Reduce the number of returns of this function 5, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [Custom404PageBestMatchingPageFinder.class.php#L34](https://github.com/Wikia/app/blob/24b11907967d22d3c6b3157061ff4781a85d9bdc/extensions/wikia/Custom404Page/Custom404PageBestMatchingPageFinder.class.php#L34): Define a constant instead of duplicating this literal "numFound" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

2016-12-12 18:06 UTC, gabrys requested changes
This doesn't make much sense to be honest. We shouldn't query Solr at all if we're outside of NS_MAIN. Just tweak the hook instead.

2016-12-13 09:17 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Custom404PageBestMatchingPageFinder.class.php#L51](https://github.com/Wikia/app/blob/2d56d5ffe263fd4c3961ea604e6a35053cee815f/extensions/wikia/Custom404Page/Custom404PageBestMatchingPageFinder.class.php#L51): Reduce the number of returns of this function 5, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [Custom404PageBestMatchingPageFinder.class.php#L34](https://github.com/Wikia/app/blob/2d56d5ffe263fd4c3961ea604e6a35053cee815f/extensions/wikia/Custom404Page/Custom404PageBestMatchingPageFinder.class.php#L34): Define a constant instead of duplicating this literal "numFound" 3 times. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

2016-12-13 09:23 UTC, macbre commented
@gabrys, you're obviously right. I performed an internal facepalm and added a check in the hook method.

2016-12-13 17:29 UTC, gabrys commented
@macbre It's alright :D, I guess that's why we have the code reviews. Thank you for updating! Much appreciated.

2016-12-13 17:29 UTC, gabrys approved these changes

2017-01-25 15:18 UTC, merged