XW-2384 | exchange of image preview and add image actions in adding media modal
Wikia/app pull request #12115
Opened 2016-12-14 18:56 UTC by weronika

https://wikia-inc.atlassian.net/browse/XW-2384

2016-12-14 18:56 UTC, WikiaTech commented on extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaVideoOptionWidget.js
>  ve.ui.WikiaVideoOptionWidget = function VeUiWikiaVideoOptionWidget( config ) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Make this function anonymous by removing its name: 'function() {...}'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)

2016-12-14 18:56 UTC, WikiaTech commented
SonarQube analysis reported 11 issues
* ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) 1 critical
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 8 major
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 2 info

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png) [ve.ui.WikiaMediaInsertDialog.js#L660](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/dialogs/ve.ui.WikiaMediaInsertDialog.js#L660): TypeError can be thrown as "count" might be null or undefined here. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ve.ui.WikiaMediaInsertDialog.js#L14](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/dialogs/ve.ui.WikiaMediaInsertDialog.js#L14): Make this function anonymous by removing its name: 'function() {...}'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ve.ui.WikiaMediaInsertDialog.js#L259](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/dialogs/ve.ui.WikiaMediaInsertDialog.js#L259): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ve.ui.WikiaMediaInsertDialog.js#L621](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/dialogs/ve.ui.WikiaMediaInsertDialog.js#L621): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ve.ui.WikiaMediaInsertDialog.js#L646](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/dialogs/ve.ui.WikiaMediaInsertDialog.js#L646): Restrict what this loop acts on by testing each property. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ve.ui.WikiaMediaInsertDialog.js#L649](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/dialogs/ve.ui.WikiaMediaInsertDialog.js#L649): Remove this assignment of "type". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2310)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ve.ui.WikiaMediaOptionWidget.js#L19](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaMediaOptionWidget.js#L19): Make this function anonymous by removing its name: 'function() {...}'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [ve.ui.WikiaMediaOptionWidget.js#L104](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaMediaOptionWidget.js#L104): Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)
1. ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) [ve.ui.WikiaMediaInsertDialog.js#L529](https://github.com/Wikia/app/blob/14c58d84d584191b5a3425e2e45ef6513ee50676/extensions/VisualEditor/wikia/modules/ve/ui/dialogs/ve.ui.WikiaMediaInsertDialog.js#L529): Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1135)

2016-12-15 09:15 UTC, rogatty requested changes

2016-12-15 09:15 UTC, rogatty commented on extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaMediaOptionWidget.js
>  		this.emit( 'check', this );
Can we rename this too? IMO it should emit `preview` event.

2016-12-15 09:15 UTC, rogatty commented on extensions/VisualEditor/wikia/modules/ve/ui/styles/images/icons/preview-photo.svg
> +	 width="24px" height="24px" viewBox="0 0 14 14" enable-background="new 0 0 14 14" xml:space="preserve">
Are these modified svgs used anywhere else? If yes, we should check how they look now.

2016-12-15 09:15 UTC, rogatty commented on extensions/VisualEditor/wikia/modules/ve/ui/dialogs/ve.ui.WikiaMediaInsertDialog.js
> +		check: 'onMediaPreview'
This looks confusing, let's unify the naming.

2016-12-15 09:44 UTC, weronika commented on extensions/VisualEditor/wikia/modules/ve/ui/styles/images/icons/preview-photo.svg
> +	 width="24px" height="24px" viewBox="0 0 14 14" enable-background="new 0 0 14 14" xml:space="preserve">
I've already checked that - we don't use them in no other place

2016-12-15 10:47 UTC, closed without merging