PLATFORM-2779: Improved handling of invalid response types
Wikia/app pull request #12167
Opened 2017-01-04 15:44 UTC by themech

2017-01-04 15:44 UTC, WikiaTech commented
SonarQube analysis reported 24 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 12 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 7 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L13](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaResponse.class.php#L13): Class "WikiaResponse" has 54 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L76](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaResponse.class.php#L76): Remove this unused "$jsVars" private field. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1068)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L325](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaResponse.class.php#L325): Add a "case default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS131)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L358](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaResponse.class.php#L358): Remove this unused "$key" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L394](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaResponse.class.php#L394): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L511](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaResponse.class.php#L511): Take the required action to fix the issue indicated by this "FIXME" comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1134)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L155](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaView.class.php#L155): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L258](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaView.class.php#L258): Add curly braces around the nested statement(s). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L259](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaView.class.php#L259): Add curly braces around the nested statement(s). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L297](https://github.com/Wikia/app/blob/2b69b74e844685d7083874154eaa3249a8c09f53/includes/wikia/nirvana/WikiaView.class.php#L297): Remove the code after this "return". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1763)

2017-01-04 15:48 UTC, WikiaTech commented
SonarQube analysis reported 25 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 12 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 8 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L13](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaResponse.class.php#L13): Class "WikiaResponse" has 54 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L76](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaResponse.class.php#L76): Remove this unused "$jsVars" private field. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1068)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L325](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaResponse.class.php#L325): Add a "case default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS131)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L358](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaResponse.class.php#L358): Remove this unused "$key" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L394](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaResponse.class.php#L394): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L511](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaResponse.class.php#L511): Take the required action to fix the issue indicated by this "FIXME" comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1134)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L155](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaView.class.php#L155): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L258](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaView.class.php#L258): Add curly braces around the nested statement(s). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L259](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaView.class.php#L259): Add curly braces around the nested statement(s). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L297](https://github.com/Wikia/app/blob/4fce866adc21b6c3df334dc997ae539ef158a0c0/includes/wikia/nirvana/WikiaView.class.php#L297): Remove the code after this "return". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1763)

2017-01-04 15:50 UTC, Grunny approved these changes

2017-01-05 09:43 UTC, Grunny requested changes
Minor comment, otherwise looks good.

2017-01-05 09:43 UTC, Grunny commented on includes/wikia/nirvana/WikiaResponse.class.php
> +			} else if ( $this->getFormat() == WikiaResponse::FORMAT_INVALID ) {
`elseif` and it would be better to use a strict comparison on these.

2017-01-05 12:19 UTC, WikiaTech commented
SonarQube analysis reported 25 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 12 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 8 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L13](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaResponse.class.php#L13): Class "WikiaResponse" has 54 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L76](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaResponse.class.php#L76): Remove this unused "$jsVars" private field. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1068)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L326](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaResponse.class.php#L326): Add a "case default" clause to this "switch" statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS131)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L359](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaResponse.class.php#L359): Remove this unused "$key" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L395](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaResponse.class.php#L395): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaResponse.class.php#L512](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaResponse.class.php#L512): Take the required action to fix the issue indicated by this "FIXME" comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1134)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L155](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaView.class.php#L155): Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L258](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaView.class.php#L258): Add curly braces around the nested statement(s). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L259](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaView.class.php#L259): Add curly braces around the nested statement(s). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WikiaView.class.php#L297](https://github.com/Wikia/app/blob/4e5305c342df5ea68367f9dbb894f292b3d9cb05/includes/wikia/nirvana/WikiaView.class.php#L297): Remove the code after this "return". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1763)

2017-01-05 12:20 UTC, themech commented on includes/wikia/nirvana/WikiaResponse.class.php
> +			} else if ( $this->getFormat() == WikiaResponse::FORMAT_INVALID ) {
Done. Also converted the format to lowercase in case something passes an uppercase value and switching to `===` would break it.

2017-01-05 12:29 UTC, Grunny approved these changes

2017-01-09 12:42 UTC, ludwikkazmierczak commented
Tested and Accepted

2017-01-09 12:42 UTC, merged