XW-2569 render smart wrapped items
Wikia/app pull request #12195
Opened 2017-01-10 14:25 UTC by idradm

2017-01-10 15:55 UTC, latata requested changes

2017-01-10 15:55 UTC, latata commented on extensions/wikia/PortableInfobox/services/PortableInfoboxRenderService.class.php
> +	private function calculateSmartWidths( $groupData, $capacity ) {
I'd change the name of this function to fit its purpose better.

2017-01-10 15:55 UTC, latata commented on extensions/wikia/PortableInfobox/services/PortableInfoboxRenderService.class.php
> +					$result = array_merge( $result, $this->calculateSmartWidths( $smartGroup, $capacity ) );
I'd extract these 3 lines to separated function to avoid code duplication as it's the same as few lines below

2017-01-10 15:55 UTC, latata commented on extensions/wikia/PortableInfobox/styles/PortableInfobox.scss
> +	display: block;
`display: block` is default for divs so I think we can remove this line

2017-01-10 15:55 UTC, latata commented on extensions/wikia/PortableInfobox/styles/PortableInfobox.scss
> +.pi-item {
maybe it'd be safer to have `.pi-smart-group .pi-item` selector?

2017-01-11 07:51 UTC, rybmat commented on extensions/wikia/PortableInfobox/services/PortableInfoboxRenderService.class.php
>  		$dataItems = $groupData['value'];
can we rename this variable to for example 'childItems'? dataItems suggests that only <data> children of <group> are stored there

2017-01-11 10:46 UTC, rybmat commented on extensions/wikia/PortableInfobox/services/PortableInfoboxRenderService.class.php
> +					$capacity = 0;
I think 'currentSize' or 'slotsTaken' better fits to what this variable contains than 'capacity'

2017-01-11 10:48 UTC, rybmat commented on extensions/wikia/PortableInfobox/services/PortableInfoboxRenderService.class.php
> +	private function calculateRowItemsSize( $rowItems, $capacity ) {
also here 'capacity' is misleading. Maybe 'rowSize'?

2017-01-11 11:15 UTC, idradm commented on extensions/wikia/PortableInfobox/services/PortableInfoboxRenderService.class.php
> +					$result = array_merge( $result, $this->calculateSmartWidths( $smartGroup, $capacity ) );
This is pretty hard to refactor, as I only reset those variables.

2017-01-11 11:44 UTC, latata approved these changes

2017-01-11 11:44 UTC, merged