VOLDEV-181 Update CheckUser "Replace talk pages" function to work with Message Wall
Wikia/app pull request #12259
Opened 2017-01-19 19:32 UTC by ty-a

2017-01-25 15:14 UTC, TK-999 commented
CR handled in https://wikia-inc.atlassian.net/browse/SUS-1520

2017-01-26 19:19 UTC, ghost submitted a review, later dismissed

2017-01-26 19:19 UTC, mixth-sense commented on extensions/CheckUser/CheckUser.i18n.php
> +	'checkuser-blocktag-wall' => 'Replace Message Wall Greeting with:',
:white_check_mark:

2017-01-26 19:19 UTC, mixth-sense commented on extensions/CheckUser/CheckUser_body.php
> +		$m = [];
:white_check_mark:

2017-01-26 19:19 UTC, mixth-sense commented on extensions/CheckUser/CheckUser_body.php
> +				$this->message[$msg] = wfMessage( $msg )->escaped();
:white_check_mark:

2017-01-26 19:19 UTC, mixth-sense commented on extensions/CheckUser/CheckUser_body.php
> +				'|' . wfMessage( 'checkuser-showlog' )->text() . ']]'
:white_check_mark:

2017-01-26 19:19 UTC, mixth-sense commented on extensions/CheckUser/CheckUser_body.php
>  				$revEdit = $dbr->selectField( 'revision',
Does `selectField()` imply `LIMIT 1`? Considering `$lastEdit = max( $revEdit, $logEdit );` one is all we need.

2017-01-26 19:21 UTC, ghost requested changes
Please, address the `LIMIT 1` comment, I have made.

2017-01-26 19:32 UTC, ty-a commented on extensions/CheckUser/CheckUser_body.php
>  				$revEdit = $dbr->selectField( 'revision',
According to https://github.com/Wikia/app/blob/dev/includes/db/Database.php#L1201, it does.

2017-01-27 07:29 UTC, mixth-sense commented on extensions/CheckUser/CheckUser_body.php
>  				$revEdit = $dbr->selectField( 'revision',
Cool. Then it does not to be explicitly stated here. Thank you very much!

2017-01-27 07:29 UTC, ghost approved these changes

2017-01-27 07:32 UTC, mixth-sense commented
@ty-a ― good job, thank you very much for your contribution!

This PR will be merged as soon as it is QA'd.

2017-02-01 16:19 UTC, merged