SOC-3744 add display_order to inserts for Forums
Wikia/app pull request #12252
Opened 2017-01-18 20:32 UTC by jsutterfield

Ticket: https://wikia-inc.atlassian.net/browse/SOC-3744

This PR updates the script used when dumping MW Forums/Threads in order to be migrated into Discussions. The dump now includes a `display_order` column, which is to used later to ensure the discussion categories (Discussions analog to a "Forum") are displayed in the same order as the Forums were on `Special:Forum`.

2017-01-18 20:32 UTC, jsutterfield commented on extensions/wikia/Discussions/maintenance/ForumDumper.php
> +			->SELECT( "page.*, comments_index.*, IF(pp.props is NULL, page.page_id, REPLACE(REPLACE(REPLACE(pp.props, ';', ''), 'i', ''), ':', '')) as idx" )
These nested `REPLACE` calls are pretty hideous, but they're the easiest way I found to transform a value like this: `i:123;` into `123`.

2017-01-18 21:44 UTC, garthwebb commented on extensions/wikia/Discussions/maintenance/ForumDumper.php
> +			->SELECT( "page.*, comments_index.*, IF(pp.props is NULL, page.page_id, REPLACE(REPLACE(REPLACE(pp.props, ';', ''), 'i', ''), ':', '')) as idx" )
Is there a reason `substring` doesn't work, e.g.:
```sql
SELECT SUBSTRING('i:123', 3);
```

2017-01-18 21:54 UTC, garthwebb commented on extensions/wikia/Discussions/maintenance/ForumDumper.php
> +			->SELECT( "page.*, comments_index.*, IF(pp.props is NULL, page.page_id, REPLACE(REPLACE(REPLACE(pp.props, ';', ''), 'i', ''), ':', '')) as idx" )
Maybe two of them could be replaced with a substring, e.g.:
```sql
> SELECT SUBSTR(REPLACE('i:12773;', ';', ''), 3);
+-----------------------------------------+
| SUBSTR(REPLACE('i:12773;', ';', ''), 3) |
+-----------------------------------------+
| 12773                                   |
+-----------------------------------------+
```

2017-01-18 22:00 UTC, garthwebb requested changes

2017-01-18 22:00 UTC, garthwebb commented on extensions/wikia/Discussions/maintenance/ForumDumper.php
> +			->SELECT( "page.*, comments_index.*, IF(pp.props is NULL, page.page_id, REPLACE(REPLACE(REPLACE(pp.props, ';', ''), 'i', ''), ':', '')) as idx" )
Actually, why bother with this at all?  The values as-is sort correctly and aren't particularly special (in fact as multi-digit page IDs they're kind of gross).  Initialize a PHP var to zero below in the loop, increment it for each row and assign that. (you'll have to change the sort to ascending).

2017-01-18 22:00 UTC, garthwebb commented on extensions/wikia/Discussions/maintenance/ForumDumper.php
> +						"display_order" => $row->idx
e.g.
```php
"display_order" => $row_idx++,
```

2017-01-18 22:20 UTC, garthwebb commented on extensions/wikia/Discussions/maintenance/ForumDumper.php
> +			->SELECT( "page.*, comments_index.*, IF(pp.props is NULL, page.page_id, REPLACE(REPLACE(REPLACE(pp.props, ';', ''), 'i', ''), ':', '')) as idx" )
And actually actually, you don't seem to use the display order here (https://github.com/Wikia/pandora/pull/2225/files#diff-e5c435a43d88dbeabadc3185f2abe152R153) but instead number based on the biggest number already there, so you could leave off any special handling or renumbering altogether.

2017-01-19 22:01 UTC, jsutterfield commented
Thanks @garthwebb, updated to use the counter var and got rid of those ugly replaces. Verified it works still works as expected.

2017-01-20 00:26 UTC, garthwebb approved these changes

2017-01-20 00:27 UTC, merged