XW-2448 make sure adding new param won't break parser tags
Wikia/app pull request #12290
Opened 2017-01-25 15:11 UTC by idradm

2017-01-25 15:14 UTC, idradm commented on includes/parser/Parser_LinkHooks.php
> -		$this->setHook( 'pre', array( $this, 'renderPreTag' ) );
The `renderPreTag` no longer exists here. And is registered here:
https://github.com/Wikia/app/blob/db60078cc6bb4185814bdd4df8a957be0889cf68/includes/parser/CoreTagHooks.php#L19-L19

2017-01-25 17:11 UTC, kvas-damian approved these changes

2017-01-26 12:29 UTC, hakubo approved these changes
Magic 🎆

2017-01-27 09:41 UTC, macbre requested changes

2017-01-27 09:41 UTC, macbre commented on extensions/CategoryTree/CategoryTree.php
> +
Please mark this change with `// Wikia change` comment just in case we want to upgrade this extension in the future.

2017-01-27 09:57 UTC, rogatty commented on extensions/CategoryTree/CategoryTree.php
> +
Done :sparkles:

2017-01-27 10:29 UTC, macbre approved these changes

2017-02-01 10:50 UTC, merged