SUS-1514: Log parsing time for GeSHi syntax highlight
Wikia/app pull request #12318
Opened 2017-01-31 13:08 UTC by TK-999

https://wikia-inc.atlassian.net/browse/SUS-1514

2017-01-31 13:33 UTC, macbre commented on extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.class.php
> +			'parsingTime' => $geSHi->get_time()
What's the unit of the time reported here?

2017-01-31 13:36 UTC, macbre requested changes

2017-01-31 13:36 UTC, macbre commented on extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.class.php
> +			'titleText' => $title->getPrefixedText(),
Page URL will be reported as a part of generic logger context. Do we need to log `titleText` here?

2017-01-31 13:59 UTC, TK-999 commented on extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.class.php
> +			'parsingTime' => $geSHi->get_time()
PHP  `microtime` format-style double generated at https://github.com/Wikia/app/blob/a2f56c08de6461f475232c399c4601eb5347d25c/extensions/SyntaxHighlight_GeSHi/geshi/geshi.php#L3677

2017-01-31 13:59 UTC, TK-999 commented on extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.class.php
> +			'titleText' => $title->getPrefixedText(),
good catch - will remove :)

2017-02-01 12:56 UTC, macbre approved these changes

2017-02-01 13:02 UTC, merged