VOLDEV-186: Whitelist Gadget-* to make the gadget extension usable
Wikia/app pull request #12342
Opened 2017-02-03 09:30 UTC by onei

Also whitelists Gadgets-*, which applies to messages defined by the extension itself, thus allowing users to alter gadgets-definition as well.

@Grunny

2017-02-03 12:06 UTC, TK-999 commented
CR: https://wikia-inc.atlassian.net/browse/SUS-1548

2017-02-03 12:25 UTC, mszabo-wikia requested changes

2017-02-03 12:25 UTC, TK-999 commented on extensions/Gadgets/Gadgets_body.php
> +				$section = wfMessage( "gadget-section-$section" )->parse();
We should consider either adding separate use for each possible value of `$section`, or at least list the possible values in comments - helps when searching for usage of messages

2017-02-03 12:25 UTC, TK-999 commented on extensions/Gadgets/SpecialGadgets.php
> +			. Xml::submitButton( wfMessage( 'gadgets-export-download' )->escaped() )
This function escapes its parameter, so no need for double escaping here

2017-02-03 14:57 UTC, onei commented on extensions/Gadgets/Gadgets_body.php
> +				$section = wfMessage( "gadget-section-$section" )->parse();
In this case, the name of the message is user defined allowing them to group similar gadgets under appropriate heads on gadgets-definition and Special:Gadgets. if you wanted a list of them, you'd have to look them up on Special:PrefixIndex on the wiki the extension is installed on or something similar. The messages from the extension are prefixed with gadgets-*.

2017-02-06 09:15 UTC, onei commented on extensions/Gadgets/SpecialGadgets.php
> +			. Xml::submitButton( wfMessage( 'gadgets-export-download' )->escaped() )
Done in 21954ee

2017-02-06 14:50 UTC, macbre approved these changes

2017-02-06 14:51 UTC, macbre commented
Ok, let's merge this one into a branch in our upstream repository. Once it passes QA we can merge it into our dev.

2017-02-06 15:28 UTC, merged