SER-777 Pulled Wall translations from crowdin
Wikia/app pull request #12362
Opened 2017-02-06 13:22 UTC by jcellary

https://wikia-inc.atlassian.net/browse/SER-777

Pulled new wall translations from Crowdin, on Keiko's request.

Pinging @macbre and @mixth-sense since Wall is in Sus

2017-02-06 13:31 UTC, macbre requested changes

2017-02-06 13:31 UTC, macbre commented on extensions/wikia/Wall/Wall.i18n.php
> +	'right-wallshowwikiaemblem' => 'Flags user as "Wikia Staff" on wall posts',
Shouldn't that say "Fandom Staff"?

2017-02-06 13:37 UTC, jcellary commented on extensions/wikia/Wall/Wall.i18n.php
> +	'right-wallshowwikiaemblem' => 'Flags user as "Wikia Staff" on wall posts',
Good catch! I see that the old version also has Wikia used, so I guess we need to adjust the translations in crowdin and repull them. I'll ping Keiko.

2017-02-06 19:16 UTC, TK-999 commented
@macbre @jcellary 

We need to verify the state of the translations with LOC and other stakeholders here because Messaging Wiki import left this file out of sync. 😢 

For example, (wall-message-rev-delete)[https://github.com/Wikia/app/blob/88eb948e6258a741840ff98b194441785777ff76/extensions/wikia/Wall/Wall.i18n.php#L2305] was changed to ("Borrar revisión")[https://github.com/Wikia/app/blame/dev/extensions/wikia/Wall/Wall.i18n.php#L2157] in 9ee7e97370b11c488e7843a8f5f80d7a0a1c4d8d as part of the import but now it'd be changed back, so we should make sure this is OK to do.

2017-02-07 14:25 UTC, jcellary commented
Thanks Mate, I followed up in https://wikia-inc.atlassian.net/browse/MAIN-9694

2017-02-07 14:25 UTC, closed without merging