ADEN-4685 Resolved state with two image assets
Wikia/app pull request #12397
Opened 2017-02-09 17:36 UTC by fraszczakszymon

2017-02-09 17:36 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/template/bfaaDesktop.js
>  ], function (uapContext,
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Function has 10 parameters which is greater than 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2017-02-09 17:36 UTC, WikiaTech commented
SonarQube analysis reported 1 issue
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major

Watch the comments in this conversation to review them.

2017-02-10 08:11 UTC, mleczey requested changes

2017-02-10 08:11 UTC, mleczey commented on extensions/wikia/AdEngine/js/spec/slot/resolvedState.spec.js
> +			if (testCase.twoAssets) {
Could you split this `if` to two different test cases?

2017-02-10 08:11 UTC, mleczey commented on extensions/wikia/AdEngine/js/slot/resolvedState.js
> +		var correctSplitImages = params.resolvedState.leftImageSrc && params.resolvedState.rightImageSrc;
Just asking, didn't we want to resign from left/right naming? (use first, second, and give parameter which of those will have video overlay)

2017-02-10 09:33 UTC, mleczey approved these changes

2017-02-10 13:54 UTC, merged