VOLDEV-185 Link masthead edit count to Special:Contributions
Wikia/app pull request #12427
Opened 2017-02-16 21:15 UTC by ty-a

2017-02-22 11:00 UTC, TK-999 commented
CR: https://wikia-inc.atlassian.net/browse/SUS-1708

2017-02-23 09:55 UTC, macbre requested changes

2017-02-23 09:55 UTC, macbre commented on extensions/wikia/UserProfilePageV3/templates/UserProfilePage_renderUserIdentityBox.php
> -						<em><?= $user['edits'] ?></em>
Do we need to check `!empty( $user['registration'] )` above once again?

2017-02-23 16:06 UTC, macbre approved these changes

2017-02-23 16:06 UTC, ty-a commented on extensions/wikia/UserProfilePageV3/templates/UserProfilePage_renderUserIdentityBox.php
> -						<em><?= $user['edits'] ?></em>
Oh wow. I've removed that check.

2017-02-23 16:06 UTC, macbre commented
Thanks, @ty-a !

I'm going to merge this PR into a feature branch that we can pass to QA and the we'll merge it to dev.

2017-02-25 21:28 UTC, merged