SUS-723 | Checking namespace before displaying wall message
Wikia/app pull request #12425
Opened 2017-02-16 14:56 UTC by rybmat

https://wikia-inc.atlassian.net/browse/SUS-723

2017-02-16 14:57 UTC, WikiaTech commented on extensions/wikia/Wall/WallMessage.class.php
>  		$title = Title::newFromID( $id, $master == true ? Title::GAID_FOR_UPDATE : 0 );
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Remove the literal "true" boolean value. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1125)

2017-02-16 14:57 UTC, WikiaTech commented
SonarQube analysis reported 46 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 17 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 17 minor
* ![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png) 12 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php): File "WallMessage.class.php" has 1772 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L7](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L7): Class "WallMessage" has 127 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L50](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L50): Reduce the number of returns of this function 5, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L162](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L162): This function has 8 parameters, which is greater than the 7 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L162](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L162): Reduce the number of returns of this function 5, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L227](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L227): Remove this unused "$userMaster" local variable. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L437](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L437): Reduce the number of returns of this function 4, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L495](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L495): Reduce the number of returns of this function 7, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L530](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L530): Reduce the number of returns of this function 8, down to the maximum allowed 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [WallMessage.class.php#L671](https://github.com/Wikia/app/blob/ddc61a32f3a84864e1cdd649c01b89369ad43947/extensions/wikia/Wall/WallMessage.class.php#L671): Merge this if statement with the enclosing one. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)

2017-02-16 15:11 UTC, macbre approved these changes

2017-02-16 15:17 UTC, TK-999 commented
Should we log if something like this happens? IMO this is a definitive indicator of broken state of `comments_index` so we should make sure we have context on it when it happens.

2017-02-16 15:17 UTC, mszabo-wikia requested changes
Should we log if something like this happens? IMO this is a definitive indicator of broken state of comments_index so we should make sure we have context on it when it happens.

2017-02-16 15:22 UTC, TK-999 commented on extensions/wikia/Wall/WallMessage.class.php
> +		return in_array( $title->getNamespace(), [ NS_USER_WALL_MESSAGE, NS_USER_WALL_MESSAGE_GREETING ] );
What about Forum?

2017-02-16 15:28 UTC, rybmat commented
@TK-999 as mentioned in ticket's comment, when proposal for delete flow will be implemented and released this state will not be possible because entry from comments index will be removed when removing  the message from wall. Currently there is a lot of such broken entries in db and I plan to write maintenance script to remove them. Knowing that I don't think that logging is necessary

2017-02-16 15:31 UTC, rybmat commented on extensions/wikia/Wall/WallMessage.class.php
> +		return in_array( $title->getNamespace(), [ NS_USER_WALL_MESSAGE, NS_USER_WALL_MESSAGE_GREETING ] );
From what I have seen forum checks namespace, but if you know place where it should also be applied please give me a link ;)

2017-02-16 16:17 UTC, mszabo-wikia approved these changes

2017-02-27 14:00 UTC, macbre approved these changes

2017-02-27 16:23 UTC, TK-999 commented on extensions/wikia/Wall/WallMessage.class.php
> +		return in_array( $title->getNamespace(), [ NS_USER_WALL_MESSAGE, NS_USER_WALL_MESSAGE_GREETING, NS_WIKIA_FORUM_BOARD_THREAD ] );
Let's use `Title::inNamespaces` helper here.

2017-02-28 08:46 UTC, macbre approved these changes

2017-02-28 09:01 UTC, merged