SUS-1698: In Chat fetch user name from right rail
Wikia/app pull request #12455
Opened 2017-02-22 01:04 UTC by TK-999

https://wikia-inc.atlassian.net/browse/SUS-1698

2017-02-22 16:01 UTC, rybmat requested changes

2017-02-22 16:01 UTC, rybmat commented on extensions/wikia/Chat2/js/views/views.js
>      		if(!(name.length > 0)) {
can we simplify this condition? i.e  `if (name.length === 0)` or even `if (name)` should also work

2017-02-22 16:23 UTC, rybmat approved these changes

2017-02-23 09:46 UTC, macbre approved these changes

2017-02-23 20:50 UTC, merged