SUS-1706 | override float for .mw-collapsible-toggle on wall
Wikia/app pull request #12478
Opened 2017-02-24 14:40 UTC by rybmat

https://wikia-inc.atlassian.net/browse/SUS-1706

2017-02-24 14:48 UTC, mszabo-wikia requested changes

2017-02-24 14:48 UTC, TK-999 commented on extensions/wikia/Wall/css/Wall.scss
> +		float: right;
Is this setting correct for RTL languages as well?

2017-02-24 14:53 UTC, rybmat commented on extensions/wikia/Wall/css/Wall.scss
> +		float: right;
I didn't find anything in the app repo that would set it to other value than right or none, so I guess it is correct

2017-02-24 14:54 UTC, mszabo-wikia approved these changes

2017-02-27 09:07 UTC, macbre approved these changes

2017-02-27 20:34 UTC, merged