MAIN-9881: Upgraded PHPUnit to 6.0.*
Wikia/app pull request #12501
Opened 2017-02-28 14:12 UTC by TK-999

https://wikia-inc.atlassian.net/browse/MAIN-9881

2017-02-28 15:37 UTC, macbre commented on extensions/wikia/ScavengerHunt/tests/ScavengerHuntTest.php
> +abstract class ScavengerHuntTest extends WikiaBaseTest {
Worth checking if we actually have ` ScavengerHunt` enabled anywhere.

2017-02-28 15:42 UTC, TK-999 commented on extensions/wikia/ScavengerHunt/tests/ScavengerHuntTest.php
> +abstract class ScavengerHuntTest extends WikiaBaseTest {
Yeah. All tests were marked as `Broken` 4 years ago and the extension might be disabled now.

2017-02-28 17:20 UTC, macbre requested changes

2017-02-28 17:20 UTC, macbre commented on lib/Wikia/tests/Logger/WikiaLoggerTest.php
> +class WikiaLoggerTest extends \PHPUnit\Framework\TestCase {
Let's be consistent when extending `TestCase` class, either provide the full "path" with namespaces or use `use`.

2017-02-28 17:21 UTC, macbre commented on extensions/wikia/ScavengerHunt/tests/ScavengerHuntTest.php
> +abstract class ScavengerHuntTest extends WikiaBaseTest {
https://wikia-inc.atlassian.net/browse/SUS-1730

2017-02-28 17:27 UTC, macbre commented
:+1: let's make the `TestCase` use consistent and we're good :)

2017-03-01 09:13 UTC, macbre approved these changes

2017-03-01 09:14 UTC, macbre commented
@TK-999, worth checking why `unitTests_php_branches` Jenkins task did not run (or at least did not report the results here).

2017-03-14 12:51 UTC, macbre commented
:+1:  if tests do pass now, let's simply merge it and announce the good news

Thanks, @TK-999  :)

2017-03-15 20:04 UTC, merged