XW-2775 | article header
Wikia/app pull request #12607
Opened 2017-03-14 14:46 UTC by idradm

https://wikia-inc.atlassian.net/browse/XW-2775

2017-03-15 16:28 UTC, rybmat commented on extensions/wikia/AssetsManager/config.php
> +		'//extensions/wikia/PremiumPageHeader/scripts/share-entry-point-hack.js',
so many hacks :)

2017-03-15 16:57 UTC, rybmat requested changes

2017-03-15 16:57 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/PremiumPageHeaderController.class.php
> +		if ( $this->app->getSkinTemplateObj() ) {
can we move this block to `widgetLanguages()` method and return list of languages from this method?
then we have here only `$this->setVal('language_list', $this->widgetLanguages());`

2017-03-16 08:55 UTC, rybmat requested changes

2017-03-16 08:55 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/PremiumPageHeaderController.class.php
> +		# print_pre($this->content_actions);
can we remove this commented code?

2017-03-16 08:55 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/PremiumPageHeaderController.class.php
> +		# print_pre($this->action); print_pre($this->actionImage); print_pre($this->actionName);
can we remove this commented code?

2017-03-16 08:55 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/PremiumPageHeaderController.class.php
> +			$langSortBy = [
I wonder if we should sort languages like this or maybe in alphabetical order? question probably for our designers

2017-03-16 08:55 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/PremiumPageHeaderController.class.php
> +			!empty( $wgEnableDiscussionsNavigation ) && !empty( $wgEnableDiscussions ) &&
not sure if it is worth to do it now, but we should create separate variable for checking if discuss button should point to discussions or forum as this is exactly the same condition like https://github.com/Wikia/config/blob/c8e54b44bb779d9348af3374413933110e0c1c22/CommonExtensions.php#L1278-L1278

2017-03-16 08:55 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/scripts/article-header.js
> +	var _track = tracker.buildTrackingFunction({
why the name of this var starts with underscore? is it some new convention? AFAIR (at least in tracking) we used just `track`

2017-03-16 08:55 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/templates/PremiumPageHeader_articleHeader.php
> +					<?= join( ', ', $visibleCategories ); ?><!--
is this comment tag needed?

2017-03-16 08:55 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/templates/PremiumPageHeader_articleHeader.php
> +						</div><!--
is this comment tag needed?

2017-03-16 08:55 UTC, rybmat commented on skins/oasis/modules/templates/Body_Index.php
> +			<?= $app->renderView( 'BannerNotifications', 'Confirmation' ) ?>
what is the reason to show it only if the new wiki header is not shown?

2017-03-16 09:35 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/styles/_banner-notifications-hack.scss
> +	top: 0 !important;
does it really need to be !important?

2017-03-16 09:35 UTC, rybmat commented on extensions/wikia/PremiumPageHeader/templates/PremiumPageHeader_articleHeader.php
> +		<?php if ( count( $visibleCategories ) ): ?>
`count( $visibleCategories ) > 0` to be more explicit?

2017-03-16 09:49 UTC, idradm commented on extensions/wikia/PremiumPageHeader/PremiumPageHeaderController.class.php
> +			!empty( $wgEnableDiscussionsNavigation ) && !empty( $wgEnableDiscussions ) &&
I'd assume that `explore` navigation tab will be provided externally, so we won't be checking this anymore.

2017-03-16 09:49 UTC, idradm commented on extensions/wikia/PremiumPageHeader/styles/_banner-notifications-hack.scss
> +	top: 0 !important;
We will have to test it properly, however, this is causing the issue https://github.com/Wikia/app/blob/cbfe441e7b83b2305c29efade30444ee94bb7e76/extensions/wikia/BannerNotifications/js/BannerNotifications.js#L231

2017-03-16 09:49 UTC, idradm commented on extensions/wikia/PremiumPageHeader/templates/PremiumPageHeader_articleHeader.php
> +					<?= join( ', ', $visibleCategories ); ?><!--
Yes, otherwise we get an empty space before `,`.

2017-03-16 09:49 UTC, idradm commented on skins/oasis/modules/templates/Body_Index.php
> +			<?= $app->renderView( 'BannerNotifications', 'Confirmation' ) ?>
For new header purposes, I've moved it to line 23, and this is the `old` behavior for not tested wikis.

2017-03-16 10:54 UTC, rybmat approved these changes

2017-03-17 15:07 UTC, merged