SUS-1508: Introduce limit parameter for domains query
Wikia/app pull request #12627
Opened 2017-03-20 10:34 UTC by TK-999

https://wikia-inc.atlassian.net/browse/SUS-1508

2017-03-20 13:34 UTC, macbre approved these changes
`city_id` are obviously not continuous values (as we remove unactive wikis), but still :+1:  :)

2017-03-21 09:48 UTC, ghost requested changes

2017-03-21 09:48 UTC, mixth-sense commented on extensions/wikia/WikiaApi/WikiaApiQueryDomains.php
> +				$limit = min( $requested, $maxLimit );
Do we want `$limit` to be set only when `$from` and `$to` are not empty? What if any of those is not set? No limit at all?

2017-03-21 09:48 UTC, mixth-sense commented on extensions/wikia/WikiaApi/WikiaApiQueryDomains.php
> +			$this->addOption( 'LIMIT', $limit );
Possible use of undeclared variable here and MySQL error.

2017-03-21 09:49 UTC, TK-999 commented on extensions/wikia/WikiaApi/WikiaApiQueryDomains.php
> +			$this->addOption( 'LIMIT', $limit );
If the variable is not provided by user in the URL, MW API will set it to the default value declared on https://github.com/Wikia/app/pull/12627/files#diff-7f7f6f25d0e2d3ff0f4770cea8e296dbR165 . So without a provided parameter, limit will be 10.

2017-03-21 09:51 UTC, mixth-sense commented on extensions/wikia/WikiaApi/WikiaApiQueryDomains.php
> +			$this->addOption( 'LIMIT', $limit );
Thanks!

2017-03-21 09:51 UTC, ghost approved these changes

2017-03-21 12:42 UTC, mixth-sense commented
Tested and accepted.

2017-03-21 12:42 UTC, merged