XW-3063 | introduce article video info into ads context
Wikia/app pull request #12702
Opened 2017-03-29 12:29 UTC by idradm

https://wikia-inc.atlassian.net/browse/XW-3063

2017-03-29 12:41 UTC, latata approved these changes

2017-03-29 13:21 UTC, hakubo commented
Do you think we could add unit tests here?

2017-03-30 10:36 UTC, latata approved these changes

2017-03-30 11:23 UTC, weronika requested changes

2017-03-30 11:23 UTC, weronika commented on extensions/wikia/ArticleVideo/ArticleVideo.hooks.php
>  	public static function isRelatedVideoEmbedded( $relatedVideo ) {
shouldn't this method and the one below also go to ArticleVideoContext class?

2017-03-31 08:00 UTC, latata commented on extensions/wikia/ArticleVideo/ArticleVideoContext.class.php
> +		return [];
I'd say that it should return `null`instead of empty array

2017-03-31 08:00 UTC, latata commented on extensions/wikia/ArticleVideo/tests/ArticleVideoContextTest.php
> +		$expected,
does the format fit to our style guide? each argument in separate line looks strange for me

2017-03-31 08:43 UTC, idradm commented on extensions/wikia/ArticleVideo/tests/ArticleVideoContextTest.php
> +		$expected,
AFAIK it does. I prefer it over breaking in the middle of parameters list.

2017-03-31 08:43 UTC, idradm commented on extensions/wikia/ArticleVideo/ArticleVideoContext.class.php
> +		return [];
Why would you say so?

2017-03-31 09:04 UTC, latata approved these changes

2017-03-31 09:16 UTC, weronika approved these changes

2017-03-31 11:42 UTC, merged