ADEN-4923 Changes to our IMA integration
Wikia/app pull request #12731
Opened 2017-04-03 12:53 UTC by nandy-andy

https://wikia-inc.atlassian.net/browse/ADEN-4923

2017-04-03 12:56 UTC, mleczey commented on extensions/wikia/AdEngine/js/template/porvata.js
> +				params.container = getVideoContainer(params.slotName);
Get video container is doing some modifications in DOM. Are you sure that this change in logic/order is safe?

2017-04-03 13:01 UTC, nandy-andy commented on extensions/wikia/AdEngine/js/template/porvata.js
> +				params.container = getVideoContainer(params.slotName);
Well, it's all wrapped in a condition which checks if it's `INSECURE`, so I'm sure it's not safe ;) Do you think moving it here is a big difference comparing to the previous place? I needed to move it here, so we're sure IMA is loaded and we can re-use IMA's enums. What other options do you think we have?

2017-04-03 13:26 UTC, nandy-andy commented on extensions/wikia/AdEngine/js/template/porvata.js
> +				params.container = getVideoContainer(params.slotName);
I can't find any issues with our test pages for Porvata or VUAP. However, I don't recall any test page with VPAID. @fraszczakszymon advice, please :) In the end, I think we can change the template parameter to our own flag and don't depend on `google.ima.ImaSdkSettings.VpaidMode.INSECURE` here. Something like:
```
if (params.insecureVpaidMode) {
}
```
before calling `porvata.inject()`.

2017-04-04 07:29 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/template/porvata.js
> +				params.container = getVideoContainer(params.slotName);
This code has to be called before injecting porvata player because it decides how DOM is going to be build

2017-04-04 07:36 UTC, fraszczakszymon commented
What about:
```
extensions/wikia/AdEngine/js/video/uapVideo.js:71:                              video.addEventListener('allAdsCompleted', function () {
extensions/wikia/AdEngine/js/video/uapVideo.js:148:                     win.addEventListener('resize', throttle(function () {
extensions/wikia/AdEngine/js/video/player/porvata/floater.js:43:                                elements.video.addEventListener('start', listeners.start);
extensions/wikia/AdEngine/js/video/player/porvata/floater.js:174:                               elements.video.addEventListener('resume', listeners.adResumed);
extensions/wikia/AdEngine/js/video/player/porvata/floaterConfiguration.js:72:                                   video.addEventListener('loaded', function () {adsManagerLoadedCallback, false);
extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js:152:                addEventListener('resume', setStatus('playing'));
extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js:153:                addEventListener('start', setStatus('playing'));
extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js:154:                addEventListener('pause', setStatus('paused'));
extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js:155:                addEventListener('complete', setStatus('completed'));
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:38:                        video.addEventListener('loaded', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:98:                                video.addEventListener('adCanPlay', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:102:                               video.addEventListener('allAdsCompleted', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:112:                               video.addEventListener('start', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:118:                               video.addEventListener('resume', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:122:                               video.addEventListener('pause', function () {
extensions/wikia/AdEngine/js/video/player/ui/playPauseButton.js:55:             video.addEventListener('pause', function () {
extensions/wikia/AdEngine/js/video/player/ui/playPauseButton.js:59:             video.addEventListener('resume', function () {
```

2017-04-04 07:37 UTC, fraszczakszymon requested changes
What about:
```
extensions/wikia/AdEngine/js/video/uapVideo.js:71:                              video.addEventListener('allAdsCompleted', function () {
extensions/wikia/AdEngine/js/video/uapVideo.js:148:                     win.addEventListener('resize', throttle(function () {
extensions/wikia/AdEngine/js/video/player/porvata/floater.js:43:                                elements.video.addEventListener('start', listeners.start);
extensions/wikia/AdEngine/js/video/player/porvata/floater.js:174:                               elements.video.addEventListener('resume', listeners.adResumed);
extensions/wikia/AdEngine/js/video/player/porvata/floaterConfiguration.js:72:                                   video.addEventListener('loaded', function () {adsManagerLoadedCallback, false);
extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js:152:                addEventListener('resume', setStatus('playing'));
extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js:153:                addEventListener('start', setStatus('playing'));
extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js:154:                addEventListener('pause', setStatus('paused'));
extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js:155:                addEventListener('complete', setStatus('completed'));
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:38:                        video.addEventListener('loaded', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:98:                                video.addEventListener('adCanPlay', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:102:                               video.addEventListener('allAdsCompleted', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:112:                               video.addEventListener('start', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:118:                               video.addEventListener('resume', function () {
extensions/wikia/AdEngine/js/video/player/porvata/porvata.js:122:                               video.addEventListener('pause', function () {
extensions/wikia/AdEngine/js/video/player/ui/playPauseButton.js:55:             video.addEventListener('pause', function () {
extensions/wikia/AdEngine/js/video/player/ui/playPauseButton.js:59:             video.addEventListener('resume', function () {
```

2017-04-04 17:59 UTC, nandy-andy commented on extensions/wikia/AdEngine/js/template/porvata.js
> +				params.container = getVideoContainer(params.slotName);
Corrected: https://github.com/Wikia/app/pull/12731/commits/4a3c01a196ac213b76bddd16f57c84fb5215ff07 :+1:

2017-04-04 18:01 UTC, nandy-andy commented
I wouldn't change those places, @fraszczakszymon because those are our custom events and the places we used `google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED` are the ones in our wrapper for IMA. What are the reasons you'd change it everywhere (if you would)?

2017-04-05 07:03 UTC, fraszczakszymon commented
@nandy-andy those events are not custom, `wikia*` events are custom only. Check out `google.ima.AdEvent.Type` object please

2017-04-05 07:26 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/template/porvata.js
> +			imaVpaidModeInsecure = 2;
`google.ima.ImaSdkSettings.VpaidMode.INSECURE`

2017-04-05 09:41 UTC, nandy-andy commented
Oh, you're right of course: https://github.com/Wikia/app/blob/4a3c01a196ac213b76bddd16f57c84fb5215ff07/extensions/wikia/AdEngine/js/video/player/porvata/googleImaPlayerFactory.js#L34! :smile_cat: And I was checking `google.ima.AdsManagerLoadedEvent.Type` not `google.ima.AdEvent.Type`. Seems like worth changing, doesn't it?

2017-04-05 09:55 UTC, fraszczakszymon approved these changes

2017-04-06 08:25 UTC, merged