SUS-1929
Wikia/app pull request #12742
Opened 2017-04-04 16:33 UTC by timmyquivy

Removing CloseMyAccount supported langauge conditional - After discussion, the behavior, even for non-support languages, is always better going through CloseMyAccount as opposed to going through Special:Contact.

2017-04-04 16:39 UTC, Grunny requested changes

2017-04-04 16:39 UTC, Grunny commented on extensions/wikia/SpecialContact2/SpecialContact.body.php
> -}
One brace too many removed, will cause a fatal error.

2017-04-04 16:39 UTC, Grunny commented on extensions/wikia/SpecialContact2/SpecialContact.body.php
> -				&& in_array( $wgContLang->getCode(), $wgSupportedCloseMyAccountLang );
Can we remove `wgSupportedCloseMyAccountLang` from the config repo as well as cleanup?

2017-04-04 16:58 UTC, timmyquivy commented
Fixed the bracket, don't know what happened with my GUI there. Looking at config.

2017-04-04 18:50 UTC, timmyquivy commented
@Grunny: https://github.com/Wikia/config/pull/2100. I believe we are now good?

2017-04-05 14:44 UTC, timmyquivy commented on extensions/wikia/SpecialContact2/SpecialContact.body.php
> -				&& in_array( $wgContLang->getCode(), $wgSupportedCloseMyAccountLang );
This is done. https://github.com/Wikia/config/pull/2100

2017-04-20 10:14 UTC, ghost approved these changes

2017-04-20 10:26 UTC, mixth-sense commented
@timmyquivy - I have made a comment under the ticket https://wikia-inc.atlassian.net/browse/SUS-1929

2017-07-26 11:03 UTC, closed without merging