XW-3127 | new right rail recirculation
Wikia/app pull request #12758
Opened 2017-04-06 13:47 UTC by latata

For the test I just copied rail recirc module code. We gonna clean it up when we will productize it.

https://wikia-inc.atlassian.net/browse/XW-3127

@Wikia/x-wing

2017-04-06 14:17 UTC, rybmat approved these changes
two minor comments but lgtm

2017-04-06 14:17 UTC, rybmat commented on extensions/wikia/Recirculation/js/views/premiumRail.js
> +				$('#RECIRCULATION_RAIL').html($html);
why this id is written with ALL_CAPS?

2017-04-06 14:17 UTC, rybmat commented on extensions/wikia/Recirculation/styles/premium-rail.scss
> +	border: 0;
is there any difference between border: 0; and border: none; ?

2017-04-06 14:21 UTC, latata commented on extensions/wikia/Recirculation/styles/premium-rail.scss
> +	border: 0;
It's shorter ;)

2017-04-06 14:21 UTC, latata commented on extensions/wikia/Recirculation/js/views/premiumRail.js
> +				$('#RECIRCULATION_RAIL').html($html);
let's leave it for now

2017-04-06 21:21 UTC, weronika commented on extensions/wikia/Recirculation/styles/premium-rail.scss
> +	border: 0;
and we should use border: 0; according to our css coding standards

2017-04-06 21:29 UTC, weronika requested changes

2017-04-06 21:29 UTC, weronika commented on extensions/wikia/Recirculation/templates/client/premiumRail.mustache
> +							</div>
Do we alway have `presented_by` var set? And why every second item has this div hidden? I would also recommend to use i18n string here (even if not translated).

2017-04-07 07:49 UTC, latata commented on extensions/wikia/Recirculation/templates/client/premiumRail.mustache
> +							</div>
That was just a temporary change for design review. Sorry I though that no one will review the code at the night. ;) I'd extract strings to i18n in recirc productization task.

2017-04-07 08:28 UTC, weronika approved these changes

2017-04-10 12:50 UTC, merged