XW-3201 | timestamps format update
Wikia/app pull request #12792
Opened 2017-04-14 09:50 UTC by weronika

https://wikia-inc.atlassian.net/browse/XW-3201

2017-04-14 10:12 UTC, latata commented on extensions/wikia/Wall/templates/Wall_message.php
> +				<span class="subtle edittime" title="<?= $iso_timestamp ?>">• <?= $fmt_timestamp ?></span>
How about moving the bullet outside the `<span>`?

2017-04-14 10:12 UTC, latata commented on extensions/wikia/Wall/templates/Wall_message.php
> +				<span class="subtle edittime" title="<?= $iso_timestamp ?>">• <?= $fmt_timestamp ?></span>
`edittime` class is not valid here as we show only creation date

2017-04-14 10:12 UTC, latata commented on extensions/wikia/MyHome/templates/feed.tmpl.php
> +			<cite><?php print $timestamp; ?><?php print FeedRenderer::getActionLabel($row); ?><?php print FeedRenderer::getDiffLink($row); ?></cite>
Shouldn't we move it to i18n to allow translators make decision about the order of these labels (timestamp / action label)?

2017-04-14 10:12 UTC, latata commented on extensions/wikia/WikiaNewFiles/WikiaNewFilesGallery.class.php
> +			$caption .= " • <i>$timeago</i><br />\n";
Don't we want to allow translators to make decision about the order of these labels?

2017-04-14 10:13 UTC, rybmat requested changes

2017-04-14 10:13 UTC, rybmat commented on extensions/GlobalMessages/GlobalMessagesW.i18n.php
> +	'wikia-seconds-ago' => '$1{{PLURAL:$1|s|s}}',
if the plural and singular version does not differ, do we have to use {{PLURAL}} helper?

2017-04-14 10:13 UTC, rybmat commented on extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php
> +			$entry['timeago'] = wfTimeFormatAgo($entry['timestamp']);
array_map(..)? or at least please avoid modifying array you iterate on

2017-04-14 10:13 UTC, rybmat commented on includes/wikia/GlobalFunctions.php
> +		// Under 7 days: to the day (5 days ago)
please update the comment to show the actual time format: 5 days ago -> 5d

2017-04-14 10:14 UTC, latata commented on extensions/GlobalMessages/GlobalMessagesW.i18n.php
> +	'wikia-seconds-ago' => '$1{{PLURAL:$1|s|s}}',
we don't know if that won't differ in other languages

2017-04-14 11:23 UTC, latata approved these changes

2017-04-14 11:33 UTC, rybmat approved these changes

2017-05-17 08:47 UTC, closed without merging

2017-05-17 08:47 UTC, WikiaTech commented on includes/wikia/GlobalFunctions.php
>  		$res = wfMsgExt( 'wikia-hours-ago', array( 'parsemag' ), floor( $ago / 3600 ) );
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)

2017-05-17 08:47 UTC, WikiaTech commented on includes/wikia/GlobalFunctions.php
>  		$res = wfMsgExt( 'wikia-days-ago', array( 'parsemag' ), floor( $ago / 86400 ) );
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)

2017-05-17 08:47 UTC, WikiaTech commented on includes/wikia/GlobalFunctions.php
>  		$res = wfMsgExt( 'wikia-seconds-ago', array( 'parsemag' ), $ago );
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)

2017-05-17 08:47 UTC, WikiaTech commented on includes/wikia/GlobalFunctions.php
>  		$res = wfMsgExt( 'wikia-minutes-ago', array( 'parsemag' ), floor( $ago / 60 ) );
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)

2017-05-17 08:47 UTC, WikiaTech commented
SonarQube analysis reported 188 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 135 major
* ![MINOR][MINOR] 13 minor
* ![INFO][INFO] 39 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [GlobalFunctions.php#L52](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/includes/wikia/GlobalFunctions.php#L52): Only the first line of this 2-line block will be executed conditionally. The rest will execute unconditionally. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS2681)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L21](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L21): Remove this unused "$wgLang" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L21](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L21): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L100](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L100): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L104](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L104): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L107](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L107): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L110](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L110): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L113](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L113): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L120](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L120): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [ThemeDesignerController.class.php#L126](https://github.com/Wikia/app/blob/040f1348b277d131ce5175d8492cff3346125b28/extensions/wikia/ThemeDesigner/ThemeDesignerController.class.php#L126): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'