ADEN-5104 add src=premium for slots on pages with premium videos
Wikia/app pull request #12881
Opened 2017-05-08 15:49 UTC by dianafa

2017-05-08 15:49 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L18](https://github.com/Wikia/app/blob/1f10589ea547b9e1fa634040e38050d8c4e7d49d/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L18): Function has 14 parameters which is greater than 4 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L57](https://github.com/Wikia/app/blob/1f10589ea547b9e1fa634040e38050d8c4e7d49d/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L57): Function has a complexity of 17 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-05-09 08:21 UTC, fraszczakszymon approved these changes

2017-05-09 08:26 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/js/provider/gpt/helper.js
> +				slotTargetingData.src = 'premium';
What about evolve/turtle providers?

2017-05-09 08:27 UTC, fraszczakszymon requested changes
What about evolve/turtle providers?

2017-05-09 14:40 UTC, v3rth reviewed
LGTM

2017-05-09 14:42 UTC, fraszczakszymon approved these changes

2017-05-10 09:41 UTC, merged