XW-3296 | new dropdowns
Wikia/app pull request #12965
Opened 2017-05-23 11:23 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-3296

@Wikia/x-wing

2017-05-23 11:24 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/643089434cbb71ad82dd9b75571589c3bc837da5/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/643089434cbb71ad82dd9b75571589c3bc837da5/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-23 12:58 UTC, rybmat requested changes

2017-05-23 12:58 UTC, rybmat commented on extensions/wikia/DesignSystem/bower.json
> +    "design-system": "Wikia/design-system#XW-3296"
remember to change it to latest release

2017-05-23 15:27 UTC, weronika requested changes

2017-05-23 15:27 UTC, weronika commented on extensions/wikia/DesignSystem/styles/GlobalNavigationNotifications.scss
> +	border-radius: 4px;
wds variable should be used here

2017-05-23 21:24 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/3a5424ee9fc52ff1034def85d66f531863df9d6c/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/3a5424ee9fc52ff1034def85d66f531863df9d6c/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-23 21:25 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/08c5b4275256c37ab0484546d384840aa6946a33/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/08c5b4275256c37ab0484546d384840aa6946a33/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-24 08:21 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/1307da480d4eca7a2f738d08293954f33daa7c05/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/1307da480d4eca7a2f738d08293954f33daa7c05/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-24 09:01 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/d063e81c778da0600d7008a87f04433eb31c4f3a/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/d063e81c778da0600d7008a87f04433eb31c4f3a/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-24 09:44 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/7f2a71622fe7daff0d882977b03eb5bd4c81a1a5/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/7f2a71622fe7daff0d882977b03eb5bd4c81a1a5/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-24 10:10 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/f455b96dad80548ef5e935255bd1cf6dbfd4d4db/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/f455b96dad80548ef5e935255bd1cf6dbfd4d4db/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-24 10:39 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/1787b0208baf52fa8227456a8da20fe5a3673e42/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/1787b0208baf52fa8227456a8da20fe5a3673e42/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-24 11:24 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/10b57168a6b9966f0782234a3c817f81ee65636b/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/10b57168a6b9966f0782234a3c817f81ee65636b/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-24 12:29 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/8e85f409cae4c8129e813b43fec70d198d960151/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/8e85f409cae4c8129e813b43fec70d198d960151/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-24 13:57 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/50aab3c4f788692a6e96c76c1cbc0fd39cb7a71a/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/50aab3c4f788692a6e96c76c1cbc0fd39cb7a71a/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-25 08:52 UTC, hakubo commented on extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js
> +					.on('mouseenter', this.proxy(this.updateCounts))
good catch!

2017-05-25 08:52 UTC, hakubo approved these changes

2017-05-25 10:58 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/72a1614ac66cfa5255d6c61c9f9d99222efd0848/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/72a1614ac66cfa5255d6c61c9f9d99222efd0848/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-25 11:00 UTC, hakubo commented on extensions/wikia/DesignSystem/scripts/DesignSystemDropdowns.js
> +			.on('touchstart', '.wds-dropdown', function (e) {
please call it 'event' for readability

2017-05-25 11:53 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/da5b381ea09e65769058f5650ff69b0253cced6b/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/da5b381ea09e65769058f5650ff69b0253cced6b/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-30 08:16 UTC, WikiaTech commented
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/36faf68b39d35e80ed7eb3094c2f1299e31e2cb1/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/36faf68b39d35e80ed7eb3094c2f1299e31e2cb1/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-30 22:06 UTC, merged