SUS-2183: Refactor CNW user and request validation logic
Wikia/app pull request #13010
Opened 2017-05-30 12:44 UTC by TK-999

- extracted validation logic to separate validators
- extracted message and http status info to validation exceptions
- centralized error handling
- unit tests
- fix for https://wikia-inc.atlassian.net/browse/SUS-352

https://wikia-inc.atlassian.net/browse/SUS-2183

2017-05-30 12:44 UTC, WikiaTech commented on extensions/wikia/CreateNewWiki/classes/validation/RequestValidator.php
> +			empty( $params ) ||
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1067)

2017-05-30 12:44 UTC, WikiaTech commented
SonarQube analysis reported 9 issues
* ![MAJOR][MAJOR] 8 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/d67ed2219d5f12cfb2adfa6ad13e1f93cdaa5211/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/d67ed2219d5f12cfb2adfa6ad13e1f93cdaa5211/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L42](https://github.com/Wikia/app/blob/d67ed2219d5f12cfb2adfa6ad13e1f93cdaa5211/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L42): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L60](https://github.com/Wikia/app/blob/d67ed2219d5f12cfb2adfa6ad13e1f93cdaa5211/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L60): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L79](https://github.com/Wikia/app/blob/d67ed2219d5f12cfb2adfa6ad13e1f93cdaa5211/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L79): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L195](https://github.com/Wikia/app/blob/d67ed2219d5f12cfb2adfa6ad13e1f93cdaa5211/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L331](https://github.com/Wikia/app/blob/d67ed2219d5f12cfb2adfa6ad13e1f93cdaa5211/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L331): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [CreateNewWikiController.class.php#L74](https://github.com/Wikia/app/blob/d67ed2219d5f12cfb2adfa6ad13e1f93cdaa5211/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L74): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-30 18:02 UTC, WikiaTech commented
SonarQube analysis reported 9 issues
* ![MAJOR][MAJOR] 8 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/cfbb7c92b26f33680325c03223ac183477c178a8/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/cfbb7c92b26f33680325c03223ac183477c178a8/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L42](https://github.com/Wikia/app/blob/cfbb7c92b26f33680325c03223ac183477c178a8/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L42): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L60](https://github.com/Wikia/app/blob/cfbb7c92b26f33680325c03223ac183477c178a8/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L60): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L79](https://github.com/Wikia/app/blob/cfbb7c92b26f33680325c03223ac183477c178a8/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L79): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L195](https://github.com/Wikia/app/blob/cfbb7c92b26f33680325c03223ac183477c178a8/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L339](https://github.com/Wikia/app/blob/cfbb7c92b26f33680325c03223ac183477c178a8/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L339): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [CreateNewWikiController.class.php#L74](https://github.com/Wikia/app/blob/cfbb7c92b26f33680325c03223ac183477c178a8/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L74): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-30 18:06 UTC, WikiaTech commented
SonarQube analysis reported 9 issues
* ![MAJOR][MAJOR] 8 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/db6093c2711f5f5f26cff50e4e04cd208c2c5948/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/db6093c2711f5f5f26cff50e4e04cd208c2c5948/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L42](https://github.com/Wikia/app/blob/db6093c2711f5f5f26cff50e4e04cd208c2c5948/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L42): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L60](https://github.com/Wikia/app/blob/db6093c2711f5f5f26cff50e4e04cd208c2c5948/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L60): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L79](https://github.com/Wikia/app/blob/db6093c2711f5f5f26cff50e4e04cd208c2c5948/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L79): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L195](https://github.com/Wikia/app/blob/db6093c2711f5f5f26cff50e4e04cd208c2c5948/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L339](https://github.com/Wikia/app/blob/db6093c2711f5f5f26cff50e4e04cd208c2c5948/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L339): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [CreateNewWikiController.class.php#L74](https://github.com/Wikia/app/blob/db6093c2711f5f5f26cff50e4e04cd208c2c5948/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L74): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-30 18:09 UTC, WikiaTech commented
SonarQube analysis reported 9 issues
* ![MAJOR][MAJOR] 8 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/74d32db5b6279b751da6ed5b4f71c5a87534ec26/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/74d32db5b6279b751da6ed5b4f71c5a87534ec26/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L42](https://github.com/Wikia/app/blob/74d32db5b6279b751da6ed5b4f71c5a87534ec26/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L42): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L60](https://github.com/Wikia/app/blob/74d32db5b6279b751da6ed5b4f71c5a87534ec26/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L60): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L79](https://github.com/Wikia/app/blob/74d32db5b6279b751da6ed5b4f71c5a87534ec26/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L79): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L195](https://github.com/Wikia/app/blob/74d32db5b6279b751da6ed5b4f71c5a87534ec26/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L339](https://github.com/Wikia/app/blob/74d32db5b6279b751da6ed5b4f71c5a87534ec26/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L339): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [CreateNewWikiController.class.php#L74](https://github.com/Wikia/app/blob/74d32db5b6279b751da6ed5b4f71c5a87534ec26/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L74): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-01 08:05 UTC, macbre commented on extensions/wikia/CreateNewWiki/classes/validation/RateLimitedException.php
> +	protected $httpStatusCode = 429;
:+1: `RFC 6585` says thank you :)

2017-06-01 08:09 UTC, macbre approved these changes

2017-06-01 09:32 UTC, WikiaTech commented
SonarQube analysis reported 10 issues
* ![MAJOR][MAJOR] 9 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L42](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L42): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L60](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L60): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L79](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L79): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L195](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L316](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L316): Remove this unused "$wgUser" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L340](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L340): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [CreateNewWikiController.class.php#L74](https://github.com/Wikia/app/blob/3075d605e045a9307672e7191796ea269d89f1a9/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L74): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-01 13:33 UTC, WikiaTech commented
SonarQube analysis reported 9 issues
* ![MAJOR][MAJOR] 8 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/c69db780ce203063bbb83d315aef224de08da97c/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/c69db780ce203063bbb83d315aef224de08da97c/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L42](https://github.com/Wikia/app/blob/c69db780ce203063bbb83d315aef224de08da97c/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L42): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L60](https://github.com/Wikia/app/blob/c69db780ce203063bbb83d315aef224de08da97c/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L60): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L79](https://github.com/Wikia/app/blob/c69db780ce203063bbb83d315aef224de08da97c/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L79): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L195](https://github.com/Wikia/app/blob/c69db780ce203063bbb83d315aef224de08da97c/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L340](https://github.com/Wikia/app/blob/c69db780ce203063bbb83d315aef224de08da97c/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L340): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [CreateNewWikiController.class.php#L74](https://github.com/Wikia/app/blob/c69db780ce203063bbb83d315aef224de08da97c/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L74): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-01 13:38 UTC, WikiaTech commented
SonarQube analysis reported 9 issues
* ![MAJOR][MAJOR] 8 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/4e30a70cb0937a60614fa575d76c421c6696f65a/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/4e30a70cb0937a60614fa575d76c421c6696f65a/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L42](https://github.com/Wikia/app/blob/4e30a70cb0937a60614fa575d76c421c6696f65a/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L42): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L60](https://github.com/Wikia/app/blob/4e30a70cb0937a60614fa575d76c421c6696f65a/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L60): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L79](https://github.com/Wikia/app/blob/4e30a70cb0937a60614fa575d76c421c6696f65a/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L79): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L195](https://github.com/Wikia/app/blob/4e30a70cb0937a60614fa575d76c421c6696f65a/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L340](https://github.com/Wikia/app/blob/4e30a70cb0937a60614fa575d76c421c6696f65a/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L340): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [CreateNewWikiController.class.php#L74](https://github.com/Wikia/app/blob/4e30a70cb0937a60614fa575d76c421c6696f65a/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L74): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-01 13:44 UTC, WikiaTech commented
SonarQube analysis reported 9 issues
* ![MAJOR][MAJOR] 8 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/a2a3a80330e29290877c1965e0cb4454835453f6/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L30](https://github.com/Wikia/app/blob/a2a3a80330e29290877c1965e0cb4454835453f6/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L30): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L42](https://github.com/Wikia/app/blob/a2a3a80330e29290877c1965e0cb4454835453f6/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L42): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L60](https://github.com/Wikia/app/blob/a2a3a80330e29290877c1965e0cb4454835453f6/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L60): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L79](https://github.com/Wikia/app/blob/a2a3a80330e29290877c1965e0cb4454835453f6/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L79): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L195](https://github.com/Wikia/app/blob/a2a3a80330e29290877c1965e0cb4454835453f6/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateNewWikiController.class.php#L340](https://github.com/Wikia/app/blob/a2a3a80330e29290877c1965e0cb4454835453f6/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L340): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [CreateNewWikiController.class.php#L74](https://github.com/Wikia/app/blob/a2a3a80330e29290877c1965e0cb4454835453f6/extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php#L74): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-05 08:11 UTC, ghost requested changes

2017-06-05 08:11 UTC, mixth-sense commented on extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
> +			$params['wAllAges'] = null;
Be aware of our changes related to wikis targeted to children. The checkbox is now enabled for all languages. Check with the `dev` branch please.

2017-06-26 14:15 UTC, closed without merging