add support for namespaces to WikiaView
Wikia/app pull request #13015
Opened 2017-05-31 07:50 UTC by hakubo

This PR adds support for namespaces to WikiaView, so we can have nirvana controllers also inside namespaces. Template path should still be build based on class name but without namespace.

Example:
$this->renderView('PageHeader/PageHeader', 'index');

Alternative idea:
add a param to renderView - $namespace, so we could generate paths correctly
this would unnecessarily increase learning curve of how to render view in nirvana

Current approach mimics how you would use a class inside a namespace in PHP
but allows to have all templates inside ClassName/templates, folder

2017-05-31 07:51 UTC, WikiaTech commented
SonarQube analysis reported 8 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WikiaView.class.php#L161](https://github.com/Wikia/app/blob/2f44ceca9fd6f491cb1d5d8e888cdbda8a438a58/includes/wikia/nirvana/WikiaView.class.php#L161): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L274](https://github.com/Wikia/app/blob/2f44ceca9fd6f491cb1d5d8e888cdbda8a438a58/includes/wikia/nirvana/WikiaView.class.php#L274): Add curly braces around the nested statement(s). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L275](https://github.com/Wikia/app/blob/2f44ceca9fd6f491cb1d5d8e888cdbda8a438a58/includes/wikia/nirvana/WikiaView.class.php#L275): Add curly braces around the nested statement(s). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L313](https://github.com/Wikia/app/blob/2f44ceca9fd6f491cb1d5d8e888cdbda8a438a58/includes/wikia/nirvana/WikiaView.class.php#L313): Remove the code after this "return". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1763)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L316](https://github.com/Wikia/app/blob/2f44ceca9fd6f491cb1d5d8e888cdbda8a438a58/includes/wikia/nirvana/WikiaView.class.php#L316): Reduce this "switch/case" number of lines from 21 to at most 10, for example by extracting code into function. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1151)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L335](https://github.com/Wikia/app/blob/2f44ceca9fd6f491cb1d5d8e888cdbda8a438a58/includes/wikia/nirvana/WikiaView.class.php#L335): Remove the code after this "return". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1763)
1. ![MINOR][MINOR] [WikiaView.class.php#L274](https://github.com/Wikia/app/blob/2f44ceca9fd6f491cb1d5d8e888cdbda8a438a58/includes/wikia/nirvana/WikiaView.class.php#L274): 2 statements were found on this line. Reformat the code to have only one statement per line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS122)
1. ![MINOR][MINOR] [WikiaView.class.php#L275](https://github.com/Wikia/app/blob/2f44ceca9fd6f491cb1d5d8e888cdbda8a438a58/includes/wikia/nirvana/WikiaView.class.php#L275): 2 statements were found on this line. Reformat the code to have only one statement per line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS122)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-31 07:53 UTC, WikiaTech commented
SonarQube analysis reported 8 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WikiaView.class.php#L161](https://github.com/Wikia/app/blob/a30164381b15bd810dafda137c72ef43a11e7aa4/includes/wikia/nirvana/WikiaView.class.php#L161): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L281](https://github.com/Wikia/app/blob/a30164381b15bd810dafda137c72ef43a11e7aa4/includes/wikia/nirvana/WikiaView.class.php#L281): Add curly braces around the nested statement(s). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L282](https://github.com/Wikia/app/blob/a30164381b15bd810dafda137c72ef43a11e7aa4/includes/wikia/nirvana/WikiaView.class.php#L282): Add curly braces around the nested statement(s). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L320](https://github.com/Wikia/app/blob/a30164381b15bd810dafda137c72ef43a11e7aa4/includes/wikia/nirvana/WikiaView.class.php#L320): Remove the code after this "return". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1763)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L323](https://github.com/Wikia/app/blob/a30164381b15bd810dafda137c72ef43a11e7aa4/includes/wikia/nirvana/WikiaView.class.php#L323): Reduce this "switch/case" number of lines from 21 to at most 10, for example by extracting code into function. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1151)
1. ![MAJOR][MAJOR] [WikiaView.class.php#L342](https://github.com/Wikia/app/blob/a30164381b15bd810dafda137c72ef43a11e7aa4/includes/wikia/nirvana/WikiaView.class.php#L342): Remove the code after this "return". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1763)
1. ![MINOR][MINOR] [WikiaView.class.php#L281](https://github.com/Wikia/app/blob/a30164381b15bd810dafda137c72ef43a11e7aa4/includes/wikia/nirvana/WikiaView.class.php#L281): 2 statements were found on this line. Reformat the code to have only one statement per line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS122)
1. ![MINOR][MINOR] [WikiaView.class.php#L282](https://github.com/Wikia/app/blob/a30164381b15bd810dafda137c72ef43a11e7aa4/includes/wikia/nirvana/WikiaView.class.php#L282): 2 statements were found on this line. Reformat the code to have only one statement per line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS122)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-31 08:07 UTC, WikiaTech commented on includes/wikia/nirvana/WikiaView.class.php
>  			default:
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce this "switch/case" number of lines from 20 to at most 10, for example by extracting code into function. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1151)

2017-05-31 08:07 UTC, WikiaTech commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-31 08:17 UTC, rogatty approved these changes
I worry that forcing the types might break some old code where the methods were used incorrectly. It should be caught by the tests, though. And it's better to fail loudly than do weird things silently, right? :wink:

2017-05-31 08:22 UTC, latata approved these changes

2017-05-31 08:53 UTC, kvas-damian commented on includes/wikia/nirvana/WikiaView.class.php
> +	private function getTemplateOptions( string $controllerClassWithNamespace, string $methodName, $controllerBaseName = null ): array {
Can we add some unit tests covering this change?

2017-05-31 08:57 UTC, macbre commented
Please update `WikiaViewTest` to cover new use case.

2017-05-31 09:07 UTC, TK-999 commented on includes/wikia/nirvana/WikiaView.class.php
> +			if ($this->response == null) {
Spacing

2017-05-31 09:07 UTC, TK-999 commented on includes/wikia/nirvana/WikiaView.class.php
> +				$this->response->setException($e);
Let's add spacing here and use strict equality operator

2017-05-31 09:11 UTC, TK-999 commented on includes/wikia/nirvana/WikiaView.class.php
> +				F::app()->getBaseName( $controllerClass )
Here `$controllerClass` was already passed through `WikiaView::getClassName`, so the namespaces should be gone. Should we pass it again?

2017-05-31 09:11 UTC, mszabo-wikia requested changes

2017-05-31 09:11 UTC, TK-999 commented on includes/wikia/nirvana/WikiaView.class.php
> +	private function getClassName( string $controllerClassWithNamespace ): string {
What if we added this logic to `WikiaApp::getBaseName`? In that case we don't have to modify `WikiaView`.

2017-05-31 09:52 UTC, macbre requested changes
Unit tests, bitte :smile:

2017-05-31 09:57 UTC, hakubo commented on includes/wikia/nirvana/WikiaView.class.php
> +	private function getClassName( string $controllerClassWithNamespace ): string {
then it could not run the class, I need to remove namespace only to build template path

2017-05-31 16:31 UTC, mszabo-wikia approved these changes

2017-06-01 06:48 UTC, kvas-damian approved these changes

2017-06-01 07:54 UTC, macbre approved these changes

2017-06-01 07:55 UTC, macbre commented on includes/wikia/tests/_fixtures/TestATestController.php
> +$wgAutoloadClasses['TestA\AnotherTestController'] = dirname(__FILE__) . '/TestATestController.php';
Let's use `__DIR__` instead

2017-06-01 07:55 UTC, macbre commented on includes/wikia/tests/_fixtures/TestATestBTestController.php
> +$wgAutoloadClasses['TestA\TestB\AnotherTestController'] = dirname(__FILE__) . '/TestATestBTestController.php';
Let's use `__DIR__` instead

2017-06-01 08:15 UTC, merged