SUS-458 | CNW: NS_PROJECT pages are missing on new wikis
Wikia/app pull request #13021
Opened 2017-05-31 13:16 UTC by macbre

Use a proper content language (`$wgContLang`) for a given starter to be able to generate localized namespace names.

Set `$wgMetaNamespace` to properly generate `NS_PROJECT` namespace names:

```xml
    <namespaces>
      <namespace key="-2" case="first-letter">Media</namespace>
      <namespace key="-1" case="first-letter">Speciale</namespace>
      <namespace key="0" case="first-letter" />
      <namespace key="1" case="first-letter">Discussione</namespace>
      <namespace key="2" case="first-letter">Utente</namespace>
      <namespace key="3" case="first-letter">Discussioni utente</namespace>
```

2017-05-31 13:17 UTC, WikiaTech commented
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![INFO][INFO] [dumpStarters.php#L16](https://github.com/Wikia/app/blob/cd586608d97cd8774cf3d4466e967d17fe67422c/extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php#L16): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

2017-05-31 13:20 UTC, WikiaTech commented on extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php
> +putenv( 'SERVER_ID=80433' ); // run in the context of www.wikia.com (where CreateWiki is enabled)
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

2017-05-31 13:20 UTC, WikiaTech commented
SonarQube analysis reported 1 issue
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

2017-05-31 13:49 UTC, ghost requested changes

2017-05-31 13:49 UTC, ghost commented on extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php
> + * Script that prepares XML and SQL dumps with the latest revisions and *links tables rows of starter wikis
`and *links…` - it seems a newline is missing

2017-05-31 13:49 UTC, ghost commented on extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php
> +putenv( 'SERVER_ID=80433' ); // run in the context of www.wikia.com (where CreateWiki is enabled)
Does it make sense to use a named constant here and across all codebase?

2017-05-31 14:09 UTC, macbre commented on extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php
> + * Script that prepares XML and SQL dumps with the latest revisions and *links tables rows of starter wikis
Nope, `*links` refers to `categorylinks`, `externallinks`, ... tables - see `$mTablesToDump` class member below.

2017-05-31 14:10 UTC, macbre commented on extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php
> +putenv( 'SERVER_ID=80433' ); // run in the context of www.wikia.com (where CreateWiki is enabled)
It's actually to early to use constant defined in another file

2017-05-31 14:15 UTC, sqreek approved these changes

2017-05-31 14:25 UTC, WikiaTech commented on extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php
> +putenv( 'SERVER_ID=80433' ); // run in the context of www.wikia.com (where CreateWiki is enabled)
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

2017-05-31 14:25 UTC, WikiaTech commented
SonarQube analysis reported 1 issue
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

2017-06-01 12:01 UTC, mszabo-wikia approved these changes

2017-06-02 07:46 UTC, WikiaTech commented on extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php
> +putenv( 'SERVER_ID=80433' ); // run in the context of www.wikia.com (where CreateWiki is enabled)
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

2017-06-02 07:46 UTC, WikiaTech commented
SonarQube analysis reported 1 issue
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

2017-06-02 07:53 UTC, merged