XW-3318 | new local nav preview
Wikia/app pull request #13026
Opened 2017-05-31 15:54 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-3318

@Wikia/x-wing

2017-05-31 15:55 UTC, WikiaTech commented on includes/wikia/models/NavigationModel.class.php
>  	 * TODO we should refactor whole model when we remove Oasis
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Complete the task associated to this "TODO" comment. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1135)

2017-05-31 15:55 UTC, WikiaTech commented
SonarQube analysis reported 22 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/dcbb7ce0e0bb147cf38c85f41edc649b137c740d/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-31 16:06 UTC, rogatty commented on extensions/wikia/CommunityHeader/CommunityHeaderHooks.class.php
> +						[ 'wikiText' => $wikitext ] );
This is a strange way to format the code :thinking:

2017-06-01 04:50 UTC, hakubo commented on includes/wikia/models/NavigationModel.class.php
>  	 * TODO we should refactor whole model when we remove Oasis
whoa! 
TODO we should refactor whole model when we remove Oasis

2017-06-01 07:36 UTC, hakubo requested changes

2017-06-01 07:36 UTC, hakubo commented on extensions/wikia/CommunityHeader/CommunityHeaderHooks.class.php
> +			$html = str_replace( '<a ', '<a target="_blank" ', $html );
maybe a parameter to localNavigation preview - to already generate links with target?

2017-06-01 07:36 UTC, hakubo commented on includes/wikia/models/NavigationModel.class.php
> +	public function getTreeFromText( $wikiText ) {
types

2017-06-01 07:38 UTC, hakubo commented on extensions/wikia/CommunityHeader/CommunityHeaderHooks.class.php
> +	public static function onEditPageLayoutModifyPreview( Title $title, &$html, $wikitext ) {
missing types

2017-06-01 08:44 UTC, rogatty commented on extensions/wikia/CommunityHeader/styles/index.scss
> +.wds-local-navigation-preview {
It's not a DS class, so I would remove the `wds-` prefix.

2017-06-01 08:45 UTC, rogatty commented on extensions/wikia/CommunityHeader/styles/index.scss
> +	// this is max width of local navigation allowed
It's probably defined somewhere in the JS too, right? Let's add a comment where it is.

2017-06-01 08:45 UTC, rogatty commented on extensions/wikia/CommunityHeader/templates/CommunityHeader_localNavigationPreview.php
> +		[ 'wikiText' => $wikiText ] ); ?>
Strange line break.

2017-06-01 08:51 UTC, rogatty commented on includes/wikia/models/NavigationModel.class.php
>  	 * TODO we should refactor whole model when we remove Oasis
@kvas-damian was such an optimist, back in the day (https://github.com/Wikia/app/commit/e431ee3c1d691a99dcd556cd248670aa55613a01#diff-f5c754c2b758d753c95dbffc34b8f45cR193) :smile:

2017-06-01 08:56 UTC, rogatty commented on includes/wikia/models/NavigationModel.class.php
> +		$this->menuNodes = $this->parseText( $wikiText, [
How did it work before? Did we leave the old code somewhere?

2017-06-01 08:56 UTC, kvas-damian commented on includes/wikia/models/NavigationModel.class.php
>  	 * TODO we should refactor whole model when we remove Oasis
;)

2017-06-01 09:15 UTC, rogatty commented on skins/oasis/js/WikiHeader.js
>  			firstMenuValidator: function () {
You're going to like this :smiling_imp: 
How about extracting all of the preview logic to a separate file in `PageHeader` extension? `WikiHeader.js` will be removed during the clean up, anyway.

2017-06-01 09:19 UTC, rogatty commented on skins/oasis/js/WikiHeader.js
> -			secondMenuValidator: function () {
@latata why do we not want to validate the second level anymore?

2017-06-01 13:51 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/cd9dff078abd67927d55bae3c71648877f64dbd1/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-01 13:51 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/42fd7145042227b97b4974807db43185ec20567f/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-01 13:54 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/dbfc1bd5298d0833be4cc14b68513ba21cc2e696/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-01 14:06 UTC, rogatty approved these changes

2017-06-01 15:51 UTC, hakubo commented on extensions/wikia/CommunityHeader/scripts/local-navigation-preview.js
> +						if ($(this).attr('href') === '#') {
`this.href`

2017-06-01 15:55 UTC, hakubo approved these changes

2017-06-02 13:19 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/50e1754b216396ec36c3c7359d20d40d2defc0c5/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-02 13:21 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/592e0ea5f7c2945e8d91f3c33b4b03cb0cd7cc7f/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-05 08:50 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/f34945d68e92ec1b0ef34a0cc9cf7b61d6ede718/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-05 20:40 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/ce0351003bd0694990654f2bfeecd34c1444748f/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-05 20:56 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/a6b2e134682f996b12163a366f0ae47c0aad8221/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-06 12:29 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/cd416c083245e591d228bd6e88ad7be4c5383680/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-06 12:36 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/af8ba6f4b5c4bc96ee306354b6c49f9d71c8fdf4/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-06 12:53 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/0dcbdb443660a4c46070de282dd7b580ee275c08/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-06 14:05 UTC, ludwikkazmierczak commented
Tested and Accepted

2017-06-06 14:05 UTC, WikiaTech commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 18 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [preview.js#L14](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/extensions/wikia/EditPreview/js/preview.js#L14): Function has 9 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [preview.js#L48](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/extensions/wikia/EditPreview/js/preview.js#L48): Remove the declaration of the unused 'modalHeightModifier' variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [Oasis_setup.php#L50](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/extensions/wikia/Oasis/Oasis_setup.php#L50): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L8](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/includes/wikia/models/NavigationModel.class.php#L8): Class "NavigationModel" has 21 methods, which is greater than 20 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L86](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/includes/wikia/models/NavigationModel.class.php#L86): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L116](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/includes/wikia/models/NavigationModel.class.php#L116): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L141](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/includes/wikia/models/NavigationModel.class.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L430](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/includes/wikia/models/NavigationModel.class.php#L430): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/includes/wikia/models/NavigationModel.class.php#L443): Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [NavigationModel.class.php#L443](https://github.com/Wikia/app/blob/d6c36068b04735819dedab223d93e093e81b5711/includes/wikia/models/NavigationModel.class.php#L443): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-06 14:23 UTC, merged