SUS-1182 | SpecialCreateNewWiki: check if user has confirmed his email
Wikia/app pull request #13034
Opened 2017-06-01 14:34 UTC by macbre

https://wikia-inc.atlassian.net/browse/SUS-1182

2017-06-01 14:35 UTC, WikiaTech commented on extensions/wikia/CreateNewWiki/SpecialCreateNewWiki.class.php
> +		$out->setPageTitle(wfMsg('cnw-title'));
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)

2017-06-01 14:35 UTC, WikiaTech commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-01 14:54 UTC, mszabo-wikia requested changes

2017-06-01 14:54 UTC, TK-999 commented on extensions/wikia/CreateNewWiki/SpecialCreateNewWiki.class.php
> +		$out->setPageTitle( wfMessage( 'cnw-title' ) );
We could actually use `$this->msg()` here.

2017-06-02 08:44 UTC, macbre commented on extensions/wikia/CreateNewWiki/SpecialCreateNewWiki.class.php
> +		$out->setPageTitle( wfMessage( 'cnw-title' ) );
`setPageTitle` method allows `Message` instance to be passed.

2017-06-02 08:45 UTC, merged