SER-986 | make username with semicolon invalid
Wikia/app pull request #13096
Opened 2017-06-09 12:13 UTC by idradm

@mixth-sense @macbre @Wikia/platform-team 

Is this a safe change?

2017-06-09 12:13 UTC, WikiaTech commented on includes/User.php
>  		if ( $name == ''
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1067)

2017-06-09 12:13 UTC, WikiaTech commented
SonarQube analysis reported 115 issues
* ![MAJOR][MAJOR] 66 major
* ![MINOR][MINOR] 7 minor
* ![INFO][INFO] 42 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [UserSignupTest.php#L107](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L107): This function "signupDataProvider" has 205 lines, which is greater than the 150 lines authorized. Split it into smaller functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS138)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L440](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L440): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L484](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L484): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L494](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L494): This function has 14 parameters, which is greater than the 7 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L546](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L546): This function "sendConfirmationEmailDataProvider" has 280 lines, which is greater than the 150 lines authorized. Split it into smaller functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS138)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L625](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L625): Remove this unused "$mockMessagesMap101" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L630](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L630): Remove this unused "$expMsg101" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L638](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L638): Remove this unused "$mockMessagesMap102" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L643](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/extensions/wikia/UserLogin/tests/UserSignupTest.php#L643): Remove this unused "$expMsg102" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [User.php](https://github.com/Wikia/app/blob/cf3c954ab6868c5be1317e5dabafa7eef1428bba/includes/User.php): File "User.php" has 4703 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-09 12:20 UTC, onei commented
@idradm just passing by, but do you mean ; instead of : (semicolon instead of colon) or vice versa?

2017-06-09 12:56 UTC, idradm commented
The char is fine, the name is wrong. ;)

2017-06-12 08:58 UTC, pwojcik86 requested changes

2017-06-12 08:58 UTC, pwojcik86 commented on extensions/wikia/UserLogin/tests/UserSignupTest.php
> +				'error - invalid user name with semicolon' =>
it should be "colon"

2017-06-12 08:58 UTC, pwojcik86 commented on includes/User.php
> +			|| strpos( $name, ':') !== false
The debug message below needs to be updated

2017-06-12 09:57 UTC, WikiaTech commented
SonarQube analysis reported 115 issues
* ![MAJOR][MAJOR] 66 major
* ![MINOR][MINOR] 7 minor
* ![INFO][INFO] 42 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [UserSignupTest.php#L107](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L107): This function "signupDataProvider" has 205 lines, which is greater than the 150 lines authorized. Split it into smaller functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS138)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L440](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L440): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L484](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L484): Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L494](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L494): This function has 14 parameters, which is greater than the 7 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L546](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L546): This function "sendConfirmationEmailDataProvider" has 280 lines, which is greater than the 150 lines authorized. Split it into smaller functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS138)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L625](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L625): Remove this unused "$mockMessagesMap101" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L630](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L630): Remove this unused "$expMsg101" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L638](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L638): Remove this unused "$mockMessagesMap102" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [UserSignupTest.php#L643](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/extensions/wikia/UserLogin/tests/UserSignupTest.php#L643): Remove this unused "$expMsg102" local variable. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [User.php](https://github.com/Wikia/app/blob/b7fc07c0f644e353858310813be3843e18c5782e/includes/User.php): File "User.php" has 4703 lines, which is greater than 1000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-12 09:59 UTC, pwojcik86 approved these changes

2017-06-12 14:08 UTC, merged