ADEN-5326 add outstream param
Wikia/app pull request #13106
Opened 2017-06-12 09:49 UTC by dianafa

https://wikia-inc.atlassian.net/browse/ADEN-5326

2017-06-12 11:14 UTC, kvas-damian commented on extensions/wikia/AdEngine/js/slot/slotTargeting.js
> +		var getVideoTargeting = prebid.get().getAdserverTargetingForAdUnitCode,
I'm not sure how this method is related to video. Can we rename this method?

2017-06-12 11:15 UTC, kvas-damian commented on extensions/wikia/AdEngine/js/slot/slotTargeting.js
> +			videoTargeting = getVideoTargeting && getVideoTargeting('INCONTENT_PLAYER');
Is it ok that we limit only to this slot? Video is also displayed in TLM and MIC

2017-06-12 13:58 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/slot/slotTargeting.js
> +], function (adContext, math, prebid, abTest, instantGlobals) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Function has 5 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2017-06-12 13:58 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/436b1ba5bd4c7f390f86a7ee3026df2234425874/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/436b1ba5bd4c7f390f86a7ee3026df2234425874/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-12 14:36 UTC, nandy-andy commented on extensions/wikia/AdEngine/js/slot/slotTargeting.js
> +			videoTargeting = getAdserverTargeting && getAdserverTargeting(videoSlots[context.targeting.skin]);
In Oasis `context.targeting.skin` should be always available: https://github.com/Wikia/app/blob/258cf92130916a8d3b6cf5e25177f1ed11c43b13/includes/Skin.php#L25

Mobile-wiki loads our [adsContext.js](https://github.com/Wikia/mobile-wiki/blob/542a1b700f35303e47fdd70ec74e82bb5c8895ca/app/modules/ads.js#L337) which depends on global ads object which in Oasis is set by the [AdContextService](https://github.com/Wikia/app/blob/dev/extensions/wikia/AdEngine/AdEngine2ContextService.class.php#L68) which uses the skin property linked above. But in mobile-wiki it's set by [Mercury API](https://github.com/Wikia/app/blob/147eb410f3127bc5112324f7fe7c79ec6471bd32/extensions/wikia/MercuryApi/MercuryApiController.class.php#L224) which means we're safe as well, aren't we? :japanese_ogre:

2017-06-12 14:38 UTC, nandy-andy approved these changes

2017-06-12 14:55 UTC, kvas-damian commented on extensions/wikia/AdEngine/js/slot/slotTargeting.js
> +			videoTargeting = getAdserverTargeting && getAdserverTargeting(videoSlots[context.targeting.skin]);
Please fix indentation :)

2017-06-13 09:16 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/80ec4f3edad94a15c09bf472fcae8811c708e2d0/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/80ec4f3edad94a15c09bf472fcae8811c708e2d0/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-13 09:45 UTC, v3rth requested changes

2017-06-13 09:45 UTC, v3rth commented on extensions/wikia/AdEngine/js/slot/slotTargeting.js
> +            getAdserverTargeting = prebid.get().getAdserverTargetingForAdUnitCode,
Some indentations problem here :( it looks like spaces, not tabs

2017-06-13 09:45 UTC, v3rth commented on extensions/wikia/AdEngine/js/slot/slotTargeting.js
> +				return bidderName.substr(0, 2) + math.leftPad(parseFloat(videoTargeting.hb_pb) * 100, 4);
Try to hide that behind some nice looking function

2017-06-13 09:45 UTC, v3rth commented on extensions/wikia/AdEngine/js/spec/slot/slotTargeting.spec.js
> +                {
Spaces here, again :(

2017-06-13 09:52 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/46ac91cdf18ea3f94037f1ad85041b5639efe125/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/46ac91cdf18ea3f94037f1ad85041b5639efe125/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-13 09:54 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/89b1aad1732f012a346650fc707e9586e485ab46/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/89b1aad1732f012a346650fc707e9586e485ab46/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-13 09:54 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/502298bae37a21d1f1103f8b817ec887dd3cb79c/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/502298bae37a21d1f1103f8b817ec887dd3cb79c/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-13 09:56 UTC, v3rth approved these changes

2017-06-13 14:37 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/2ae74914493987010bc756ce95e24025d46d658b/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/2ae74914493987010bc756ce95e24025d46d658b/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-13 15:26 UTC, v3rth approved these changes

2017-06-14 12:55 UTC, WikiaTech commented on extensions/wikia/AdEngine/js/slot/slotTargeting.js
> +], function (adContext, math, abTest, instantGlobals, prebid) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Function has 5 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

2017-06-14 12:55 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/19b8930c8980f8c7d9f7d61a7413301b58e725c2/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/19b8930c8980f8c7d9f7d61a7413301b58e725c2/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-14 12:57 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/5d88a2bde83bb772f91ca3c16a17cbec227cb3e5/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/5d88a2bde83bb772f91ca3c16a17cbec227cb3e5/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-14 12:58 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [helper.js#L19](https://github.com/Wikia/app/blob/f53dd81a2485829d5f2553eb27347c429439b7b0/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L19): Function has 15 parameters which is greater than 4 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)
1. ![MAJOR][MAJOR] [helper.js#L59](https://github.com/Wikia/app/blob/f53dd81a2485829d5f2553eb27347c429439b7b0/extensions/wikia/AdEngine/js/provider/gpt/helper.js#L59): Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-06-14 13:34 UTC, bulaszenko approved these changes

2017-06-14 13:53 UTC, merged