SUS-2200 in rename user tool use rollup_wiki_user_event instead rollup_edit_events
Wikia/app pull request #13130
Opened 2017-06-14 16:44 UTC by sqreek

https://wikia-inc.atlassian.net/browse/SUS-2200

@mixth-sense @macbre

2017-06-14 16:45 UTC, WikiaTech commented on extensions/wikia/UserRenameTool/RenameUserHelper.class.php
>  		if ( empty( $wgDevelEnvironment ) ) { // on production
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

2017-06-14 16:45 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![INFO][INFO] [RenameUserHelper.class.php#L51](https://github.com/Wikia/app/blob/18f29e003dd1185e0f91717f0e4079605a387c16/extensions/wikia/UserRenameTool/RenameUserHelper.class.php#L51): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [RenameUserHelper.class.php#L101](https://github.com/Wikia/app/blob/18f29e003dd1185e0f91717f0e4079605a387c16/extensions/wikia/UserRenameTool/RenameUserHelper.class.php#L101): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

2017-06-14 18:04 UTC, macbre approved these changes

2017-06-19 08:41 UTC, ghost requested changes
Per my comment on the JIRA case, let's use `stats.events` so that there is no delay.

2017-06-19 10:39 UTC, WikiaTech commented
SonarQube analysis reported 3 issues
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![INFO][INFO] [RenameUserHelper.class.php#L51](https://github.com/Wikia/app/blob/6a710df757ab2c1df88d4030fd9efa4f70cd93f9/extensions/wikia/UserRenameTool/RenameUserHelper.class.php#L51): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [RenameUserHelper.class.php#L101](https://github.com/Wikia/app/blob/6a710df757ab2c1df88d4030fd9efa4f70cd93f9/extensions/wikia/UserRenameTool/RenameUserHelper.class.php#L101): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

2017-06-19 12:18 UTC, ghost approved these changes

2017-06-20 09:27 UTC, merged