XW-3600 | sitename link length fix - DS update
Wikia/app pull request #13147
Opened 2017-06-20 10:29 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-3600
@Wikia/x-wing

2017-06-21 09:37 UTC, rogatty approved these changes

2017-06-26 08:23 UTC, rybmat requested changes

2017-06-26 08:23 UTC, hakubo approved these changes

2017-06-26 08:23 UTC, rybmat commented on extensions/wikia/DesignSystem/bower.json
> +    "design-system": "Wikia/design-system#XW-3600"
change to release

2017-06-26 10:21 UTC, rybmat approved these changes

2017-06-26 10:21 UTC, merged