SUS-2277 | Sunset extensions/wikia/TextRegex
Wikia/app pull request #13194
Opened 2017-06-29 11:00 UTC by macbre

https://wikia-inc.atlassian.net/browse/SUS-2277

* remove dependency on `TextRegexCore` from CreateNewWiki + simplify the code

2017-06-29 11:00 UTC, WikiaTech commented
SonarQube analysis reported 17 issues
* ![MAJOR][MAJOR] 12 major
* ![MINOR][MINOR] 5 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L36](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L36): Replace or remove this deprecated Wikia::log logging statement. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AWikiaLogUsage)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L65](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L65): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L70](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L70): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L72](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L72): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L74](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L74): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L75](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L75): This branch's code block is the same as the block for the branch on line 73. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1871)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L76](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L76): Replace this legacy wfMsg* function call with one of the new i18n functions. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L106](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L106): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L106](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L106): This branch's code block is the same as the block for the branch on line 103. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1871)
1. ![MAJOR][MAJOR] [CreateWikiChecks.php#L141](https://github.com/Wikia/app/blob/f0450c154aa87d3629a42e1e854fee61454e0111/extensions/wikia/CreateNewWiki/CreateWikiChecks.php#L141): Refactor this code to rely on RequestContext instead of context-dependent globals. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-29 11:55 UTC, macbre commented on extensions/wikia/CreateNewWiki/CreateWikiChecks.php
> -		if ( !class_exists( 'TextRegexCore' ) ) {
This will always be `true` now - TextRegexCore

2017-06-30 15:49 UTC, mszabo-wikia requested changes

2017-06-30 15:49 UTC, TK-999 commented on extensions/wikia/CreateNewWiki/CreateWikiChecks.php
> +		return wfRunHooks( 'CreateWikiChecks::checkBadWords', array( $sText, $where, $split ) );
Let's directly call `Hooks::run` and use short array syntax here.

2017-06-30 15:49 UTC, TK-999 commented on extensions/wikia/CreateNewWiki/CreateWikiChecks.php
>  	public static function checkBadWords( $sText, $where, $split = false ) {
Should we add strict type hinting here?

2017-07-03 09:25 UTC, macbre commented
@TK-999, these are good CR points, but let's focus on sunsets and and make any additional changes around as small as possible.

2017-07-03 09:26 UTC, mszabo-wikia approved these changes

2017-07-03 09:27 UTC, merged