XW-3684 | Fix Ooyala preroll issues
Wikia/app pull request #13246
Opened 2017-07-05 11:29 UTC by rogatty

https://wikia-inc.atlassian.net/browse/XW-3684

- Upgrade Ooyala to v4.14.8
- Custom WikiaAdScreen with video controls
- Special handling for VPAID prerolls
  - Hide full screen toggle, as the tested ad looked broken on fullscreen
  - Hide Ad Time Left, as the tested ad has its own timer

@Wikia/x-wing @Wikia/adeng

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/utils.js
> +        for (var z in uniqueSourceArray) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Restrict what this loop acts on by testing each property. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/utils.js
>        item &&
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/utils.js
> +  arrayDeepMerge: function(target, source, optionsArgument) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Function has a complexity of 16 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/utils.js
> +              if (optionsArgument.buttonArrayFusion === 'prepend' && uniqueSourceArray && uniqueSourceArray.length) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Refactor this code to not nest more than 3 if/for/while/switch/try statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANestedIfDepth)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/controller-test.js
>        calculateAspectRatio: function(a,b) {},
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "a". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "b". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/controller-test.js
>            removeClass: function(a) {}
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "a". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/controller-test.js
> +      findMainVideoElement: function(a) {},
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "a". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/controller-test.js
> +      loadConfigData: function(a, b, c, d) {},
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "a". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "b". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "c". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "d". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/controller-test.js
> +            add: function(a) {},
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "a". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/controller-test.js
>        displayMoreOptionsScreen: function(a) {},
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "a". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/controller-test.js
> +            remove: function(a) {}
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "a". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/controller-test.js
> +          addEventListener: function(a,b) {}
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "a". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "b". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/deepMerge.js
> +    //console.log("****** utils defaultArrayMerge destination: ", destination);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/deepMerge.js
> +  deepmerge.all = function deepmergeAll(array, optionsArgument) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Make this function anonymous by removing its name: 'function() {...}'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/deepMerge.js
> +    //console.log("****** utils defaultArrayMerge target: ", target);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/accessibilityControls.js
>    handleKey: function(e) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Function has a complexity of 14 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/views/startScreen.js
> +    if (nextProps.contentTree.description != this.props.contentTree.description) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "!=" with "!==". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/views/wikiaAdScreen.js
> +      this.props.controller.state.controlBarVisible || this.props.playerState == CONSTANTS.STATE.PAUSE;
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/views/wikiaAdScreen.js
> +  // FIXME move this to controller.js (?) so the first click shows controls, not toggles play/pause
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  					_IMAAdsManager.addEventListener(eventType.CLICK, _IMA_SDK_onAdClicked, false, this);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_IMA_SDK_onAdClicked" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  								_startTimeUpdater();
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_startTimeUpdater" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
> +					_IMAAdsManager.addEventListener(google.ima.AdEvent.Type.AD_BREAK_READY, _IMA_SDK_onAdBreakReady);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_IMA_SDK_onAdBreakReady" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  					_IMAAdsManager.addEventListener(eventType.CONTENT_PAUSE_REQUESTED, _IMA_SDK_pauseMainContent, false, this);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_IMA_SDK_pauseMainContent" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  				this.resumeAd = function(ad)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "ad". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  					_IMAAdsManager.addEventListener(eventType.CONTENT_RESUME_REQUESTED, _IMA_SDK_resumeMainContent, false, this);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_IMA_SDK_resumeMainContent" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
> +								_startNonLinearAdRulesOverlay();
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_startNonLinearAdRulesOverlay" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  						_tryStartAd();
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_tryStartAd" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  							if (this.videoControllerWrapper)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Merge this if statement with the nested one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACollapsibleIfStatements)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  					_IMA_SDK_destroyAdsLoader();
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_IMA_SDK_destroyAdsLoader" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  				this.pauseAd = function(ad)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "ad". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  					if(_usingAdRules && this.currentAMCAdPod.adType == _amc.ADTYPE.UNKNOWN_AD_REQUEST)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  					_IMAAdsLoader.addEventListener(adsManagerEvents.ADS_MANAGER_LOADED, _onAdRequestSuccess, false);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_onAdRequestSuccess" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
>  								_stopTimeUpdater();
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_stopTimeUpdater" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala/google_ima.js
> +							_resetUIContainerStyle();
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Move the declaration of "_resetUIContainerStyle" before this usage. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AVariableDeclarationAfterUsage)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/views/adScreen.js
>        this.props.playerState == CONSTANTS.STATE.PAUSE ||
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:30 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/components/utils-test.js
> +OO = {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Add the "let", "const" or "var" keyword to this declaration of "OO" to make it explicit. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2703)

2017-07-05 11:32 UTC, fraszczakszymon commented on extensions/wikia/ArticleVideo/scripts/ooyala-player.js
> +						if (eventData.A.vpaid === true) {
`eventData.A` - is it safe to use it?

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/adPanel.js
> +    if (this.props.currentAdsInfo &&
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce the number of conditional operators (4) used in the expression (maximum allowed 3). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/controlBar.js
>      finalControlBarItems = [];
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Add the "let", "const" or "var" keyword to this declaration of "finalControlBarItems" to make it explicit. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2703)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/controlBar.js
>      for (var k = 0; k < collapsedControlBarItems.length; k++) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Rename "k" as this name is already used in declaration at line 427. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2814)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/controlBar.js
>      // TODO: Update when implementing localization
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Complete the task associated to this TODO comment. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1135)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/controlBar.js
>      for (var k = 0; k < defaultItems.length; k++) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce the total number of "break" and "continue" statements in this loop to use one at most. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ATooManyBreakOrContinueInLoop)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/components/controlBar.js
>    populateControlBar: function() {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Function has a complexity of 71 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/components/controlBar-test.js
> +    DOM = TestUtils.renderIntoDocument(
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Add the "let", "const" or "var" keyword to this declaration of "DOM" to make it explicit. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2703)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/components/controlBar-test.js
> +    optionsButton = TestUtils.scryRenderedDOMComponentsWithClass(DOM, 'oo-more-options');
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Add the "let", "const" or "var" keyword to this declaration of "optionsButton" to make it explicit. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2703)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/components/controlBar-test.js
> +    buttons = TestUtils.scryRenderedDOMComponentsWithClass(DOM, 'oo-play-pause');
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Add the "let", "const" or "var" keyword to this declaration of "buttons" to make it explicit. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2703)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/tests/components/controlBar-test.js
> +    mockProps = {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Add the "let", "const" or "var" keyword to this declaration of "mockProps" to make it explicit. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2703)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>        else if (videoId == OO.VIDEO.ADS) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
> +      if (element.tagName && element.tagName.toLowerCase().indexOf(CONSTANTS.MEDIA_TYPE.VIDEO) != -1) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "!=" with "!==". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>      showUpNextScreenWhenReady: function(currentPlayhead, duration) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Function has a complexity of 12 which is greater than 10 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>        else if (videoId == OO.VIDEO.ADS){
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
> +      if(!this.state.autoPauseDisabled && Utils.isChrome() && this.state.mainVideoMediaType == CONSTANTS.MEDIA_TYPE.FLASH) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>        if (source == OO.VIDEO.MAIN) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>          if(currentPlayhead == 0 && this.state.playerState == CONSTANTS.STATE.PLAYING) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
> +          if (shareContent[i] == 'url') {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "==" with "===". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
> +      else if (element.tagName && element.tagName.toLowerCase().indexOf(CONSTANTS.MEDIA_TYPE.OBJECT) != -1) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "!=" with "!==". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>        if ((this.state.mainVideoPlayhead != 0 && currentPlayhead != 0) && duration !==0 &&
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "!=" with "!==". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace "!=" with "!==". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce the number of conditional operators (8) used in the expression (maximum allowed 3). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>        if(!this.state.isFullScreenSupported) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Merge this if statement with the nested one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACollapsibleIfStatements)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>      onPlaybackReady: function(event) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "event". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:32 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/bower_components/html5-skin/js/controller.js
>      onSkipAdClicked: function(event) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "event". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-07-05 11:32 UTC, WikiaTech commented
SonarQube analysis reported 4779 issues
* ![CRITICAL][CRITICAL] 38 critical
* ![MAJOR][MAJOR] 4144 major
* ![MINOR][MINOR] 378 minor
* ![INFO][INFO] 219 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [html5-skin.js#L4305](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4305): Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2583)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L4309](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4309): Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2583)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L4313](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4313): Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2583)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L4317](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4317): Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2583)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L4873](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4873): Remove this "===" check; it will always be false. Did you mean to use "=="? [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS3403)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L9073](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L9073): "converter" expects 0 arguments, but 2 were provided. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS930)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L9135](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L9135): Correct one of the identical sub-expressions on both sides of operator "/" [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1764)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L9469](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L9469): "iteratee" expects 1 argument, but 3 were provided. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS930)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L11244](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L11244): TypeError can be thrown as "initialChildren" might be null or undefined here. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L15950](https://github.com/Wikia/app/blob/fad1b5ed5ceaa8cf5ac69f7afb10dc82cc5814c5/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L15950): TypeError can be thrown as "inst" might be null or undefined here. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-07-05 11:41 UTC, rogatty commented on extensions/wikia/ArticleVideo/scripts/ooyala-player.js
> +						if (eventData.A.vpaid === true) {
Most likely not. Good catch, fixed in https://github.com/Wikia/app/pull/13246/commits/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa

2017-07-05 11:42 UTC, WikiaTech commented
SonarQube analysis reported 4779 issues
* ![CRITICAL][CRITICAL] 38 critical
* ![MAJOR][MAJOR] 4144 major
* ![MINOR][MINOR] 378 minor
* ![INFO][INFO] 219 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [html5-skin.js#L4305](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4305): Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2583)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L4309](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4309): Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2583)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L4313](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4313): Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2583)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L4317](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4317): Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2583)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L4873](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L4873): Remove this "===" check; it will always be false. Did you mean to use "=="? [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS3403)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L9073](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L9073): "converter" expects 0 arguments, but 2 were provided. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS930)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L9135](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L9135): Correct one of the identical sub-expressions on both sides of operator "/" [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1764)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L9469](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L9469): "iteratee" expects 1 argument, but 3 were provided. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS930)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L11244](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L11244): TypeError can be thrown as "initialChildren" might be null or undefined here. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [html5-skin.js#L15950](https://github.com/Wikia/app/blob/2a168017e740139fe2e2f91b6cd5641c8c8eb6aa/extensions/wikia/ArticleVideo/bower_components/html5-skin/build/html5-skin.js#L15950): TypeError can be thrown as "inst" might be null or undefined here. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-07-05 11:46 UTC, WikiaTech commented
SonarQube analysis reported 10 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ooyala-player.js#L97](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/scripts/ooyala-player.js#L97): Either make this concatenation explicit or cast one operand to a number. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS3402)
1. ![INFO][INFO] [OoyalaConfigController.class.php#L230](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/OoyalaConfigController.class.php#L230): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [OoyalaConfigController.class.php#L232](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/OoyalaConfigController.class.php#L232): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [OoyalaConfigController.class.php#L234](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/OoyalaConfigController.class.php#L234): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [OoyalaConfigController.class.php#L236](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/OoyalaConfigController.class.php#L236): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [OoyalaConfigController.class.php#L238](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/OoyalaConfigController.class.php#L238): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [OoyalaConfigController.class.php#L240](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/OoyalaConfigController.class.php#L240): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [OoyalaConfigController.class.php#L252](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/OoyalaConfigController.class.php#L252): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [OoyalaConfigController.class.php#L264](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/OoyalaConfigController.class.php#L264): Move this trailing comment on the previous empty line. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [ooyala-player.js#L4](https://github.com/Wikia/app/blob/e4212e38776a2755c1609f1932eabb69b79650f0/extensions/wikia/ArticleVideo/scripts/ooyala-player.js#L4): Complete the task associated to this TODO comment. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1135)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-07-05 12:39 UTC, rybmat requested changes

2017-07-05 12:39 UTC, rybmat commented on extensions/wikia/ArticleVideo/bower.json
> +		"html5-skin": "Wikia/html5-skin#XW-3684",
remember to change the branch to wikia-master

2017-07-05 13:04 UTC, hakubo approved these changes

2017-07-05 13:41 UTC, v3rth approved these changes

2017-07-06 15:58 UTC, WikiaTech commented on extensions/wikia/ArticleVideo/scripts/ooyala-player.js
> +					// FIXME with VPAID it causes volume controls to be in incorrect state
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)

2017-07-06 15:58 UTC, WikiaTech commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-07-07 08:48 UTC, latata commented on extensions/wikia/ArticleVideo/bower.json
> +		"html5-skin": "Wikia/html5-skin#XW-3684",
I'd set that to commit hash

2017-07-07 14:09 UTC, rybmat approved these changes

2017-07-07 14:10 UTC, merged