Remove legacy script
Wikia/app pull request #13294
Opened 2017-07-11 12:44 UTC by TK-999

These legacy svn utils are long unused and are missing from upstream repo too.

2017-07-11 12:48 UTC, themech approved these changes

2017-07-11 12:52 UTC, macbre requested changes

2017-07-11 12:52 UTC, macbre commented on bin/ulimit4.sh
> -eval "$4"
Please keep it - it's used by `wfShellExe`

2017-07-12 08:31 UTC, macbre approved these changes

2017-07-12 09:42 UTC, merged