Extension:SpecialCategoryIntersection rework
Wikia/app pull request #13457
Opened 2017-08-01 14:57 UTC by shaedrich

2017-08-03 09:01 UTC, mszabo-wikia requested changes
Thanks for your contribution! I have left a few notes.

2017-08-03 09:01 UTC, TK-999 commented on extensions/wikia/SpecialCategoryIntersection/SpecialCategoryIntersection.php
> +		$examples = array_map(function($singleExample) {
There is no benefit to using `array_map` here, it is slower than the `foreach` loop and does not make the code more readable.

2017-08-03 09:01 UTC, TK-999 commented on extensions/wikia/SpecialCategoryIntersection/SpecialCategoryIntersection.php
> +							$categories[] = (!startsWith($cat, $this->CATEGORY_NS_PREFIX) and !startsWith($cat, NS_CATEGORY)) ? $this->CATEGORY_NS_PREFIX.$cat : $cat;
FANDOM follows [MediaWiki's PHP coding conventions](https://www.mediawiki.org/wiki/CC/PHP). Please ensure your contributions follow this coding style.

2017-08-03 12:53 UTC, shaedrich commented on extensions/wikia/SpecialCategoryIntersection/SpecialCategoryIntersection.php
> +		$examples = array_map(function($singleExample) {
Okay, I reverted it.

2017-08-03 12:54 UTC, shaedrich commented on extensions/wikia/SpecialCategoryIntersection/SpecialCategoryIntersection.php
> +							$categories[] = (!startsWith($cat, $this->CATEGORY_NS_PREFIX) and !startsWith($cat, NS_CATEGORY)) ? $this->CATEGORY_NS_PREFIX.$cat : $cat;
no problem, I altered it to an if

2017-08-08 07:55 UTC, shaedrich reviewed
I hope everything is proper now.

2017-09-20 14:41 UTC, closed without merging

2017-09-20 15:59 UTC, shaedrich commented
@TK-999 First, @macbre added these two labels. So it seemed to me like the pr was desirable. So you delete it and I asked myself what your intent was...

2017-09-20 16:31 UTC, TK-999 commented
After internal discussion it was determined we cannot accept such feature requests for now to maintain compliance with the Pull Request Policy.

2017-09-20 16:37 UTC, shaedrich commented
Thank's for your explanation :)