XW-3816 | Fix fallback navigation
Wikia/app pull request #13565
Opened 2017-08-11 22:41 UTC by hakubo

2017-08-14 07:05 UTC, rybmat approved these changes

2017-08-21 13:53 UTC, rogatty commented on includes/wikia/services/ApiService.class.php
> +	static function foreignCall( string $dbName, Array $params, string $endpoint = self::API, bool $setUser = false ) {
```
There was 1 failure:

1) ApiAccessServiceTest::testForeignCall
Array (...) does not match expected type "boolean".
```

2017-08-21 14:01 UTC, rogatty commented on includes/wikia/services/ApiService.class.php
> +			$hostName = WikiFactory::DBtoUrl( $dbName );
Why do we want to use `DBtoUrl` on devboxes and `wgServer` on the rest of envs? If there is a good reason for that, please add a comment to the code.

2017-08-21 14:05 UTC, rogatty commented on includes/wikia/models/DesignSystemCommunityHeaderModel.class.php
> +			if ($this->productInstanceId == $wgCityId) {
A lot of missing spaces in this file, please reformat.

2017-08-21 14:08 UTC, rogatty requested changes
Please fix the tests, explain the changes in `getHostByDbName` and it will LGTM.

2017-09-12 10:10 UTC, rogatty approved these changes

2017-09-12 12:29 UTC, merged