XW-3171 | banner notifications
Wikia/app pull request #13651
Opened 2017-09-01 09:43 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-3171
@Wikia/x-wing

2017-09-01 10:12 UTC, rybmat approved these changes

2017-09-01 10:12 UTC, rybmat commented on extensions/wikia/BannerNotifications/js/BannerNotifications.js
> +			'<svg class="wds-icon wds-icon-tiny wds-banner-notification__close" width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg">' +
can you add here a TODO comment with the ticket number for supporting ds icons in JS?

2017-09-01 10:12 UTC, rybmat commented on extensions/wikia/DesignSystem/bower.json
> +    "design-system": "Wikia/design-system#XW-3171"
remember about release

2017-09-01 14:01 UTC, hakubo requested changes

2017-09-01 14:01 UTC, hakubo commented on extensions/wikia/BannerNotifications/js/BannerNotifications.js
> +			'notify': {
not needed ''

2017-09-01 14:01 UTC, hakubo commented on extensions/wikia/BannerNotifications/templates/BannerNotifications.mustache
> +		{{{icon}}}</div>
maybe that should be on one line (line 2)

2017-09-01 14:01 UTC, hakubo commented on extensions/wikia/BannerNotifications/templates/BannerNotifications_Confirmation.php
> +			</span>
weird indenting?

2017-09-01 14:45 UTC, JamesHawking approved these changes

2017-09-04 14:47 UTC, hakubo approved these changes

2017-09-04 15:22 UTC, merged