SUS-2628: Added shadow call to Phalanx@k8s
Wikia/app pull request #13690
Opened 2017-09-07 11:51 UTC by harnash

Companion PR:

2017-09-07 12:18 UTC, mszabo-wikia requested changes

2017-09-07 12:18 UTC, TK-999 commented on extensions/wikia/PhalanxII/services/PhalanxService.class.php
> +		global $wgPhalanxShadowUrl, $wgWikiaDatacenter;
Let's use `KubernetesUrlProvider` class that encapsulates this logic.

2017-09-07 12:18 UTC, TK-999 commented on extensions/wikia/PhalanxII/services/PhalanxService.class.php
> +			if ( $response != $shadowResponse && ( new \Wikia\Util\Statistics\BernoulliTrial( 0.001 ) )->shouldSample() ) {
Let's use strict type comparison here

2017-09-08 09:18 UTC, mszabo-wikia approved these changes

2017-09-08 13:54 UTC, macbre approved these changes

2017-09-13 11:02 UTC, merged