XW-3899 | update featured video labels in custom dimension
Wikia/app pull request #13719
Opened 2017-09-12 10:11 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-3899
@Wikia/x-wing 
@Wikia/adeng I added additional null check because there was exception thrown on browsers with adblock enabled
https://github.com/Wikia/app/compare/XW-3899?expand=1#diff-9d6fc6ece7c9753b14648b1f8b3c4870R117

2017-09-12 10:47 UTC, xkxd approved these changes

2017-09-12 10:47 UTC, xkxd commented on extensions/wikia/ArticleVideo/scripts/article-featured-video.js
> +					updateVideoCustomDimensions(nextVideoData.embed_code, nextVideoData.name, videoLabels);
`nextVideoData.embed_code` => `nextVideoId`?

2017-09-12 10:55 UTC, hakubo requested changes

2017-09-12 10:55 UTC, hakubo commented on extensions/wikia/ArticleVideo/scripts/article-featured-video.js
> +		function updateVideoCustomDimensions(videoId, videoTitle, videoLabels) {
can this funciton be inited outside initAttributionTracking?

2017-09-12 10:55 UTC, hakubo commented on extensions/wikia/ArticleVideo/scripts/ooyala-service.js
> +			nirvana.sendRequest({
sendRequest returns $.ajax - that already returns jquery promise

2017-09-12 10:55 UTC, hakubo commented on extensions/wikia/ArticleVideo/ArticleVideoController.class.php
> +		if ( empty( $videoId ) ) {
one \n before if

2017-09-12 11:50 UTC, hakubo approved these changes

2017-09-13 10:53 UTC, merged

2017-09-14 08:07 UTC, kvas-damian commented on extensions/wikia/ArticleVideo/ArticleVideoController.class.php
> +		$this->response->setVal( 'labels', $api->getLabels( $videoId ) );
It's a request to 3rd party API. Can we handle errors and make sure site won't be down when there are any problems on Ooyala side?

2017-09-14 08:17 UTC, kvas-damian commented
What is the use-case for this data?
I'm not sure how would we like to use this data. We don't share this information in the user session as it's changing. This suggests me that we're tracking one-time data - event. Maybe we could use tracking events?