XW-3831 | LI Metdata client
Wikia/app pull request #13710
Opened 2017-09-10 16:48 UTC by JamesHawking

[Ticket](https://wikia-inc.atlassian.net/browse/XW-3940)

@Wikia/x-wing

2017-09-11 06:42 UTC, latata commented on extensions/wikia/Recirculation/RecirculationHooks.class.php
> +			$metaData['start_date'] = $metaDataFromService->getDateFrom()->getTimestamp();
Are you sure timestamp is a right format of start/end date?

2017-09-11 06:42 UTC, latata commented on extensions/wikia/Recirculation/RecirculationHooks.class.php
> +		if ( !is_null( $metaDataFromService ) ) {
I'd use `empty` instead of is_null.

2017-09-11 06:51 UTC, latata commented on extensions/wikia/Recirculation/RecirculationHooks.class.php
>  			$siteAttributeData = self::getLiftIgniterMetadataFromSiteAttributeService();
I wonder what's stored there and maybe we should move these data to our service in future?

2017-09-11 07:55 UTC, hakubo requested changes

2017-09-11 07:55 UTC, hakubo commented on includes/wikia/services/LiftigniterMetadataService.class.php
> +/**
useless comment, can we remove?

2017-09-11 07:55 UTC, hakubo commented on includes/wikia/services/LiftigniterMetadataService.class.php
> +		} catch ( ApiException $e ) {
$apiException

2017-09-11 07:55 UTC, hakubo commented on includes/wikia/services/LiftigniterMetadataService.class.php
> +	public function getLiMetadataForArticle( $cityId, $pageId) {
properties types, also missing space

2017-09-11 07:55 UTC, hakubo commented on includes/wikia/services/LiftigniterMetadataService.class.php
> +		$apiProvider = Injector::getInjector()->get(ApiProvider::class);
missing spaces

2017-09-11 07:55 UTC, hakubo commented on lib/Swagger/src/Liftigniter/Metadata/Api/GeosApi.php
> +        } catch (ApiException $e) {
$apiException

2017-09-11 08:57 UTC, JamesHawking commented on extensions/wikia/Recirculation/RecirculationHooks.class.php
> +		if ( !is_null( $metaDataFromService ) ) {
👍

2017-09-11 10:16 UTC, xkxd approved these changes

2017-09-11 10:42 UTC, latata approved these changes

2017-09-12 10:23 UTC, latata approved these changes

2017-09-12 10:26 UTC, WikiaTech commented
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [RecirculationHooks.class.php#L71](https://github.com/Wikia/app/blob/78b96d9a046636a304d17a3621f52184b4444504/extensions/wikia/Recirculation/RecirculationHooks.class.php#L71): Reduce the number of conditional operators (4) used in the expression (maximum allowed 3). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1067)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-09-12 10:51 UTC, hakubo approved these changes

2017-09-13 10:09 UTC, merged