SER-1083 | Since users are global - we send confirmation reminder e-mail for use…
Wikia/app pull request #13818
Opened 2017-09-25 14:41 UTC by tmszdmsk

…rs without the context of wiki id

https://wikia-inc.atlassian.net/browse/SER-1083

2017-09-25 15:52 UTC, sqreek approved these changes

2017-09-25 16:11 UTC, macbre commented on extensions/wikia/UserLogin/maintenance.php
> +        sendReminder();
Please use tabs

2017-09-25 16:11 UTC, macbre commented on extensions/wikia/UserLogin/maintenance.php
> +			array()
You can omit these two last arguments of `select` method.

2017-09-25 16:11 UTC, macbre requested changes
Two minor comments left

2017-09-26 08:13 UTC, macbre approved these changes

2017-09-26 08:40 UTC, ghost approved these changes

2017-09-27 09:02 UTC, merged