SUS-2989 | Query wikicities
Wikia/app pull request #13985
Opened 2017-10-13 13:21 UTC by JamesHawking

[Ticket](https://wikia-inc.atlassian.net/browse/SUS-2989)

Remove JOIN to wikicities_cX.user in ApiQueryUsers::execute

2017-10-13 13:29 UTC, mszabo-wikia requested changes

2017-10-13 13:29 UTC, TK-999 commented on includes/api/ApiQueryUsers.php
>  			#$this->showHiddenUsersAddBlockInfo( isset( $this->prop['blockinfo'] ) );
Let's remove this commented out code.

2017-10-13 13:29 UTC, TK-999 commented on includes/api/ApiQueryUsers.php
>  				$user = User::newFromId( $row->user_id );
Let's use  `User::newFromRow` here to avoid cache lookup / DB call - the DB row we just loaded should have all of the necessary data.

2017-10-13 13:32 UTC, TK-999 commented on includes/api/ApiQueryUsers.php
>  				$user = User::newFromId( $row->user_id );
...as done in upstream 😉  https://github.com/wikimedia/mediawiki/blob/master/includes/api/ApiQueryUsers.php#L189

2017-10-13 15:23 UTC, mszabo-wikia approved these changes

2017-10-13 15:24 UTC, macbre requested changes

2017-10-13 15:24 UTC, macbre commented on includes/api/ApiQueryUsers.php
> +			$res = $dbr->select('`user`', 'user_id', [ 'user_name' => $goodNames ], __METHOD__);
Let's add `user_name` column so that `newFromRow` and `getName` does not make a query.

2017-10-16 10:01 UTC, mszabo-wikia approved these changes

2017-10-16 12:05 UTC, macbre approved these changes

2017-10-16 12:06 UTC, merged