XW-3960 | Support for JWPlayer in featured video MercuryAPI
Wikia/app pull request #14109
Opened 2017-10-30 09:13 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-3960
@Wikia/x-wing

2017-10-30 09:18 UTC, bkoval approved these changes

2017-10-30 09:27 UTC, hakubo approved these changes

2017-10-31 09:05 UTC, xkxd requested changes

2017-10-31 09:05 UTC, xkxd commented on extensions/wikia/MercuryApi/handlers/MercuryApiArticleHandler.class.php
> +				$featuredVideoData['ember']['jsParams']['videoId'] = $featuredVideo['videoId'];
![image](https://user-images.githubusercontent.com/6940495/32215697-00363ed4-be23-11e7-969f-d5ac1e3fd276.png)

2017-10-31 10:37 UTC, fraszczakszymon approved these changes

2017-10-31 10:52 UTC, xkxd approved these changes

2017-11-02 13:44 UTC, xkxd approved these changes

2017-11-02 13:44 UTC, xkxd commented on extensions/wikia/ArticleVideo/scripts/featured-video.jwplayer.ads.js
> +		featuredVideoSource,
keep undefined variables at the end

2017-11-02 14:25 UTC, merged