XW-4191 | Unmute video if coming from recirculation
Wikia/app pull request #14139
Opened 2017-11-03 11:41 UTC by JamesHawking

https://wikia-inc.atlassian.net/browse/XW-4191

2017-11-03 12:10 UTC, latata requested changes

2017-11-03 12:10 UTC, latata commented on extensions/wikia/ArticleVideo/scripts/featured-video.jwplayer.instant.js
> +			mute: isFromRecirculation() ? false : true,
if it isn't from recirculation it should be `willAutoplay`

2017-11-03 12:29 UTC, latata approved these changes

2017-11-06 09:59 UTC, xkxd approved these changes

2017-11-06 09:59 UTC, xkxd commented on extensions/wikia/ArticleVideo/package.json
> +    "jwplayer-fandom": "git+https://github.com/Wikia/jwplayer-fandom.git#XW-4191"
change before merging

2017-11-06 11:41 UTC, merged