SUS-3648 | remove ooyala-related code
Wikia/app pull request #14593
Opened 2018-01-29 13:41 UTC by xkxd

https://wikia-inc.atlassian.net/browse/SUS-3848

@Wikia/sus 
@Wikia/adeng 
@Wikia/x-wing 
@Wikia/mobile-apps

2018-01-29 14:35 UTC, macbre approved these changes
Red is my favourite colour :)

2018-01-30 09:29 UTC, fraszczakszymon commented on extensions/wikia/AdEngine/AdEngine2Hooks.class.php
> -		$vars[] = 'wgAdDriverF2OoyalaPosKeyValueCountries';
Revert it please. It's still in use and it shouldn't be removed

2018-01-30 09:38 UTC, fraszczakszymon requested changes
Revert instant global please

2018-01-30 12:34 UTC, fraszczakszymon approved these changes

2018-01-30 12:34 UTC, fraszczakszymon approved these changes

2018-01-30 12:47 UTC, macbre approved these changes

2018-01-30 12:49 UTC, mrmike approved these changes
LGTM from apps

2018-02-05 11:31 UTC, merged