MAIN-12799
Wikia/app pull request #14627
Opened 2018-01-31 16:39 UTC by timmyquivy

Enabling URT on Special:Contact

2018-01-31 16:47 UTC, Grunny requested changes

2018-01-31 16:47 UTC, Grunny commented on extensions/wikia/SpecialContact2/SpecialContact.body.php
> +		global $wgContLang, $wgEnableUserRenameToolExt;
`$wgContLang` is not used.

2018-01-31 16:52 UTC, timmyquivy commented
@Grunny - Change made.

2018-01-31 16:52 UTC, timmyquivy commented on extensions/wikia/SpecialContact2/SpecialContact.body.php
> +		global $wgContLang, $wgEnableUserRenameToolExt;
Fixed.

2018-02-01 09:24 UTC, macbre approved these changes

2018-02-06 08:12 UTC, merged