PLATFORM-3333: Make all design system links protocol relative
Wikia/app pull request #14692
Opened 2018-02-07 12:58 UTC by themech

2018-02-07 14:31 UTC, Grunny approved these changes

2018-02-07 14:35 UTC, Grunny requested changes
Actually, we need to fix the unit tests which expect the protocol.

2018-02-08 09:24 UTC, Grunny approved these changes

2018-02-15 10:31 UTC, closed without merging

2018-02-15 10:31 UTC, ludwikkazmierczak commented
Moved to : https://github.com/Wikia/app/pull/14797