XW-4155 | Remove jquery usage from mercury_ads_js
Wikia/app pull request #14760
Opened 2018-02-09 14:24 UTC by hakubo

2018-02-09 14:33 UTC, rybmat commented on resources/wikia/modules/tracker.stub.js
> +		if (window.$) {
a comment why we leave jquery in this place would be awesome

2018-02-12 07:23 UTC, kvas-damian commented on extensions/wikia/AdEngine/js/template/floor.js
> +			floor.classNames = 'hidden';
classNameS?

2018-02-12 07:31 UTC, kvas-damian requested changes
Please fix the typo

2018-02-12 09:35 UTC, kvas-damian approved these changes

2018-02-12 09:50 UTC, latata commented on extensions/wikia/AdEngine/js/template/floor.js
> +				var iFrameBody = iframe.contentWindow.document.body;
did you test it? I'm always worried about iframe manipulations.

2018-02-12 09:50 UTC, latata commented on extensions/wikia/AdEngine/js/template/floor.js
> +		floor.querySelector('.ad').appendChild(iframe);
are you sure `.ad` is empty before appneding?

2018-02-12 09:50 UTC, latata commented on extensions/wikia/PaidAssetDrop/js/paidAssetDrop.js
> +		// in mobile-wiki we do not have jquery but we do have a fetch polyfill so it is save to use this
do we have polyfill in `window` in MobileWiki?

2018-02-16 14:21 UTC, merged