XW-4637 | Track ad load time
Wikia/app pull request #14850
Opened 2018-02-22 12:29 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-4637
@Wikia/x-wing

2018-02-22 12:37 UTC, nandy-andy commented on extensions/wikia/AdEngine/js/tracking/adInfoTracker.js
> +			'ad_load_time': timestamp - window.performance.timing.connectStart,
Use `win.performance.timing.connectStart` instead in order to keep the global stuff away ;)

2018-02-22 12:38 UTC, hakubo approved these changes

2018-02-22 13:02 UTC, nandy-andy requested changes
Use `win` dependency instead of global `window`, please.

2018-02-22 13:03 UTC, nandy-andy commented on extensions/wikia/AdEngine/js/tracking/adInfoTracker.js
> +			'ad_load_time': timestamp - window.performance.timing.connectStart,
Use `win.performance.timing.connectStart` instead in order to keep the global stuff away ;)

2018-02-22 14:50 UTC, kvas-damian approved these changes

2018-02-23 10:00 UTC, nandy-andy approved these changes

2018-02-23 11:36 UTC, merged