SUS-4201 Make ckeditor https-ready
Wikia/app pull request #14863
Opened 2018-02-23 14:04 UTC by fraszczakszymon

2018-02-23 14:06 UTC, mszabo-wikia requested changes

2018-02-23 14:06 UTC, TK-999 commented on extensions/wikia/RTE/js/RTE.js
> +		var url = window.wgServer + window.wgScriptPath + '/wikia.php?controller=RTE&method=i18n&uselang=' + lang +
let's use `mw.util.wikiScript('wikia')`

2018-02-23 14:06 UTC, TK-999 commented on extensions/wikia/RTE/js/plugins/infobox/plugin.js
> +					$.get(window.wgScriptPath + '/api.php?format=json&action=query&list=allinfoboxes&uselang=' + window.wgContentLanguage).done(function(data) {
Let's use `mw.Api` helper

2018-02-26 11:10 UTC, mszabo-wikia approved these changes

2018-03-01 13:08 UTC, merged