SUS-4194 in Answers extension use getLocalUrl instead manual creation
Wikia/app pull request #14880
Opened 2018-02-26 15:15 UTC by sqreek

https://wikia-inc.atlassian.net/browse/SUS-4194

@Wikia/sus

2018-02-26 15:16 UTC, macbre approved these changes

2018-02-26 15:32 UTC, fraszczakszymon requested changes
What about 
https://github.com/Wikia/app/blob/dev/extensions/wikia/Answers/Answers.php#L236
https://github.com/Wikia/app/blob/dev/extensions/wikia/Answers/Answers.php#257
https://github.com/Wikia/app/blob/dev/extensions/wikia/Answers/SpecialGetQuestionWidget.php#L44
https://github.com/Wikia/app/blob/dev/extensions/wikia/Answers/SpecialGetQuestionWidget.php#L46

2018-02-27 00:37 UTC, mszabo-wikia requested changes

2018-02-27 00:37 UTC, TK-999 commented on extensions/wikia/Answers/HomePageList.php
> +	private function createLinkListElement($pageTitle, $text): string
Let's use [MW coding conventions](https://www.mediawiki.org/wiki/CC/PHP) - there's also an [XML configuration snippet](https://www.mediawiki.org/wiki/JetBrains_IDEs#MediaWiki_code_style) for IDEA

2018-02-27 09:21 UTC, sqreek commented
@fraszczakszymon wgServer will handle language path and answer.wikia.com is a specific wikia that we will rename from http to http[s by grepping whole repo

2018-02-27 09:24 UTC, mszabo-wikia approved these changes

2018-02-27 09:26 UTC, mszabo-wikia submitted a review, later dismissed
the `wgServer` won't contain path components, it will have to be concatenated with `wgScriptPath` and friends

2018-02-27 12:15 UTC, sqreek commented
@fraszczakszymon @TK-999 problematic code was removed

2018-02-27 12:33 UTC, mszabo-wikia approved these changes

2018-02-27 13:15 UTC, fraszczakszymon commented
@sqreek I like this approach :D

2018-02-27 13:15 UTC, fraszczakszymon approved these changes

2018-03-05 13:52 UTC, merged