SUS-4320 Removes INSERT IGNORE option in Block::insert()
Wikia/app pull request #15001
Opened 2018-03-15 16:05 UTC by leshniak

2018-03-16 08:24 UTC, macbre approved these changes

2018-03-16 08:24 UTC, macbre commented on includes/Block.php
> -			array( 'IGNORE' )
:+1:

2018-03-16 11:22 UTC, mszabo-wikia approved these changes
Callers expect this method to not throw an exception in case of conflict—let's preserve this guarantee by catching query errors and returning false. The `DBError` constructor will log it for us.

2018-03-16 16:18 UTC, mszabo-wikia requested changes
☝️ above was meant to be changes requested

2018-03-19 11:36 UTC, mszabo-wikia approved these changes

2018-03-19 11:36 UTC, mszabo-wikia commented on includes/Block.php
> +		catch ( DBError $ex ) {
let's align the braces otherwise 👍

2018-03-19 12:16 UTC, merged