ADEN-6827 Adds Grapeshot to allowed crawlers
Wikia/app pull request #15032
Opened 2018-03-20 15:10 UTC by leshniak

2018-03-26 09:50 UTC, nandy-andy commented on extensions/wikia/RobotsTxt/classes/WikiaRobots.class.php
> +			   $wgServer;
Something's wrong with indentation

2018-03-26 09:52 UTC, nandy-andy approved these changes

2018-04-09 07:08 UTC, macbre approved these changes

2018-04-11 10:03 UTC, mszabo-wikia requested changes

2018-04-11 10:03 UTC, mszabo-wikia commented on extensions/wikia/RobotsTxt/tests/RobotTest.php
> +	}
Let's move data providers under their corresponding test method

2018-04-11 10:03 UTC, mszabo-wikia commented on extensions/wikia/RobotsTxt/tests/RobotTest.php
> +		return [
You can use PHP generators (`yield`) in data providers which makes them more readable.

2018-07-12 11:24 UTC, themech commented
Closing as it got out of sync with dev

2018-07-12 11:24 UTC, closed without merging