SUS-4533 | Moving php.ini setup to dockerfile
Wikia/app pull request #15193
Opened 2018-04-18 09:08 UTC by bkoval

2018-04-18 09:08 UTC, bkoval commented on docker/base/Dockerfile
> +ADD ./php.ini /etc/php/7.0/apache2/php.ini
Do we need to set it up for cli as well? Let's check.

2018-04-18 16:17 UTC, pwojcik86 approved these changes

2018-04-18 16:17 UTC, pwojcik86 commented on docker/base/Dockerfile
> +# setup php.ini for apache
this comment is no longer valid

2018-04-25 14:00 UTC, macbre requested changes

2018-04-25 14:00 UTC, macbre commented on docker/base/php.ini
> +; End:
Let's remove useless lines with comments only. This file is simply too big.

2018-06-18 08:16 UTC, macbre approved these changes

2018-06-18 09:03 UTC, merged