SUS-4611 | backport MemcachedPeclBagOStuff from MW 1.20
Wikia/app pull request #15226
Opened 2018-04-23 10:45 UTC by macbre

https://github.com/wikimedia/mediawiki/commit/3c62077fe28778eb41bde7549fbae402c8be0ef7#diff-86946fda95cb93f7a1deb64d78e6c661

2018-04-23 11:03 UTC, mszabo-wikia requested changes

2018-04-23 11:03 UTC, mszabo-wikia commented on includes/objectcache/MemcachedPeclBagOStuff.php
> +				wfDebugLog( 'memcached-serious', $msg );
Let's update logging statements as needed

2018-04-24 09:04 UTC, ghost approved these changes

2018-04-24 09:32 UTC, bkoval commented on includes/objectcache/MemcachedBagOStuff.php
> +	 * Clamp expiries >30d at 30d, unless they're >=1e9 in which
*expires?

2018-04-25 11:21 UTC, mszabo-wikia approved these changes

2018-04-26 09:33 UTC, bkoval approved these changes

2018-04-27 14:16 UTC, merged