Make tests great again 🚚
Wikia/app pull request #15439
Opened 2018-05-29 12:27 UTC by mszabo-wikia

Drag the tests, kicking and screaming, into Travis CI so they can be executed in a containerized, isolated environment.

A tiny number of tests have dependencies that cannot be replicated inside the container (such as `SwiftStorageTest` calling the aforementioned storage, or ImageServing tests assuming the presence of certain wiki articles with embedded specific images). For now these tests have been annotated with `@group Infrastructure` and are excluded from Travis runs—it should be possible to run them manually on devbox, or via some Jenkins job.

Additionally, all `@group Broken` tests were either fixed and re-enabled or removed, and the handling of the group itself was removed from our PHPUnit setup. In the future, failing tests should either be fixed, or removed, or at least disabled via PHPUnit `markTestSkipped` feature so they actually show up in the test run output as skipped.

@Wikia/sus

2018-05-29 13:07 UTC, macbre commented on extensions/wikia/UserRenameTool/tests/RenameUserSetupChecksTest.php
> +			var_dump($process->getErrors());
var_dump :)

2018-05-29 13:11 UTC, macbre approved these changes

2018-05-29 14:07 UTC, pwojcik86 requested changes

2018-05-29 14:07 UTC, pwojcik86 commented on extensions/wikia/Privacy/tests/UserDataRemoverTest.php
> +		$this->heliosClientMock->expects( $this->once() )
We don't need to check if Helios is called; it's done by the rtbf service already. The only reason this happens is because we use `Wikia::invalidateUser`

2018-05-29 14:07 UTC, pwojcik86 commented on extensions/wikia/Privacy/tests/fixtures/audit_log.sql
> +  id int PRIMARY KEY AUTO_INCREMENT,
I thought this didn't work with sqllite

2018-05-29 14:19 UTC, mszabo-wikia commented on extensions/wikia/Privacy/tests/fixtures/audit_log.sql
> +  id int PRIMARY KEY AUTO_INCREMENT,
There's no SQLite any more, MySQL is used :)

2018-05-29 14:19 UTC, mszabo-wikia commented on extensions/wikia/Privacy/tests/UserDataRemoverTest.php
> +		$this->heliosClientMock->expects( $this->once() )
sure, I can change it to do no verification—but the stubbing needs to stay there to avoid an HTTP call to a nonexistent service

2018-06-18 16:27 UTC, macbre commented
@mszabo-wikia - rotten pull request warning :smile:

2018-06-18 19:26 UTC, closed without merging