PLATFORM-3525: enable HTTPS on single domain wikis for all logged in users
Wikia/app pull request #15469
Opened 2018-06-04 11:45 UTC by harnash

Initial cleanup and removal of the threshold check. This will enable HTTPS by default for logged-in users on all single-domain wikis.

ping: @Wikia/core-platform-team

2018-06-04 14:26 UTC, Grunny requested changes

2018-06-04 14:26 UTC, Grunny commented on extensions/wikia/HTTPSOptIn/HTTPSOptInHooks.class.php
> -				'label-message' => 'https-opt-in-toggle',
We can now remove the i18n.php file (and delete the crowdin project), since this was the only message.

2018-06-05 08:40 UTC, harnash commented on extensions/wikia/HTTPSOptIn/HTTPSOptInHooks.class.php
> -				'label-message' => 'https-opt-in-toggle',
@Grunny fix in 36d3d4c.

2018-06-05 08:41 UTC, Grunny approved these changes

2018-06-12 09:05 UTC, merged