SUS-3433 | add comment mapping when comments are posted
Wikia/app pull request #15487
Opened 2018-06-06 09:07 UTC by pwojcik86

https://wikia-inc.atlassian.net/browse/SUS-3433

Whenever a comment is posted, a mapping record is added to `article_comments`. Mappings are deleted using foreign key constraints, and restored in the `UndeleteComplete` hook.

2018-06-06 09:08 UTC, macbre approved these changes

2018-06-06 09:27 UTC, mszabo-wikia requested changes

2018-06-06 09:27 UTC, mszabo-wikia commented on extensions/wikia/ArticleComments/ArticleCommentsHooks.class.php
> +		if ( strpos($dbKey, '@comment' ) === false ) {
let's check also namespace: `in_array( MWNamespace::getSubject( $title->getNamespace() ), $wgArticleCommentsNamespaces )` so as not to handle Wall & friends

2018-06-06 09:27 UTC, mszabo-wikia commented on extensions/wikia/ArticleComments/ArticleCommentsHooks.class.php
> +			$parentCommentId = Title::newFromDBkey( $parts[0] . '/' . $parts[1] )->getArticleID();
if parent comment or parent article don't exist we should probably abort

2018-06-06 09:27 UTC, mszabo-wikia commented on extensions/wikia/ArticleComments/classes/ArticleComment.class.php
> +		self::addCommentMapping( $article->getID(), $title->getArticleID(), $parentId ?: 0 ); // SUS-3433
this code gets called also for Wall/Forum, we should probably put it into doAfterPost method which won't get called for those after https://github.com/Wikia/app/pull/15473

2018-06-07 08:48 UTC, mszabo-wikia approved these changes

2018-06-08 09:28 UTC, mszabo-wikia approved these changes

2018-08-10 13:13 UTC, closed without merging