PLATFORM-3540 delete single wiki
Wikia/app pull request #15602
Opened 2018-06-26 07:17 UTC by harnash

Script for deleting single wiki - used to recreate tests wikis.

2018-06-29 16:26 UTC, Grunny requested changes

2018-06-29 16:26 UTC, Grunny commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +		$centralDB = empty( $cluster) ? "wikicities" : "wikicities_{$cluster}";
Is `$cluster` set anywhere?

2018-06-29 16:26 UTC, Grunny commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +		$sth = $dbr->select(
`$dbr->selectRow` since you only want one result.

2018-06-29 16:26 UTC, Grunny commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +				'cluster'   => $cluster,
Same here, is `$cluster` set anywhere?

2018-06-29 16:26 UTC, Grunny commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +			[ "city_list" ],
Minor: coding conventions prefer single quotes unless you are doing string interpolation, same applied throughout.

2018-06-29 16:26 UTC, Grunny commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +			return 1;
Do the return values of `execute` have any meaning/effect?

2018-06-29 16:26 UTC, Grunny commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +	private function cleanupSharedData( $city_id ) {
Minor: coding conventions prefer `lowerCamelCase` rather than underscores for variables. Same comment applies to some other variables below in `doTableCleanup` and `WikiFactory::isInArchive`.

2018-07-02 08:00 UTC, harnash commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +		$centralDB = empty( $cluster) ? "wikicities" : "wikicities_{$cluster}";
Fixed in 6cb8fa7a116. This might be useful on prod clusters.

2018-07-02 08:02 UTC, harnash commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +				'cluster'   => $cluster,
6cb8fa7

2018-07-02 08:05 UTC, harnash commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +			[ "city_list" ],
24604c22a83

2018-07-02 08:07 UTC, harnash commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +	private function cleanupSharedData( $city_id ) {
5137ab7ba13

2018-07-02 08:12 UTC, harnash commented
@grunny all remarks should be addressed now

2018-07-02 08:23 UTC, harnash commented on extensions/wikia/WikiFactory/Close/close_single_wiki.php
> +			return 1;
You are right. They seem to be ignored. 11f784a554b

2018-07-02 15:48 UTC, Grunny approved these changes

2018-07-03 08:44 UTC, merged