SER-2686 | Publish wiki status changes
Wikia/app pull request #16221
Opened 2018-10-17 14:30 UTC by slayful

2018-10-17 16:28 UTC, mszabo-wikia requested changes

2018-10-17 16:28 UTC, mszabo-wikia commented on includes/wikia/VariablesBase.php
> +$wgWikiStatusChangePublisher = [
Let's add some docs for this variable

2018-10-17 16:28 UTC, mszabo-wikia commented on extensions/wikia/WikiFactory/WikiStatusChangePublisher/WikiStatusChangeHooks.php
> +class WikiStatusChangeHooks {
This class needs to be registered with the autoloader

2018-10-17 16:28 UTC, mszabo-wikia commented on extensions/wikia/WikiFactory/WikiStatusChangePublisher/WikiStatusChangeHooks.php
> +				return "hidden";
are there any other cases we should handle? should there be a fallback?

2018-10-18 10:12 UTC, slayful commented on includes/wikia/rabbitmq/ConnectionBase.class.php
> -	protected $deadExchange;
This field was unused.

2018-10-18 10:13 UTC, mszabo-wikia approved these changes

2018-10-18 10:17 UTC, mszabo-wikia approved these changes

2018-10-19 09:58 UTC, tmszdmsk approved these changes

2018-10-19 14:59 UTC, merged