IW-1233 Create price update bot for runescape wikis
Wikia/app pull request #16319
Opened 2018-11-06 08:24 UTC by jsutterfield

Ticket: https://wikia-inc.atlassian.net/browse/IW-1233

This PR replicates a price update bot which used to exist on the runescape and oldschoolrunescape wikis. The bot queries for all items which need to be updated (those in the "Grand Exchange" category), fetches the latest price info for those items from the Jagex API (Jagex is the creator of Runescape), and updates the Module:Exchange/\<itemName\> and Module:Exchange/\<itemName\>/Data pages with the new price info. Additionally, it updates Module:GEPrices/data page (which is a list of all items and their latest prices), and a series of index pages.

It's based on the old TyBot which was an admin created and maintained bot which updates prices in the same way. After the fork on October 2nd, that bot was moved to the new wikis and removed from our wikis. This code recreates it's functionality so items on our wikis have up-to-date pricing information again.

2018-11-06 10:23 UTC, mszabo-wikia requested changes

2018-11-06 10:23 UTC, mszabo-wikia commented on maintenance/wikia/runescapeBot/grandExchangePageFetcher.class.php
> +		];
It might be better to create a `Category` instance with `Category::newFromTitle` and use `Category::getMembers( int $limit, string $offset )` to get the members. It's a bit more efficient/straightforward and will also return a `TitleArray` that can be used to iterate over titles.

2018-11-06 10:23 UTC, mszabo-wikia commented on maintenance/wikia/runescapeBot/updateGrandExchangeItemPrices.php
> +		$this->botUser = User::newFromName( self::BOT_USERNAME );
There's an existing constant `Wikia::BOT_USER` which should be preferred.

2018-11-06 10:23 UTC, mszabo-wikia commented on maintenance/wikia/runescapeBot/updateGrandExchangeItemPrices.php
> +		} catch (Exception $e) {
Should be spacey

2018-11-06 12:15 UTC, jsutterfield commented on maintenance/wikia/runescapeBot/grandExchangePageFetcher.class.php
> +		];
Ah! I didn't know we could do it that way. That does sounds like a better approach. I'll update.

2018-11-06 14:27 UTC, mszabo-wikia approved these changes
Looks OK. Depending on the number of pages in the category, we might not want to fetch them all in a single query and use multiple batches instead.

2018-11-07 11:55 UTC, jsutterfield commented
Just a heads-up @mszabo-wikia, I ended reverting the changes I made which used the Category class. I tried to implement paging (since we are pulling ~4k pages out of the db), but I was struggling to get it working. Even if using the `ApiMain` approach is a bit less efficient, it does use paging which I think is a greater net benefit. I'm going to stick with that for now.

Thanks again for the eyes and insights :)

2018-11-07 11:55 UTC, merged