LORE-110 | Add ability to mark certain variables as readonly
Wikia/app pull request #16458
Opened 2018-12-06 21:41 UTC by vforge

@Wikia/lore 
@Grunny

2018-12-07 07:11 UTC, Grunny requested changes

2018-12-07 07:11 UTC, Grunny commented on extensions/wikia/WikiFactory/WikiFactory.php
> +		return in_array( $cv_variable_id, $wgWikiFactoryReadonlyBlacklist, true );
This is missing the `global $wgWikiFactoryReadonlyBlacklist;` declaration, so `$wgWikiFactoryReadonlyBlacklist` will be null.

2018-12-07 19:03 UTC, nmonterroso approved these changes

2018-12-10 12:25 UTC, Grunny approved these changes

2018-12-10 18:36 UTC, merged