PLATFORM-3884 | Apply uncrawlable links fix to category navigation links
Wikia/app pull request #16512
Opened 2018-12-20 08:53 UTC by maaartyyynaa

2018-12-28 13:24 UTC, themech requested changes

2018-12-28 13:24 UTC, themech commented on extensions/wikia/CategoryPage3/styles/category-page3.scss
> +				cursor: pointer;
In general we try to keep the rules in alphabetical order. Although as you can see here, we're not doing a perfect job.

2018-12-28 13:24 UTC, themech commented on extensions/wikia/CategoryPage3/templates/members-header.php
> +				'href' => null,
do you have to specify the `href` attribute?

2019-01-02 09:43 UTC, Grunny approved these changes

2019-01-02 13:29 UTC, themech approved these changes

2019-01-04 15:56 UTC, Grunny approved these changes

2019-01-04 15:57 UTC, merged