IW-1489 | add rail logic + backend urls
Wikia/app pull request #16544
Opened 2019-01-09 13:56 UTC by xkxd

https://wikia-inc.atlassian.net/browse/IW-1489

2019-01-09 17:31 UTC, mszabo-wikia requested changes

2019-01-09 17:31 UTC, mszabo-wikia commented on extensions/wikia/Recirculation/RecirculationHooks.class.php
> +		$out->addJsConfigVars('wgServiceUrl', empty( $wgDevelEnvironment ) ? 'services.wikia.com' : 'services.wikia-dev.pl' );
`wgServicesExternalDomain` is already available on the client side and should be used instead

2019-01-10 09:39 UTC, jsutterfield approved these changes

2019-01-10 09:39 UTC, jsutterfield commented on extensions/wikia/Recirculation/js/helpers/sponsoredContent.js
> +			$
This formatting is kind of funky. Maybe bring `.ajax` up to this line?

2019-01-10 09:39 UTC, jsutterfield commented on extensions/wikia/Recirculation/js/helpers/sponsoredContent.js
> +					url: w.wgServicesExternalDomain + 'wiki-recommendations/sponsored-articles',
String interpolation via backticks is typically preferred, yea?

2019-01-10 10:26 UTC, mszabo-wikia commented on extensions/wikia/Recirculation/js/helpers/sponsoredContent.js
> +					url: w.wgServicesExternalDomain + 'wiki-recommendations/sponsored-articles',
It won't work in IE11

2019-01-10 12:35 UTC, mszabo-wikia approved these changes

2019-01-10 12:36 UTC, merged