PLATFORM-3912 image lightbox
Wikia/app pull request #16569
Opened 2019-01-16 09:53 UTC by harnash

Adds an tooltip/dropdown with image description for anonymous users instead of link to the file page.

2019-01-22 10:19 UTC, Grunny requested changes

2019-01-22 10:19 UTC, Grunny commented on extensions/wikia/Lightbox/templates/Lightbox_lightboxModalContent.php
> +				<span><?= wfMsg('lightbox-header-more-info-button') ?></span>
`wfMsg` is deprecated, `wfMessage` with a safe output format should be used.

2019-01-22 10:19 UTC, Grunny commented on extensions/wikia/Lightbox/LightboxController.class.php
> +		global $wgParser;
I think we would generally use `ParserPool` rather than the global `wgParser` object for one off parsing like this.

2019-01-22 10:19 UTC, Grunny commented on extensions/wikia/Lightbox/styles/Lightbox.scss
> +				padding: 18px;
Properties should be alphabetised per conventions.

2019-01-22 10:34 UTC, harnash commented on extensions/wikia/Lightbox/templates/Lightbox_lightboxModalContent.php
> +				<span><?= wfMsg('lightbox-header-more-info-button') ?></span>
Fix: 32f1b20b7ac

2019-01-22 12:28 UTC, harnash commented on extensions/wikia/Lightbox/LightboxController.class.php
> +		global $wgParser;
Fix: 10a4de2f9e8

2019-01-22 12:29 UTC, harnash commented on extensions/wikia/Lightbox/styles/Lightbox.scss
> +				padding: 18px;
Fix: 10a4de2f9e8

2019-01-23 20:20 UTC, Grunny approved these changes

2019-01-28 12:25 UTC, merged