SER-3150 | Allow to use unified-search in Special:Search
Wikia/app pull request #16986
Opened 2019-04-25 15:50 UTC by slayful

2019-04-26 12:53 UTC, slayful commented on extensions/wikia/Search/WikiaSearchController.class.php
> +		$this->handleLayoutAbTest( $this->getVal( 'ab', null ) );
The `namespaces` param was unused in the method. Removed to simplify.

2019-04-26 12:53 UTC, slayful commented on extensions/wikia/Search/WikiaSearchController.class.php
> +		$this->setPageTitle( $searchConfig );
We can safely re-order this.

2019-05-06 13:54 UTC, pwojcik86 requested changes

2019-05-06 13:54 UTC, pwojcik86 commented on extensions/wikia/Search/classes/QueryService/Select/AbstractSelect.php
> +		WikiaLogger::instance()->info("fields " .json_encode( $fields));
Is this necessary?

2019-05-06 13:54 UTC, pwojcik86 commented on extensions/wikia/Search/classes/QueryService/Select/Dismax/Video.php
> +//		'indexed',
Don't commit commented out code. Either remove it, or don't.

2019-05-06 13:54 UTC, pwojcik86 commented on extensions/wikia/Search/classes/UnifiedSearch/UnifiedSearchService.php
> +			throw $e;
Is this exception handled in any way?

2019-05-06 13:54 UTC, pwojcik86 commented on extensions/wikia/Search/classes/UnifiedSearch/SearchResultWrapper.php
> +use Wikia\Search\SearchResultItems as SearchResultItemsAlias;
Why is this aliased?

2019-05-07 07:52 UTC, pwojcik86 approved these changes

2019-05-07 10:42 UTC, merged