Configurable consul suffix with datacenter and stage validation, PLAT…
Wikia/app pull request #17007
Opened 2019-05-06 09:33 UTC by abador

Based on WIKIA_OVERWRITE_CONSUL_SUFFIX env it checks what stage and dc is used and validates it. After that It overwrites all service.consul sufficex and stage prefixes to the set values.
You can check by setting WIKIA_OVERWRITE_CONSUL_SUFFIX=true SERVER_DBNAME=abador php $PHP_PARAMS /usr/wikia/source/app/maintenance/wikia/HttpsMigration/migrateCheckUser.php

2019-05-06 11:07 UTC, harnash requested changes

2019-05-06 11:07 UTC, harnash commented on LocalSettings.php
> +$wgOverwriteConsulSuffix = getenv( 'WIKIA_OVERWRITE_CONSUL_SUFFIX' );
This name is a bit misleading since it does not override only suffixes but also forces app to use consul tags as well. I would opt for something in tune with `wgForceConsulDatacenter` or similar

2019-05-06 11:07 UTC, harnash commented on LocalSettings.php
> +			if( $wgWikiaDatacenter != 'sjc' && $wgWikiaDatacenter != 'poz' ){
Although I appreciate the effort I do not think that this check is needed. If set improperly the app will fail anyway and it will not safeguard us from all possible/incorrect variations. Moreover when we decide to add new DC (i.e. we might have some apps running in FRA or in the cloud) it will add to the things we need to update in order to deploy the application there. I would keep the config as opaque (from the running ENV) as possible and not double check those values (they should be provided and be correct).

2019-05-06 11:07 UTC, harnash commented on includes/wikia/VariablesBase.php
> +	$wgSolrHost = $wgWikiaEnvironment . '.search-fulltext.' . $wgWikiaDatacenter . '.consul';
I'm not sure we do have those SOLR instances on DEV

2019-05-06 11:07 UTC, harnash commented on includes/wikia/VariablesBase.php
> +	$wgSolrKvHost = $wgWikiaEnvironment . '.search-kv.' . $wgWikiaDatacenter . '.consul';
same as above

2019-05-06 11:30 UTC, harnash commented on includes/wikia/VariablesBase.php
> +	$wgPoolCounterServers = [ $wgWikiaEnvironment . '.kubernetes-lb-l4.' . $wgWikiaDatacenter . '.consul' ];
```suggestion
	$wgPoolCounterServers = [ $wgWikiaEnvironment . '.kubernetes-lb-l4.service.' . $wgWikiaDatacenter . '.consul' ];
```

2019-05-06 11:31 UTC, harnash commented on includes/wikia/VariablesBase.php
> +	$wgSMTP['host'] = $wgWikiaEnvironment . '.smtp.' . $wgWikiaDatacenter . '.consul';
```suggestion
	$wgSMTP['host'] = $wgWikiaEnvironment . '.smtp.service.' . $wgWikiaDatacenter . '.consul';
```

2019-05-06 11:32 UTC, harnash commented on includes/wikia/VariablesBase.php
> +	$wgSolrHost = $wgWikiaEnvironment . '.search-fulltext.' . $wgWikiaDatacenter . '.consul';
Remember about `.service.` part

2019-05-07 08:40 UTC, harnash approved these changes

2019-05-07 20:22 UTC, mszabo-wikia requested changes
In the config refactor it was laid out that `VariablesBase.php` should only contain simple declarations. Could we perhaps move these overrides into a conditionally included override file?

2019-05-09 17:19 UTC, Grunny approved these changes

2019-05-09 18:44 UTC, mszabo-wikia approved these changes

2019-05-10 09:27 UTC, merged