PLATFORM-3837 Removed config variables, assumed all domains have https enabled
Wikia/app pull request #17171
Opened 2019-06-13 12:44 UTC by Michal-Chatlas1221

2019-06-17 12:15 UTC, themech requested changes

2019-06-17 12:15 UTC, themech commented on extensions/wikia/CreateNewWiki/CreateWikiChecks.php
> +				$protocol = 'https';
We don't need the `$protocol` variable anymore. Just replace the usage below with 
```
[ 'href' => PROTO_HTTPS . "{$domain}" ]
```

2019-06-17 12:15 UTC, themech commented on extensions/wikia/FandomComMigration/FandomComMigrationHooks.class.php
>  		return empty( $wgDomainMigrationDisabled ) &&
I think the `wgDomainMigrationDisabled` can be removed. It was introduced for domain that we did not want to migrate, but I think those are now closed so we don't need this check anymore. @Grunny?

2019-06-17 12:15 UTC, themech commented on extensions/wikia/FandomComMigration/FandomComMigrationHooks.class.php
> -			empty( $wgWikiaOrgMigrationScheduled ) &&
I'm not sure about removing the `wgWikiaOrgMigrationScheduled` here. Unless we're removing it from the whole codebase.

2019-06-17 12:15 UTC, themech commented on extensions/wikia/FandomComMigration/FandomComMigrationHooks.class.php
> +			empty( $wgEnableAnswers ) &&
obsolete since https://github.com/Wikia/app/pull/17129/files has been merged

2019-06-17 12:15 UTC, themech commented on extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
> -		$wikiVariables['disableHTTPSDowngrade'] = !empty( $wgDisableHTTPSDowngrade );
which reminds me we should also simplify the mobile-wiki counterpart: https://github.com/Wikia/mobile-wiki/blob/13a65ea944623c86601cc2032ed7d3c1d593bc57/app/models/wiki-variables.js#L77

2019-06-17 12:15 UTC, themech commented on extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
>  	public static function onRobotsBeforeOutput( WebRequest $request, User $user, OutputPage $output ): bool {
https://github.com/Wikia/app/pull/17158 - you removed the code that was triggering this hook listener. So the whole `onRobotsBeforeOutput ` method and its registration as hook listener can be removed.

2019-06-17 12:15 UTC, themech commented on extensions/wikia/RobotsTxt/classes/WikiaRobots.class.php
> +				if ( wfHttpsAllowedForURL( $sitemapUrl ) ) {
This check is obsolete. All communities have been migrated to https so we can always call `wfHttpToHttps( $sitemapUrl )`

2019-06-17 12:15 UTC, themech commented on includes/wikia/api/WikisApiController.class.php
> +				$this->response->setVal( 'primaryProtocol', 'https://' );
Now the `primaryProtocol` is obsolete. We can remove it from the response. And update the robots-txt service code (https://github.com/Wikia/robots-txt/blob/ea8fe43566aab244f538ab028056aae6b762d823/handlers/robots.go#L139).
And, while there, we could also remove this check: https://github.com/Wikia/robots-txt/blob/ea8fe43566aab244f538ab028056aae6b762d823/handlers/robots.go#L170

2019-06-17 12:15 UTC, themech commented on extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
> +				wfHttpsAllowedForURL( $requestURL )
I'm not sure we even need this method anymore. All protocol redirects are probably done in WikiFactoryLoader so this is redundant.

2019-06-17 12:15 UTC, themech commented on extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
>  				self::shouldDowngradeRequest( $title, $request )
We should never downgrade from https to http. So things like the `shouldDowngradeRequest` method or `$httpsArticles` can be removed as well

2019-06-17 12:15 UTC, themech commented on extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
>  	public static function onMercuryWikiVariables( array &$wikiVariables ): bool {
Now this method is so simple I think we can just try to use wfHttpsAllowedForURL/wfHttpToHttps there: https://github.com/Wikia/app/blob/b3d119e46384a373d2510de23eff22c001d67cca/extensions/wikia/MercuryApi/models/MercuryApi.class.php#L115 and remove this hook listener

2019-06-17 12:15 UTC, themech commented on extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
>  	private static function httpsEnabledTitle( Title $title ): bool {
most likely this can be removed

2019-06-17 12:15 UTC, themech commented on extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
>  	private static function shouldDowngradeRequest( Title $title, WebRequest $request ): bool {
most likely this can be removed (as well as `isRawCssOrJs` below)

2019-06-17 12:15 UTC, themech commented on includes/wikia/GlobalFunctions.php
> -	global $wgWikiaDevDomain, $wgFandomDevDomain, $wgWikiaEnvironment, $wgDevelEnvironment;
👍 for making it simpler

2019-06-17 12:15 UTC, themech commented on includes/wikia/services/WikiDetailsService.class.php
> +			if ( wfHttpsAllowedForURL( $city_url ) ) {
I'm pretty sure this check if not needed, just assume we're on https.

2019-06-17 12:28 UTC, Michal-Chatlas1221 commented on extensions/wikia/FandomComMigration/FandomComMigrationHooks.class.php
>  		return empty( $wgDomainMigrationDisabled ) &&
I didn't remove it actually, I've removed other variables, and moved it one line higher

2019-06-17 12:47 UTC, Michal-Chatlas1221 commented on extensions/wikia/FandomComMigration/FandomComMigrationHooks.class.php
> -			empty( $wgWikiaOrgMigrationScheduled ) &&
`$wgFandomComMigrationScheduled` should stay is, because it's being used for some hacks, am I correct?

2019-06-17 12:54 UTC, themech commented on extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
> -		$wikiVariables['disableHTTPSDowngrade'] = !empty( $wgDisableHTTPSDowngrade );
Actually there is more apps to be updated: https://github.com/search?q=org%3AWikia+disableHTTPSDowngrade&type=Code

2019-06-17 13:37 UTC, Grunny commented on extensions/wikia/FandomComMigration/FandomComMigrationHooks.class.php
>  		return empty( $wgDomainMigrationDisabled ) &&
Yep, it can be removed.

2019-07-03 10:41 UTC, themech commented on includes/OutputPage.php
> +			if( wfHttpsAllowedForURL( $this->mRedirect ) ) {
I'm not sure if that maintains the previous logic. Will have to double-check that later.

2019-07-04 08:38 UTC, themech commented on includes/OutputPage.php
> +			if( wfHttpsAllowedForURL( $this->mRedirect ) ) {
`if ( $this->mRedirectProtocol === PROTO_HTTPS ) {` is more compatible with the previous flow. But while we're here, I think the `wfHttpsAllowedForURL` should be called after `wfExpandUrl`. So the flow should be:
```
# Standards require redirect URLs to be absolute
$this->mRedirect = wfExpandUrl( $this->mRedirect, $this->mRedirectProtocol );

if ( $this->mRedirectProtocol === PROTO_HTTPS ) {
    $this->mRedirect = wfHttpToHttps( $this->mRedirect );
}
```

2019-07-04 08:53 UTC, themech approved these changes

2019-07-05 13:44 UTC, merged