PLATFRORM-3950 Updated starter interwiki links
Wikia/app pull request #17206
Opened 2019-06-25 09:24 UTC by Michal-Chatlas1221

2019-06-26 06:40 UTC, harnash approved these changes

2019-06-26 13:12 UTC, themech requested changes

2019-06-26 13:12 UTC, themech commented on maintenance/interwiki.sql
> +('wikia','https://www.fandom.com/wiki/$1',0),
There is no mediawiki under www.fandom.com

2019-06-26 13:12 UTC, themech commented on maintenance/interwiki.sql
> +('wikicities','https://www.fandom.com/wiki/$1',0),
ditto

2019-06-26 13:12 UTC, themech commented on maintenance/wikia/city_interwiki_links.sql
> +('academicjobs','https://academicjobs.fandom.com/wiki/$1','1','0'),
should be `https://academicjobs.wikia.org`

2019-06-26 13:12 UTC, themech commented on maintenance/wikia/city_interwiki_links.sql
> +('wikiavideo','https://video.fandom.com/wiki/Video:$1','1','0'),
I don't think it exists

2019-07-01 12:33 UTC, themech approved these changes

2019-07-02 08:03 UTC, ludwikkazmierczak commented on maintenance/wikia/city_interwiki_links.sql
> +('wikiagaming','https://gamicus.gamepedia.com/wiki/$1','1','0'),
I think it should be: `https://gamicus.gamepedia.com/$1` since gamepedia does not have an article path like we do :)

2019-07-02 08:03 UTC, ludwikkazmierczak commented on maintenance/wikia/city_interwiki_links.sql
> +('wikiaentertainment','https://entertainment.fandom.com/wiki/$1','1','0'),
This wiki seems to be closed, should we just remove it?

2019-07-02 09:22 UTC, merged