Added a docker image for using composer on devbox
Wikia/app pull request #17234
Opened 2019-07-02 10:38 UTC by Michal-Chatlas1221

2019-07-02 12:19 UTC, Michal-Chatlas1221 commented
Decided to run composer as root for now. If we were to use host user we would need to wrap the application container to use it as well

2019-07-03 09:15 UTC, harnash requested changes

2019-07-03 09:15 UTC, harnash commented on docker/devbox/README.md
> +docker build -f composer/Dockerfile -t c ../../../app/ && docker run -it c php composer.phar require some/stuff
I would split it into two separate commands / sections:
1. For running composer only (it should use image pushed to artifactory so we do not need to build this image every time (with some tag: `latest` perhaps)
2. For re-building the above image if needed (some configuration change or base was changed and needs rebuild, etc.)

2019-07-03 09:15 UTC, harnash commented on docker/devbox/composer/Dockerfile
> +ADD . /usr/wikia/slot1/current/src
It is common to use `VOLUME` in this case so you can reuse the image (we do that for devbox images). This way you can build one image and push it to repository and use it with your current app code.

2019-07-03 09:15 UTC, harnash commented on docker/devbox/composer/Dockerfile
> +CMD ["php composer.phar"]
I would use`gosu` https://github.com/Wikia/mobile-wiki/blob/dev/Dockerfile.devbox#L22 as @Grunny suggested to not mess up directory/files permissions.

2019-07-03 12:28 UTC, harnash approved these changes
One small remark. Rest LGTM

2019-07-03 12:28 UTC, harnash commented on docker/devbox/composer/wrapper.sh
> +gosu docker_user git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf ssh://git@github.com/
I believe we do not need that here

2019-07-05 07:49 UTC, harnash requested changes

2019-07-05 07:49 UTC, harnash commented on docker/devbox/composer/Dockerfile
> +CMD ["php composer.phar"]
Shouldn't it be now like this?
```suggestion
CMD ["php composer"]
```

2019-07-05 07:53 UTC, harnash approved these changes

2019-07-05 08:17 UTC, merged