SER-3277 | Change Phalanx block notice
Wikia/app pull request #17464
Opened 2019-09-18 15:13 UTC by slayful

After successful CR and QA we need to upload translations and after they're complete download them.

https://wikia-inc.atlassian.net/browse/SER-3277

This PR changes the notice from:
```
You can contact VSTF or another administrator to discuss the block. Please include all details in the above box in any queries you make.
```
to
```
You can contact Fandom staff or an administrator to discuss the block. Please include all details in the above box in any queries you make.
```

This PR changes the notice from:
```
You can contact VSTF or another administrator to discuss the block. Please include all details in the above box in any queries you make.
```
to
```
You may contact Fandom staff or an administrator to discuss the block.
Please include all of the details above in any queries you make.
```

and also
```
You may contact VSTF or one of the other administrators to discuss the block.
[...]
Please include all above details in any queries you make.
```
to
```
You may contact Fandom Support or an administrator to discuss the block.
Please include all of the details above in any queries you make.
```

Use the following commands:
```
crowdin --project-config crowdin-global-a.conf upload-branch
crowdin --project-config crowdin-global-b.conf upload-branch
```

2019-09-18 19:28 UTC, mszabo-wikia commented on extensions/GlobalMessages/GlobalMessagesA.i18n.php
> +You may contact [[Special:Contact|Fandom Support]] or an [[Special:ListUsers|{{MediaWiki:group-sysop-member}}]] to discuss the block.
I believe this will also affect local block notices ("You may contact $blockingAdminName or one of the other administrators..."). Is this intended?

2019-10-16 11:37 UTC, mszabo-wikia commented on extensions/GlobalMessages/GlobalMessagesA.i18n.php
>  Note that you may not use the "e-mail this user" feature unless you have a valid e-mail address registered in your [[Special:Preferences|user preferences]] and you have not been blocked from using it
We could remove this line because we've removed the email user feature a few years ago

2019-10-16 11:37 UTC, mszabo-wikia commented on extensions/wikia/ArticleComments/classes/ArticleCommentList.class.php
> +			$blockerLink =  '[[Special:Contact|' . wfMessage( 'fandom-support' ) . ']]';
->text()

2019-10-17 06:28 UTC, Grunny requested changes
What about the use of this message in `Title`: https://github.com/Wikia/app/blob/9ec9f65/includes/Title.php#L2150-L2170

2019-10-17 06:28 UTC, Grunny commented on extensions/wikia/ArticleComments/classes/ArticleCommentList.class.php
> +			$blockerLink =  '[[Special:Contact|' . wfMessage( 'fandom-support' ) . ']]';
```suggestion
			$blockerLink =  '[[Special:Contact|' . wfMessage( 'fandom-support' )->plain() . ']]';
```

2019-10-28 10:50 UTC, pwojcik86 approved these changes

2019-10-29 12:15 UTC, slayful commented
LGTM

2019-10-29 12:49 UTC, mszabo-wikia approved these changes

2019-11-12 14:45 UTC, merged