ADEN-9458 Fix missing labrador for garfield
Wikia/app pull request #17500
Opened 2019-10-09 09:20 UTC by preludek

2019-10-09 13:20 UTC, jacekbj commented on extensions/wikia/AdEngine3/src/bill-the-lizard-wrapper.js
> +        const projects = btlConfig.projects || config.projects;
Variable `config` does not exist.

2019-10-09 13:24 UTC, jacekbj requested changes
Please remove the redundant variable.

2019-10-09 14:26 UTC, preludek commented on extensions/wikia/AdEngine3/src/bill-the-lizard-wrapper.js
> +        const projects = btlConfig.projects || config.projects;
👍

2019-10-10 06:51 UTC, jacekbj approved these changes
Checking if geo is right in order to track sth is very obscure yet effective.

2019-10-11 07:02 UTC, merged