DE-4530 Add a controller which returns article data required by the recommendations service
Wikia/app pull request #17537
Opened 2019-10-24 14:38 UTC by mikulskibartosz

Issue
The recommendations module displays social media icons instead of nice-looking article thumbnails.

Cause
The implementation returns the first image assigned to the article instead of using the image returned by ImageServing.

Solution
Create a new endpoint which returns the article thumbnails using ImageServing directly (also the minimal picture dimensions have been set to 400x400).

In this implementation, the caller must request pictures for every wiki separately (by specifying the X-Mw-Wiki-Id header).

2019-10-25 12:23 UTC, mszabo-wikia requested changes

2019-10-25 12:23 UTC, mszabo-wikia commented on includes/wikia/api/RecommendationTileApiController.class.php
> +		if($articleIds)
Let's remove this condition if it is unused

2019-10-25 12:23 UTC, mszabo-wikia commented on includes/wikia/api/RecommendationTileApiController.class.php
> +		$articleIds = explode( ',', $this->request->getVal( 'ids', null ) );
minor: we can use `str_getcsv` instead

2019-10-25 12:23 UTC, mszabo-wikia commented on includes/wikia/api/tests/RecommedationTileApiControllerTest.php
> +class TestableRecommendationTileApiController extends RecommendationTileApiController {
We could use PHPUnit mock objects instead of custom mocks

2019-10-25 12:23 UTC, mszabo-wikia commented on includes/wikia/api/tests/RecommedationTileApiControllerTest.php
> +		$responseItems = get_object_vars($responseItems);
(array)$responseItems

2019-10-25 12:23 UTC, mszabo-wikia commented on includes/wikia/api/tests/RecommedationTileApiControllerTest.php
> +		$this->assertEquals('image_url_1', $first['thumbnail']);
code should be spacey - see guidelines https://github.com/Wikia/guidelines/tree/master/PHP, there's an IntelliJ code style too :)

2019-10-25 12:23 UTC, mszabo-wikia commented on includes/wikia/api/RecommendationTileApiController.class.php
> +				$result[ $id ] = $thumbnail;
$result[ $id ] = $images[$id][0]['url'] ?? null;

2019-10-28 11:08 UTC, mikulskibartosz commented
@mszabo-wikia could you please review the code again?

2019-10-28 11:18 UTC, mszabo-wikia commented on includes/wikia/api/RecommendationTileApiController.class.php
> +		$ids = !is_array( $articleIds ) ? [ $articleIds ] : $articleIds;
$articleIds should always be an array here, so we could remove this check and add a type hint

2019-10-28 12:49 UTC, mszabo-wikia approved these changes

2019-11-05 15:22 UTC, JackThePie approved these changes

2019-11-05 15:24 UTC, mszabo-wikia commented on includes/wikia/api/RecommendationTileApiController.class.php
> +				'some_config_url' => $wgChatPublicHost
these last two items should probably be removed 😉

2019-11-06 09:38 UTC, mikulskibartosz commented on includes/wikia/api/RecommendationTileApiController.class.php
> +				'some_config_url' => $wgChatPublicHost
yes, I needed it only to verify that I use the correct DC during stress tests ;)

2019-11-06 12:15 UTC, mszabo-wikia commented on includes/wikia/api/RecommendationTileApiController.class.php
> +		global $wgChatPublicHost;
These two global declarations can be removed

2019-11-07 14:05 UTC, merged