ADEN-9643 | Move fmr-rotator to ad-engine
Wikia/app pull request #17606
Opened 2019-11-29 07:31 UTC by bckatarzyna

2019-11-29 09:13 UTC, Bielik20 requested changes

2019-11-29 09:13 UTC, Bielik20 commented on extensions/wikia/AdEngine3/src/slots.js
> +    const rotator = new FmrRotator(slotName, 'incontent_boxad_', btRec);
indentation - I know IDE hides it.

2019-11-29 09:13 UTC, Bielik20 commented on extensions/wikia/AdEngine3/src/slots.js
> +    rotator.rotateSlot(slotName);
ditto

2019-12-02 11:59 UTC, fraszczakszymon approved these changes

2019-12-02 11:59 UTC, Bielik20 approved these changes

2019-12-05 14:05 UTC, merged