(PLATFORM-4513) Make InterwikiEdit work with both versions of MediaWiki
Wikia/app pull request #17702
Opened 2020-01-08 16:28 UTC by Grunny

Make InterwikiEdit work with wikis on both versions of MediaWiki, so that the
current special page can be used to manage the links on all wikis while we are
migrating communities to the UCP.

This extension needs a rewrite, but since we will do so when porting it to the UCP,
I'm leaving it relatively untouched here.

/cc @Wikia/core-platform-team

2020-01-20 11:12 UTC, mszabo-wikia approved these changes
Lovely stuff

2020-01-24 12:56 UTC, themech approved these changes

2020-01-31 08:38 UTC, maaartyyynaa requested changes

2020-01-31 08:38 UTC, maaartyyynaa commented on extensions/wikia/WikiFactory/WikiFactory.php
> +	public static function isUCPWiki( int $wikiId ): bool {
I've created similiar function: https://github.com/Wikia/app/blob/dev/extensions/wikia/WikiFactory/WikiFactory.php#L3642-L3655, let's remove it or use it here too.

2020-02-05 11:44 UTC, harnash requested changes

2020-02-05 11:44 UTC, harnash commented on extensions/wikia/SpecialInterwikiEdit/SpecialInterwikiEdit.php
> +function wfSIWEMaybeAddExtraFields( int $wikiId, array $fields ): array {
```suggestion
function wfSIWEAddExtraFields( int $wikiId, array $fields ): array {
```

2020-02-05 11:44 UTC, harnash commented on extensions/wikia/SpecialInterwikiEdit/SpecialInterwikiEdit.php
> +						$fields = wfSIWEMaybeAddExtraFields( $wikiaID, $fields );
```suggestion
						$fields = wfSIWEAddExtraFields( $wikiaID, $fields );
```

2020-02-05 11:44 UTC, harnash commented on extensions/wikia/SpecialInterwikiEdit/SpecialInterwikiEdit.php
> +						$fields = wfSIWEMaybeAddExtraFields( $wikiaID, $fields );
```suggestion
						$fields = wfSIWEAddExtraFields( $wikiaID, $fields );
```

2020-02-05 11:44 UTC, harnash commented on extensions/wikia/SpecialInterwikiEdit/SpecialInterwikiEdit.php
> +		$fields = wfSIWEMaybeAddExtraFields( $linker, $fields );
```suggestion
		$fields = wfSIWEAddExtraFields( $linker, $fields );
```

2020-02-05 12:03 UTC, harnash approved these changes

2020-02-11 15:35 UTC, merged