Conditionally redirected users to ucp CNW
Wikia/app pull request #17778
Opened 2020-02-26 15:32 UTC by Michal-Chatlas1221

2020-03-03 20:54 UTC, abador commented on includes/wikia/Extensions.php
> +$wgUCPCommunityCNWAddress = 'https://ucp-internal-test-community.fandom.com/wiki/Special:CreateNewWiki';
shouldn't this be changed to ucp.fandom.com ?

2020-03-06 12:05 UTC, harnash requested changes

2020-03-06 12:05 UTC, harnash commented on extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
> +		return $wgUser->isStaff();
How about:
```suggestion
		return $this->getContext()->getUser()->isStaff();
```

2020-03-06 12:05 UTC, harnash commented on extensions/wikia/CreateNewWiki/SpecialCreateNewWiki.class.php
> +			$out->redirect( WikiFactory::getLocalEnvURL( $wgUCPCommunityCNWAddress ) );
This might work on prod but won't probably work on dev since there  is different wiki. We need to sync those after we switch

2020-03-06 12:45 UTC, harnash commented on extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
>  		global $wgUser;
```suggestion
```

2020-03-06 12:46 UTC, harnash commented on extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
> +
```suggestion
```

2020-03-06 12:46 UTC, harnash approved these changes

2020-03-10 09:17 UTC, merged