Change migration messages to be better for the current migration, PLA…
Wikia/app pull request #17913
Opened 2020-05-19 12:44 UTC by abador

…TFORM-4807

2020-05-21 13:39 UTC, themech commented on extensions/wikia/FandomComMigration/FandomComMigration.i18n.php
> +	'fandom-com-migration-before' => "Attention: Over the next few weeks, we are migrating your community to the Unified Community Platform. Find out more on [https://community.fandom.com/wiki/Help:Unif
Should we reuse the same message? something ucp related would be more appropriate. 
I'm not an expert in i18, but when reusing the message don't we risk downloading translations for the previous string?

2020-05-21 13:47 UTC, themech requested changes

2020-05-21 13:47 UTC, themech commented on extensions/wikia/FandomComMigration/FandomComMigrationHooks.class.php
> +			if ( static::isMigrationScheduled() ) {
it duplicates the `if` you have above

2020-05-21 13:47 UTC, themech commented on extensions/wikia/FandomComMigration/FandomComMigrationHooks.class.php
> -		global $wgFandomComMigrationDone, $wgFandomComMigrationCustomMessageBefore,
I think Growth is using this for displaying various messages on wikis, for example on https://fishing-simulator.fandom.com/wiki/Fishing_Simulator_Wiki. I think they won't be happy if you remove it

2020-05-22 13:59 UTC, rbroering requested changes
The help page link has no text:
`Find out more on [https://community.fandom.com/wiki/Help:Unified_Community_Platform] this Fandom help page.`
should be
`Find out more on [https://community.fandom.com/wiki/Help:Unified_Community_Platform this Fandom help page].`

2020-05-25 11:13 UTC, themech approved these changes

2020-05-27 13:30 UTC, merged