PLATFORM-4806 | Change all references to VSTF in code to SOAP
Wikia/app pull request #18004
Opened 2020-07-06 12:18 UTC by maaartyyynaa

2020-07-07 13:45 UTC, Markus-Rost requested changes
Fix typo `SOAD` to `SOAP`

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/GlobalMessages/GlobalMessagesR.i18n.php
> +| [[Special:ListUsers/sysop|{{int:group-sysop}}]] <b>&middot;</b> [[Special:ListUsers/bureaucrat|{{int:group-bureaucrat}}]] <b>&middot;</b> [[Special:ListGlobalUsers/helper|{{int:group-helper}}]] <b>
```suggestion
| [[Special:ListUsers/sysop|{{int:group-sysop}}]] <b>&middot;</b> [[Special:ListUsers/bureaucrat|{{int:group-bureaucrat}}]] <b>&middot;</b> [[Special:ListGlobalUsers/helper|{{int:group-helper}}]] <b>&middot;</b> [[Special:ListGlobalUsers/soap|{{int:group-soap}}]] <b>&middot;</b> [[Special:ListGlobalUsers/staff|{{int:group-staff}}]] <b>&middot;</b> <small>[[Special:ListUsers|wszyscy...]]</small>
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserProfilePage.i18n.php
> +	'user-identity-box-group-soad' => 'SOAD',
```suggestion
	'user-identity-box-group-soap' => 'SOAP',
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserProfilePage.i18n.php
> +	'user-identity-box-group-soad' => 'Frivillig spambekämpningsstyrka',
```suggestion
	'user-identity-box-group-soap' => 'Frivillig spambekämpningsstyrka',
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserProfilePage.i18n.php
> +	'user-identity-box-group-soad' => 'Kusang-loob na Hukbo na Panglaban sa Basurang Liham',
```suggestion
	'user-identity-box-group-soap' => 'Kusang-loob na Hukbo na Panglaban sa Basurang Liham',
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserProfilePage.i18n.php
> +	'user-identity-box-group-soad' => 'SOAD',
```suggestion
	'user-identity-box-group-soap' => 'SOAP',
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserProfilePage.i18n.php
> +	'user-identity-box-group-soad' => 'SOAD',
```suggestion
	'user-identity-box-group-soap' => 'SOAP',
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserTagsStrategy.class.php
> +		'soad',
```suggestion
		'soap',
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/WikiaIrcGateway/WikiaIrcGateway.i18n.php
> +* #wikia-soad
```suggestion
* #wikia-soap
```

2020-07-07 13:45 UTC, Markus-Rost commented on includes/Block.php
> +	 * SUS-288: Hide blocker name from logs and error pages if the block was made by staff/SOAD
```suggestion
	 * SUS-288: Hide blocker name from logs and error pages if the block was made by staff/SOAP
```

2020-07-07 13:45 UTC, Markus-Rost commented on includes/Block.php
> +	 * (i.e. if the block was made by staff/SOAD)
```suggestion
	 * (i.e. if the block was made by staff/SOAP)
```

2020-07-07 13:45 UTC, Markus-Rost commented on includes/api/ApiQueryUsers.php
> +	 * (it is internal request or request by staff/SOAD/helper user)
```suggestion
	 * (it is internal request or request by staff/SOAP/helper user)
```

2020-07-07 13:45 UTC, Markus-Rost commented on includes/api/wikia/ApiQueryUserGroupMembers.php
> +			'api.php?action=query&list=groupmembers&gmgroups=soad|staff&gmlimit=15',
```suggestion
			'api.php?action=query&list=groupmembers&gmgroups=soap|staff&gmlimit=15',
```

2020-07-07 13:45 UTC, Markus-Rost commented on includes/wikia/Wikia.php
> +		// Allow trusted users to edit interface messages (util, soad, select admins)
```suggestion
		// Allow trusted users to edit interface messages (util, soap, select admins)
```

2020-07-07 13:45 UTC, Markus-Rost commented on includes/wikia/tests/HideBlockerNameTest.php
> +		yield 'user name hidden for soad' => [ 3, true ];
```suggestion
		yield 'user name hidden for soap' => [ 3, true ];
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
> +		'soad',
```suggestion
		'soap',
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
> +	$wgGroupPermissions['soad']['nuke'] = true;
```suggestion
	$wgGroupPermissions['soap']['nuke'] = true;
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
> +$wgGroupPermissions['soad']['achievements-exempt'] = true;
```suggestion
$wgGroupPermissions['soap']['achievements-exempt'] = true;
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
> +$wgGroupPermissions['soad']['admindashboard'] = true;
```suggestion
$wgGroupPermissions['soap']['admindashboard'] = true;
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
> +$wgGroupPermissions['soad']['imagereview'] = true;
```suggestion
$wgGroupPermissions['soap']['imagereview'] = true;
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
> +$wgGroupPermissions['soad']['promoteimagereview'] = true;
```suggestion
$wgGroupPermissions['soap']['promoteimagereview'] = true;
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
> +$wgGroupPermissions['soad']['multidelete'] = true;
```suggestion
$wgGroupPermissions['soap']['multidelete'] = true;
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserProfilePage.i18n.php
> +	'user-identity-box-group-soad' => 'SOAD',
```suggestion
	'user-identity-box-group-soap' => 'SOAP',
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserProfilePage.i18n.php
> +	'user-identity-box-group-soad' => 'SOAD',
```suggestion
	'user-identity-box-group-soap' => 'SOAP',
```

2020-07-07 13:45 UTC, Markus-Rost commented on extensions/wikia/UserProfilePageV3/UserTagsStrategy.class.php
> +					$tags[] = wfMessage( 'user-identity-box-group-soad' )->escaped();
```suggestion
				case 'soap':
					$tags[] = wfMessage( 'user-identity-box-group-soap' )->escaped();
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
> +		$this->groupsSelfRemovableByGroup['soad'] = [ 'rollback', 'bot', 'sysop', 'bureaucrat' ];
```suggestion
		$this->groupsSelfAddableByGroup['soap'] = [ 'rollback', 'bot', 'sysop' ];
		$this->groupsSelfRemovableByGroup['soap'] = [ 'rollback', 'bot', 'sysop', 'bureaucrat' ];
```

2020-07-07 13:45 UTC, Markus-Rost commented on lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
> +		$wgGroupPermissions['soad']['abusefilter-private'] = true;
```suggestion
		$wgGroupPermissions['soap']['abusefilter-modify'] = true;
		$wgGroupPermissions['soap']['abusefilter-modify-restricted'] = true;
		$wgGroupPermissions['soap']['abusefilter-revert'] = true;
		$wgGroupPermissions['soap']['abusefilter-log-detail'] = true;
		$wgGroupPermissions['soap']['abusefilter-private'] = true;
```

2020-07-13 11:31 UTC, maaartyyynaa commented
Closing this messy one. Changes in https://github.com/Wikia/app/pull/18022 and https://github.com/Wikia/app/pull/18024

2020-07-13 11:31 UTC, closed without merging